### ISSUE TITLE
Make apps for other platforms like android with custom python libraries

### ISSUE THREAD

**Issue by arian81** [beeware/toga#1024]
**Is your feature request related to a problem? Please describe.**
I put a lot of time to develop an app but just when I compiled and run it on android the app would crash because it doesn't have access to custom libraries installed by pip.

**Describe the solution you'd like**
A simple way to add custom libraries as requirements to be compiled alongside the main app so it would work.

**Additional context**

![image](https://user-images.githubusercontent.com/35879206/90203043-8b0a2500-ddad-11ea-8e1d-55bc56d48993.png)

**Comment by freakboy3742** [comment]
Thanks for the report; however, this isn't a Toga problem - it's a Briefcase problem. See beeware/briefcase#471 for details.
