### ISSUE TITLE
save_file_dialog -  file_types argument

### ISSUE THREAD

**Issue by OhadNir9** [beeware/toga#1034]
**Describe the bug**
save_file_dialog does nothing with the file_types list passed to it.

**To Reproduce**
Call save_file_dialog from a toga.Window instance, pass some strings list as the file_types argument (say ["png","jpg"]).
The resulting file types list is empty, regardless of the file_types argument.

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: 0.3.0.dev22

**Additional context**
Looking into the implementation, it looks like nothing is done with the file_types argument.
This, in contradiction to <a href="https://toga.readthedocs.io/en/latest/reference/api/window.html#toga.window.Window.save_file_dialog"> documentation .</a></br>

From toga_winforms/window.py:
```python
    def save_file_dialog(self, title, suggested_filename, file_types):
        dialog = WinForms.SaveFileDialog()
        dialog.Title = title
        if suggested_filename is not None:
            dialog.FileName = suggested_filename
        if dialog.ShowDialog() == WinForms.DialogResult.OK:
            return dialog.FileName
        else:
            raise ValueError("No filename provided in the save file dialog")
```

**Comment by OhadNir9** [comment]
I think adding this:
```python
        if file_types is not None:
            dialog.Filter = self.build_filter(file_types)
```
to save_file_dialog will solve the issue, I'll make the PR tomorrow.

**Comment by freakboy3742** [comment]
Thanks for the report! I haven't tried the fix you suggest, but it definitely seems like it makes sense - I look forward to seeing your patch!
