### ISSUE TITLE
Button / select box - font size attribute

### ISSUE THREAD

**Issue by AndiLeni** [beeware/toga#1037]
**Describe the bug**
`font_size` attribute is not working for buttons and select boxes.

**To Reproduce**
```
button = toga.Button(
            'Eintrag speichern',
            on_press=self.say_hello,
            style=Pack(padding=5, font_size=15)
        )
```
or 
`toga.Selection(items=['m', 'w'], style=Pack(font_size=15))`

**Expected behavior**
The font size should change.

**Screenshots**
/

**Environment:**
 - Operating System: windows 10
 - Python version: 3.8.5
 - Software versions:
   - Briefcase: 0.3.3
   - toga-core==0.3.0.dev22
   - toga-winforms==0.3.0.dev22

**Additional context**
/

**Comment by shape-warrior-t** [comment]
I've been looking into this issue. As of now, on Windows, `font_size` works for buttons, but not select boxes. The same thing also happens to be true for Android, based on my testing.

I'll try and see if there's anything I can do to quickly fix this bug.

**Comment by freakboy3742** [comment]
#1761 Addressed this issue, and added runtime tests of this behavior.
