### ISSUE TITLE
Suppressing std-err

### ISSUE THREAD

**Issue by soniceroy** [beeware/toga#106]
This might be more of a need for advice than an issue. 
I use Linux Deepin 15.3, which is based on Debian Sid Unstable.
GTK spits out lots of warnings to std-err when used, (might be more an OS issue or GTK being overly sensitive).
When I call the script directly i can filter out GTK warnings with grep:
{ python3 hello_world.py 2> >(grep -v Gtk-WARNING >&2); }

but according to the docs, i'm supposed to call the script as a module. However, the line below won't work:
{ python3 -m hello_world 2> >(grep -v Gtk-WARNING >&2); }

Any advice on how i can call in a module and still filter, or better yet a way/fix without this work-around?

**Comment by TiberiumPY** [comment]
I think toga can't suppress these warnings (I personally see them while running almost ANY app from terminal but everything works fine)

**Comment by freakboy3742** [comment]
Yes - this is a "GTK being noisy" issue. There's not much we can do to make it quiet - other than, of course, fixing the reason why it's complaining. Rather than developing a mechanism to hide errors, I'd rather merge fixes that *fix* the underlying errors.

**Comment by freakboy3742** [comment]
Closing this as a "wontfix". If GTK is being noisy, that is presumably for a reason, and we should fix that reason.
