### ISSUE TITLE
Enhancing the documentation

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1071]
The documentation does not clarify how the user can be create `Toga` project, that work perfectly and as we expect, from scratch. In `Running the app` section in `Docs » Tutorials » Your first Toga app`, it must be clarify the method that makes all feature of `Toga` are working. The documentation says that to run the application write `python -m helloworld` in your terminal of `venv`, this will work good in most cases but in some cases, like when `your app` contains some icons, some features will fail.
### Describe the solution you'd like
I suggest clarify the following in the documentation:

You can run Python script in multiple ways. But in toga, to the project work as we expect, you must be follow the following steps:
1. Create folder, called it for example, `helloworld`.
2. In this folder create three files `__init__.py`, `__main__.py` and your python script, for example `app.py`.
3. In `__main__.py` file, write the following:
    ```python
    from helloworld.app import main

    if __name__ == '__main__':
        main().main_loop()
    ```
4. Finally, to run your project, execute the following in shell:
    - `cd Location_of_helloworld_folder`.
    - `python -m helloworld`, where `helloworld` is the folder name that contains `__init__.py`, `__main__.py` and `app.py`.

I'm open to suggestions, if I missed thing please let me know. If these changes make sense, I will make PR that update the documentation.

### Issue to be solved
This clarifying will solve the issue of not appearing the icons #1052

**Comment by MuhammadMouradG** [comment]
@freakboy3742, is the suggestion make sense or I missed something?

**Comment by freakboy3742** [comment]
@MuhammadMouradG So - I broadly agree that there's a need for more documentation about the conventions that exist for how a Toga app will find metadata, and how the way you start the Python process will impact on the availability of that metadata.

However, I'm hesitant to frame that as working "as expected" - the current behavior is entirely *expected*; but some modes of operation have limitations. Those limitations are entirely expected and predictable; whether they even *matter* is a value judgement depending on what you're trying to do.

The "default recommendation" is really "Use the Briefcase bootstrap". But that's no more than an easy recommendation. Toga is, ultimately, Python. Any way of starting the process is valid. However, some of the options have consequences.

**Comment by MuhammadMouradG** [comment]
I completely agree with you, but it seems that I have mistyped what I mean. What I mean exactly is that as a toga user and not as a toga developer, what I care about is that when I follow the instructions, I get the same results that are mentioned in the tutorial, otherwise I must be alerted, and tell me that we expect it and we know why this happened and how to treat it. Because, again as a user of toga and not a developer of it, if I didn't find that I might think that the project is still in its early stages or that it hasn't updated for a while, and I end up saying "How can the tutorials not work as they have described in the documentation". "This exactly what happened to me :-)"

So, if the "default recommendation" is really "Use the Briefcase bootstrap", isn't it a good thing to mention that in the documentation?

**Comment by MuhammadMouradG** [comment]
Well, I got what you mean. Now we need to clarify how `Toga` will find metadata and also recommend to the user using `Briefcase Bootstrap` to see what he is reading in the documentation and avoiding some modes of operation that have limitations.

**Comment by freakboy3742** [comment]
Closing as a generic ticket to "improve documentation" won't progress us toward having better documentation.
