### ISSUE TITLE
Enhancing imageview implemantation

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1074]
In `ImageView` what are the things that still need implementation
```python
class ImageView(Widget):
    """

    Args:
        image (:class:`toga.Image`): The image to display.
        id (str): An identifier for this widget.
        style (:obj:`Style`):
        factory (:obj:`module`): A python module that is capable to return a
            implementation of this class with the same name. (optional & normally not needed)

    Todo:
        * Finish implementation.
    """
```

Also, in the same file of `imageview`, are these lines important, as I understood `style` object will do the work of `scaling` and `alignment`.
```python

        # @property
        # def alignment(self):
        #     return self._alignment

        # @alignment.setter
        # def alignment(self, value):
        #     self._alignment = value
        #     self._impl.setAlignment_(NSTextAlignment(self._alignment))

        # @property
        # def scaling(self):
        #     return self._scaling

        # @scaling.setter
        # def scaling(self, value):
        #     self._scaling = value
        #     self._impl.setAlignment_(NSTextAlignment(self._scaling))
```

**Comment by MuhammadMouradG** [comment]
@freakboy3742 what do you think about this?

**Comment by freakboy3742** [comment]
@MuhammadMouradG Yes; there is work to be done on the ImageView API. What is needed at this point is a complete API proposal. The methods you've shown commented out are placeholders that have, from the look of it, been copied from another widget (a text input widget, by the look of it).

If you're interested in working on such a proposal: Essentially, anything that you would control in a *web* context with CSS should be controlled by the Style attribute; anything else should be a native widget API.

**Comment by MuhammadMouradG** [comment]
Currently, I'm trying to write API proposal for `imageview` and others. For `imageview` API, what do we intend for this library to do, will it do what Photoshop does, for example (cutting, rotating, mirror, smart selection, color inversion, text recognition, writing on the image, ...), or just simple operations such as cutting, rotating, mirror, etc...

If I missed something, please let me know.

**Comment by freakboy3742** [comment]
ImageView isn't intended to be "Photoshop". We need some basic image *display* features, but I'd consider any sort of image processing or filtering to be out of scope.

As a guide - I'd consider the aim to be API parity with an `<img>` tag in a web browser with *basic* CSS. That means properties like scaling, alignment and tiling are in scope; but rotation, mirroring, color manipulation, or any more advanced image manipulation is not.

**Comment by MuhammadMouradG** [comment]
Well, as I understand, the `<img>` tag and basic CSS can do the following:
- [x] include image.
- [x] adjust height and width of the image.
- [x] adjust the transparency of the image.
- [x] add alternative text to the image.
- [x] add a clickable link to image.

Now, the current implementation of `Toga` together with `style` object can do the following:
- [x] include image.
- [x] adjust height and width of the image.
- [ ] adjust the transparency of the image.
- [ ] add alternative text to the image.
- [ ] add a clickable link to image.

So, we need to implement unchecked items in the previous list. Now, if these unchecked items is required please let me know and add another items if exist.

**Comment by MuhammadMouradG** [comment]
@freakboy3742 This may be seem clear, but for me I'm really confused. So, could you please guide me to what we need implement?

**Comment by freakboy3742** [comment]
To some extent you've answered your own question: Basic CSS lets you do <list of things>; Toga currently allows <subset of that list of things>; that means we need to add the things that aren't currently implemented.

That said:
 * alt-text probably isn't required. While alt-text is important in a web context for accessibility, I'm not sure the same applies to GUI interfaces.
 * "adjust height and width" is certainly *present* in Toga at present - but it's nowhere near as flexible as it is in CSS. 
    - Should an image expand to fill available space, or stay a fixed size? 
    - If it resizes, should it preserve aspect ratio? 
    - If it preserves aspect ratio, which axis controls size? 
    - How is the image content aligned (left, right or centered)? 
    - If the image is smaller than a given axis, should it repeat in that axis (i.e., image tiling)?

The task at this point is to make an API proposal. 

If you wanted to start simple - take something like the "clickable link" feature. That's a feature that is currently missing. So - propose how we'd add it. As a guide, we have existing examples of "onclick" handlers in Toga, so there won't be an extensive "design" process - you can probably move right to implementation. But for the other features (like transparency or the height/width adjustments I mentioned), you'll need to make a proposal for the end-user interface to that feature.

**Comment by freakboy3742** [comment]
Closing as the proposal doesn't appear to be heading in a direction that is likely to be accepted.
