### ISSUE TITLE
Enhancing imageview implemantation

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1075]
In `ImageView` what are the things that still need implementation
![Screenshot at 2020-09-24 14-58-26](https://user-images.githubusercontent.com/50509521/94148243-e7a93700-fe65-11ea-913a-cb653b447155.png)

Also, is these lines is important now, I expect `style` object will do the work of `scaling` and `alignment`.
![Screenshot at 2020-09-24 14-57-26](https://user-images.githubusercontent.com/50509521/94148266-ed9f1800-fe65-11ea-96d4-2ee6d72a5447.png)

**Comment by MuhammadMouradG** [comment]
This is a duplicated issue, because my poor internet connection, please delete it.

**Comment by freakboy3742** [comment]
Closing by request. 

As a side note - if you're including code samples, it's a lot more helpful to include them as text, rather than a screenshot. Github markdown can format blocks of text if you include it in triple quotes:
```
def methods_like_this_one(self):
    calling_other_methods()
```
