### ISSUE TITLE
API Proposal | ImageView widget

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1100]
Taking inspiration from #1074, I would like to propose an API for `ImageView` widget.

```python
import toga
import toga.style.pack

# A representation of image content
image = toga.Image("resources/myImage.png")

# Create image view, alignment image content to the left of its container and tiling it,
# if it is smaller than its allocated space.
ImageView = toga.ImageView(style=Pack(alignment=LEFT), image=image, tiling=True, on_press=myfunction)

# Image transparency
ImageView.transparency = 0.5

# Expand available space
ImageView.flex = True

# Image aspect ratio, if flex=False aspect_ration will ignored
# aspect_ratio is a 3-tuple of width, height and control axis, respectively.
ImageView.aspect_ratio = (4, 3, 'x')
```
What do you think? If you approve, I'll go on implementing it before my university start :-).

**Comment by freakboy3742** [comment]
So - there's at least 4 features being proposed here; and unfortunately, a single example of usage isn't really a full API proposal. However, based on what I understand of your proposal:

It looks like you're proposing these as "top level" APIs, rather than features that are applied as style. As a general rule, if CSS provides a way to control a feature, we should be using a style, rather than a top level feature.

The term "flex" seems like it's overloaded here - it's already used in the layout engine. Unless it has a direct relationship to the flex being used in layout, we need a different word here. It's also not clear how "flex=True" interacts with the other features of this API.

I'm not wild about the idea of a "magic tuple" for aspect ratio - that feels like it's 2 independent properties (aspect ratio, and axis).

It isn't clear to me how "tiling=True" is interpreted. There are 2 possible tiling axes.

**Comment by MuhammadMouradG** [comment]
This is after editing:

```python
import toga

# A representation of image content
image = toga.Image("resources/myImage.png")

# Create image view, alignment image content to the left of its container and tiling it,
# if it is smaller than its allocated space.
ImageView = toga.ImageView(image=image, tiling_x=bool, tiling_y=bool, on_press=myfunction)

ImageView.style.update(alignment=toga.style.pack)    # CENTER or LEFT or ...

# Image transparency
# `0.0`: There is no transparency.
# `1.0`: The maximum value of transparency that image can be hold.
ImageView.transparency = float    # from 0.0 to 1.0

ImageView.ratio_with_control_axis = (int, int, str)    # str either 'x' or 'y', default is 'x'
```
If the `height` and `width` in `style` property are specified the image will be have a fixed size and `ratio_with_control_axis` will be ignored. If the `height` and `width` in `style` property are not specified the image will be fill its container depending on `ratio_with_control_axis` which specify the aspect ration when the image resized and the control axis on this aspect ratio. I changed the `aspect_ratio` property to `ratio_with_control_axis` to overcome the problem of feeling it's 2 independent properties, but I don't know if this will overcome the problem.

What do you think?

**Comment by MuhammadMouradG** [comment]
This is after editing:

```python
import toga

# A representation of image content
image = toga.Image("resources/myImage.png")

# Create image view, alignment image content to the left of its container and tiling it,
# if it is smaller than its allocated space.
ImageView = toga.ImageView(image=image, tiling_x=bool, tiling_y=bool, on_press=myfunction)

ImageView.style.update(alignment=toga.style.pack)    # CENTER or LEFT or ...

# Image transparency
# `0.0`: There is no transparency.
# `1.0`: The maximum value of transparency that image can be hold.
ImageView.transparency = float    # from 0.0 to 1.0

ImageView.ratio_with_control_axis = (int, int, str)    # str either 'x' or 'y', default is 'x'
```
If the `height` and `width` in `style` property are specified the image will be have a fixed size and `ratio_with_control_axis` will be ignored. If the `height` and `width` in `style` property are not specified the image will be fill its container depending on `ratio_with_control_axis` which specify the aspect ration when the image resized and the control axis on this aspect ratio. I changed the `aspect_ratio` property to `ratio_with_control_axis` to overcome the problem of feeling it's 2 independent properties, but I don't know if this will overcome the problem.

@freakboy3742 What do you think?

**Comment by freakboy3742** [comment]
So - I don't see that you've actually addressed the first - and most important - question/criticism I raised:

Why are these features being treated as attributes of ImageView, rather than style attributes? As I've said previously: anything that can be controlled by CSS in a web context should be controlled by style in a Toga context. 

All the discussion about the remaining properties is essentially moot until we've got that fundamental concept nailed down.

**Comment by MuhammadMouradG** [comment]
Well, the style attributes, as I understood, provide us with the following properties `display`, `visibility`, `direction`, `alignment`, `width`, `height`, `flex`, `padding`, `color`, `background_color`, `font_family`, `text_direction`, `text_align`, `font_size` and `font`. The `width`, `height` and `flex` only can effect on the `ImageView` behavior.

Our concerning here only these three properties, as I can understand, `width`, `height` and `flex`.

Currently, `width` and `height` are used to give the image a fixed size and can not be used to give the image an aspect ratio because its value interpreted as pixels not a ratio.

`flex` used to give a weighting to the image between its siblings, and also can not be used to give the image an aspect ratio.

Finally, the attributes that I propose does not have alternative in `style` attribute then
`transparency` can not be replaced with property in the `style` attribute,
`tiling_x` can not be replaced with property in the `style` attribute,
`tiling_y` can not be replaced with property in the `style` attribute,
`ratio_with_control_axis` can not be replaced with property in the `style` attribute.

This is what I understand, please if I missed something let me know.

**Comment by freakboy3742** [comment]
I'm not talking about style attributes that currently exist in Toga's Pack. I'm talking about style attributes that exist *IN CSS*. CSS is the model to follow here. For example - if you have a HTML document with an IMG tag - how do you change that image's transparency? You use the `opacity` attribute. 

The end goal with Toga is to replace Pack with Colosseum, which is (or will be) a full CSS3 implementation. Any feature we add to Toga needs to be viewed through that lens. If that means we need to add style attributes to Pack, then that's what we need to do as part of this proposal.

**Comment by freakboy3742** [comment]
Closing as the proposal doesn't appear to be going anywhere productive.
