### ISSUE TITLE
Is there a way to add a new line of text while keeping the existing line of text? 

### ISSUE THREAD

**Issue by vosonnshop** [beeware/toga#1101]
Is there a way to add a new line of text while keeping the existing line of text? When I use .value = 'str' then the app will remove the old 'str' before inserting the new 'str'. For example on tkinter just use .insert ('end', '\ ntext')

**Comment by saroad2** [comment]
This can be easily done with:
```python
textinput.value += "This is the new line"
```

Hope it solves your problem, If there's any other thing you want to ask related to that question, feel free to reopen the issue.
