### ISSUE TITLE
Asking how to use "file_types" in open_file_dialog

### ISSUE THREAD

**Issue by vosonnshop** [beeware/toga#1112]
When I bookmark a list like the example below
`    def action_open_file_dialog(self, multi_var, widget=None):
            filenames = self.main_window.open_file_dialog(
                title="Open file with Toga",
                multiselect=multi_var,
                file_types=['gif', 'tiff', 'jpeg', 'bmp', 'png', 'webp']
            )`
The result is a column list, which will prevent the window from displaying all images in the correct format in the list.
How does the window show all the listed formats, instead of having to select files one by one or All files. Similar to the example in HTML.
input type="file"
       id="avatar" name="avatar"
       accept="image/png, image/jpeg"
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

**Comment by freakboy3742** [comment]
I'm not sure I understand the question - are you able to provide details about what platform you're on, what you're expecting to see, and what you're actually seeing?

**Comment by vosonnshop** [comment]
### My code on Pycharm and Windows 10
![image](https://user-images.githubusercontent.com/69602855/96675192-9a50b480-1394-11eb-96ed-2015c1004e62.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/69602855/96675556-54e0b700-1395-11eb-9634-c3809c7c1c7c.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/69602855/96675055-45ad3980-1394-11eb-8752-9034299b42d6.png)

**Comment by freakboy3742** [comment]
Ah - now I understand. This looks like it's a limitation of how we've implemented the Winforms file dialog implementation. It's an easy fix though; I'll commit a fix shortly.

**Comment by vosonnshop** [comment]
Thank you for the feedback, I will be waiting for the correction from you, thanks.
