### ISSUE TITLE
Undocumented API of NSImage?

### ISSUE THREAD

**Issue by SamSchott** [beeware/toga#1115]
**Describe the bug**

The code for `TogaIconView` currently uses a method `NSImage.resizeTo` to resize its icon to 16 x 16:

https://github.com/beeware/toga/blob/cc48b8e9380a29abf616c59c518c80845e62b032/src/cocoa/toga_cocoa/widgets/internal/cells.py#L106-L110

This methods doesn't seem to be documented anywhere and raises an `AttributeError` on macOS High Sierra.

I realise that I originally wrote the code but I cannot recall where I found and why I used this method. It is similarly confusing to me that it seems to work.

**To Reproduce**
Not necessarily a bug because it does work on macOS Mojave and later.

**Environment:**
 - Operating System: macOS High Sierra
 - Python version: Python 3.8
 - Software versions:
   - Toga: 0.3.0.dev24

**Comment by freakboy3742** [comment]
Huh... I'm guessing that the method is silently crashing, and the two constraints aren't being set. Nice catch.

**Comment by SamSchott** [comment]
I think it actually works and does what the name suggests. In particular, if there are multiple image representations for different sizes (think icons) it will also pick the closest one to scale down.

I've only noticed this because I starting using `rescaleTo` in other places in an app and it crashed on macOS High Sierra. It appears to work just fine in Mojave and higher.

In any case, it's usage should be replaced. It may be enough to just use the constraints to automatically resize here. I'll have a look and submit a PR once I have a working alternative.

**Comment by freakboy3742** [comment]
Fixed by #1120.
