### ISSUE TITLE
Bug color property in android

### ISSUE THREAD

**Issue by Eduardo-Vitesse** [beeware/toga#1126]
When I assign a color property to a Label or Button and execute the briefcase dev command, the colors are applied. Plus, if I run the briefcase run android command all colors are not applied. How can I solve this?
NOTE: I am using Windows 10

**Comment by cosmo9able** [comment]
Eu também notei esse bug, não consegui com color= e nem o background_color=, o text_align= também não funciona no android, ja abri outra inssue.

**Comment by freakboy3742** [comment]
I believe this has now been implemented.
