### ISSUE TITLE
no module named toga.style  it's a moduleNotFoundError please help ! 

### ISSUE THREAD

**Issue by chiro94-prox** [beeware/toga#1127]
PS C:\Users\asus\beeware-tutorial\helloworld\src\helloworld>  cd 'c:\Users\asus\beeware-tutorial\helloworld\src\helloworld'; & 'Python' 'c:\Users\asus\.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\lib\python\debugpy\launcher' '57311' '--' 'c:\Users\asus\beeware-tutorial\helloworld\src\helloworld\app.py'
Traceback (most recent call last):
  File "c:\Users\asus\beeware-tutorial\helloworld\src\helloworld\app.py", line 5, in <module>
    from toga.style import Pack
ModuleNotFoundError: No module named 'toga.style'

![Capture d’écran (156)](https://user-images.githubusercontent.com/73724659/97770541-7b1ef900-1af1-11eb-83e5-356c7e7294da.png)

**Comment by freakboy3742** [comment]
I believe you've installed toga 0.2, rather than the 0.3 development branch as the tutorial says - I'm guessing you missed the `--pre` option when running `pip install --pre toga`. If you run `pip install -U --pre toga`, you should be able to fix the problem.
