### ISSUE TITLE
toga.Label() text_align problem on Android

### ISSUE THREAD

**Issue by cosmo9able** [beeware/toga#1128]
Pack(text_align='center') and Pack(text_align=CENTER) doesn't function as expected on Android.

--- 
**Original report**

Pack(text_align='center') ou Pack(text_align=CENTER) não funciona no android,  estou usando Debian 10, ao executar briefcase dev funciona normalmente o alinhamento, apenas no android não funciona.

**Comment by freakboy3742** [comment]
Without a complete reproduction case, it's impossible to verify this report.

**Comment by sictmfx** [comment]
# -*- coding: utf-8 -*-
#I have the same problem

import toga
from toga.style.pack import COLUMN, LEFT, RIGHT, ROW, Pack

from helloworld.web_tools import get_server_msg,set_stop_msg
from travertino.constants import CENTER, BLUE


class HelloWorld(toga.App):

    def startup(self):
        main_box = toga.Box(style=Pack(padding=5, direction=COLUMN, background_color='#000000'))

        server_name_tv = toga.Label('当前服务：未开启',
                                         style=Pack(text_align=CENTER, height=30, background_color=BLUE))
        main_box.add(server_name_tv)
        self.main_window = toga.MainWindow(title='server_name_tv')
        self.main_window.content = main_box
        self.main_window.show()

# briefcase
def main():
    return HelloWorld()

**Comment by freakboy3742** [comment]
Thanks for the reproduction case - I can confirm I'm seeing this problem; my guess is that the label *is* being centered - but the box in which it is centred is the same width as the label, so centering has no effect. However, that's a bug, as the main box *should* be allocated the full width of the screen.

**Comment by freakboy3742** [comment]
This has been addressed as part of #1799.
