### ISSUE TITLE
Question dialog does not return True or False

### ISSUE THREAD

**Issue by durgaswaroop** [beeware/toga#1139]
**Describe the bug**
The `question_dialog` on windows, according to the documentation is supposed to return `True` or `False` depending on if the user has pressed "YES" or "NO". 
```
question_dialog(title, message)
    Opens a dialog with a ‘YES’ and ‘NO’ button.
    Parameters:  .....
    Returns True when the ‘YES’ button was pressed, False when the ‘NO’ button was pressed.
```

But when I tried to print the return value of `self.main_window.question_dialog(..., ...)`, it is showing an integer. 
In my case, I am getting `6` for YES and `7` for NO. This should be True, False instead. 

**To Reproduce**
Call `question_dialog` on the window object. 
```
choice = self.main_window.question_dialog(self.formal_name, 'Do you want to delete the timezone?')
print(choice) # Would print 6 or 7
```

**Expected behavior**
Return `True` or `False` instead. 

**Environment:**
 - Operating System: Windows 10
 - Python version: Python 3.7
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: 0.2.15
   - .toga-core : 0.3.0.dev25
   - toga-winforms : 0.3.0.dev25

**Comment by saroad2** [comment]
Fixed in #1129
