### ISSUE TITLE
DeprecationWarning on GTK backend

### ISSUE THREAD

**Issue by Ksengine** [beeware/toga#1147]
simple issue
this is the console log
```python
gtk/toga_gtk/app.py:40:DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.native.set_wmclass(app.interface.name, app.interface.name)
```

**Comment by freakboy3742** [comment]
Thanks for the report. 

Can I request that when opening tickets, you please provide full descriptive titles, and detailed reports in full sentences. We provide templates for bug reports and enhancements, deleting all that template content to provide partial sentences and half-explanations makes more work for the rest of us.

**Comment by Ksengine** [comment]
ok

**Comment by leggewie** [comment]
This issue is being tracked in #1167, I suggest to close this ticket

**Comment by freakboy3742** [comment]
Closing as a duplicate.
