### ISSUE TITLE
rework web backend

### ISSUE THREAD

**Issue by Ksengine** [beeware/toga#1148]
I saw that toga has few web backends.
We need to recreate it with following major features.
- works with any WSGI server
- works with any WSGI framework
**maybe +ASGI**
we can use [DicksonUI](https://github.com/Ksengine/DicksonUI/)
it  uses websockets or ajax to communicate between browser and python.

I had recently updated my websocket server library (https://github.com/Ksengine/WSocket/)
**note; It needs simple patches when adding new server.**

these both libraries need development.
can anyone contibute?.

**Comment by freakboy3742** [comment]
Closing this ticket on the basis that it isn't inherently actionable.

The layout that is currently in master *does* work with any WSGI server; this is what the toga-web backend provides. However, there will *always* be framework-specific pieces to provide framework-specific integrations, such as integration with URL resolvers/routing. The toga-django and toga-flask backends (as well as the toga-tornado, and other nursery backends) provide those framework bindings, using toga-web to provide the common functionality.

We're unlikely to adopt a GUI abstraction library. Toga *is* a GUI abstraction library; using an abstraction library to wrap another abstraction library doesn't make any sense. Toga's implementation layer talks directly to the native API on each platform - that means Cocoa on macOS, GTK or Qt on Linux, Winforms on Windows... and HTML/JS/CSS on Web.

**Comment by Ksengine** [comment]
Actually DicksonUI is not a GUI library.
Its a bridge between JavaScript (web browser) and python.
It has a window object.
It converts
```python
window.open("https://www.google.com")
```
to 
```javascript
window.open("https://www.google.com");
```
and returns value ir proxy

**Comment by Ksengine** [comment]
Toga wraps WinForms, GTK, Cocoa ...
Then toga can wrap DicksonUI.

**Comment by Ksengine** [comment]
@freakboy3742 can you reopen this issue

**Comment by freakboy3742** [comment]
In short; no, I won't be re-opening this issue.

 * Winforms is the official API provided by Microsoft for GUI programming on Windows
 * Cocoa is the official API provided by Apple for GUI programming on macOS
 * GTK is the official API provided by the Gnome project for GUI programming on Linux with Gnome desktops
 * UIKit is the offical API provided by Apple for GUI programming on iOS
 * DicksonUI is your pet project.

One of these things is not like the others.

On top of that, from what I can make out, the approach that DicksonUI is taking to GUI programming for web is fundamentally different to the approach that the web backend of Toga has historically taken.

I've [spoken at many conferences](https://pyvideo.org/speaker/russell-keith-magee.html), and I've engaged in many discussions in BeeWare's discussion forums over multiple years about the possible approaches for writing web apps in Python. I have a very clear vision for what Toga will look like on the web, and server-side execution of Python connecting to the browser over websockets isn't part of that vision.

If you want to build a Toga-compliant backend that uses DicksonUI, go right ahead. Toga's interface is open source, and can (in theory) be implemented by anyone. However, I don't believe the approach that you're suggesting is viable, and as a result, I won't implicitly endorse it by providing space for it under the Toga/BeeWare umbrella.

**Comment by Ksengine** [comment]
with or without dicksonui, can we add a one backend for web. with
- support for any server
- support for any web framework

**Comment by freakboy3742** [comment]
No, we can't; and if you actually read my responses, and/or spend 30 seconds looking at the code for existing Flask and Django backends, you'd see why.
