### ISSUE TITLE
Windows doesnt work

### ISSUE THREAD

**Issue by razorTwo** [beeware/toga#115]
The install is working fine on windows.
The start of toga-demo tells No module named 'toga'

How can i patch this issue?

**Comment by tritium21** [comment]
Windows support is a placeholder, at the moment (meaning, there is no windows support in toga)

**Comment by zeerorg** [comment]
I think it works when compiled from source.

**Comment by tritium21** [comment]
I really do advise you to [read the windows readme](https://github.com/pybee/toga/blob/master/src/win32/README.rst).  Windows support is pre-alpha, incomplete, and from looking briefly at the code, entirely incompatible with the current version of toga core.

**Comment by freakboy3742** [comment]
It's not *completely* incompatible, as long as you're using the trunk version of toga-core and colosseum. However, only the Hello World and Fahrenheit to Celsius demos will work at this time. The Windows backend is definitely a work in progress.

**Comment by voltagex** [comment]
I think this issue should be closed - we can always add a project and individual issues to track Windows support.

**Comment by freakboy3742** [comment]
I think it's worth keeping this one for now - at least until toga-demo runs.

**Comment by pyeguy** [comment]
Just listened to the BeeWare Talk Python To Me podcast and got super excited to check out Toga. Unfortunately I'm a (happy) Windows 10 user ... I'd love to help but the reason I came to the project is because I don't know much (at all) about GUI programming or C#/C++. Any suggestions on how to contribute with limited skill?

**Comment by freakboy3742** [comment]
@pyeguy You don't need to know any C# or C++ to contribute - Toga is 100% Python code. And as long as you're willing to spend some time poking around Microsoft's documentation site, you can contribute at almost any experience level!

There are three areas where 
* Testing Briefcase. We've recently added an MSI installer backend for briefcase so you can package your Toga applications as Windows apps; this needs testing, and possibly some fixes - there's at least one bug (pybee/briefcase#53) that has been reported that requires some investigation.
* Porting Widgets. [Pythonnet](https://github.com/pythonnet/pythonnet), (and in particular, the ]Wordpad demo](https://github.com/pythonnet/pythonnet/blob/master/demo/wordpad.py)) give examples of how to use Python to access native Windows widgets. Toga is essentially a generic API wrapper around this native functionality. The Cocoa backend has seen the most development; if you provide a Windows API version of the widgets defined in Cocoa, you'll put Windows on the same footing as macOS and GTK.
* Documentation: This is one area where I'm woefully behind where I'd like to be. So, take the code that *is* there, and work up good tutorial, topic and reference documentation for how to use Toga in practice.

**Comment by pyeguy** [comment]
@freakboy3742 Thanks for pointing me in the right direction! I'll take a stab at a few of those.

**Comment by freakboy3742** [comment]
Closing this ticket; Windows support has improved significantly at this point.
