### ISSUE TITLE
WinForms webview - replace IE with EdgeHTML

### ISSUE THREAD

**Issue by Ksengine** [beeware/toga#1155]
Use EdgeHTML instead of IE.
Winforms default webbrowser control uses Internet Explorer.
Its old and buggy.
We can use EdgeHTML if Edge installed else use IE.
It adds a dll(around 140kb) to Toga

**Comment by freakboy3742** [comment]
This has been a topic of active discussion recently. If you would take a moment to engage with the community rather than opening dozens of barely minimal tickets and expecting us to come to you, we'd be happy to give you that context.

**Comment by Ksengine** [comment]
ok
