### ISSUE TITLE
Alternate GTK/Gnome mapping for Toga.Command/Group

### ISSUE THREAD

**Issue by Ksengine** [beeware/toga#1159]
# Toga needs an alternate GTK/Gnome mapping for Toga.Command/Group
It should be something like this
![A visual reference for some of the most common GNOME 3 design patterns.](https://developer.gnome.org/hig/stable/figures/patterns/patterns.svg)

**Comment by Ksengine** [comment]
# Application menus
Application menus are no longer recommended, and their contents will not be included in GNOME 3's top bar from GNOME 3.32. Primary and secondary menus should be used as alternatives.
**Then we cant use Application menus**

# Menu bars
> Menu bars increase the vertical footprint of an application’s user interface, introduce a large number of disclosure points, and function as a fixed set of inflexible options. For these reasons, header bars and header bar menus are generally recommended over menu bars, along with other design patterns for exposing controls on demand, such as selection mode, action bars, and popovers.
>
> At the same time, it can be appropriate for complex applications that already include a menu bar to retain it. Additionally, some platforms also incorporate space for a menu bar in their user environment, and a menu model can be desirable for cross-platform integration purposes.

**not recommended**

**Comment by Ksengine** [comment]
# Then we should use
## [Header bars](https://developer.gnome.org/hig/stable/header-bars.html.en)
![](https://developer.gnome.org/hig/stable/figures/patterns/header-bar.svg)
## [Primary menus](https://developer.gnome.org/hig/stable/primary-menus.html.en)
![](https://developer.gnome.org/hig/stable/figures/patterns/primary-menu.svg)
## [Secondary menus](https://developer.gnome.org/hig/stable/secondary-menus.html.en)
![](https://developer.gnome.org/hig/stable/figures/patterns/secondary-menu.svg)

**Comment by freakboy3742** [comment]
Once again - this is a lot of screenshots, but not a *detailed proposal*. A detailed proposal should be enough information that anyone else could take the contents of the discussion, and generate an implementation that meets that specification. 

You've made a proposal that only mentions toga.Command and toga.Group in the *subject*. It mentions that there should be a an alternate mapping... but doesn't address the only detail that matters - *what that mapping would be*.

If you want to do this in practical terms: What would Tutorial 2 look like if we follow your proposal?

**Comment by freakboy3742** [comment]
Closing as this feature proposal is incomplete, and doesn't appear to be going in a direction that is likely to be accepted.
