### ISSUE TITLE
Update Selection Widget

### ISSUE THREAD

**Issue by horphi0815** [beeware/toga#1169]
Hi,

is it possible, to enhance the Selection Widget, to change the dropdown items with new content?
https://toga.readthedocs.io/en/latest/reference/api/widgets/selection.html

Best regards,

Phil

**Comment by horphi0815** [comment]
ok i got it
...items = ['a'.'b'.'c']

**Comment by freakboy3742** [comment]
Closing on the basis that the feature already exists.
