### ISSUE TITLE
WebView in MacOS not accepting keyboard input

### ISSUE THREAD

**Issue by jrwdunham** [beeware/toga#1197]
**Describe the bug**

I am unable to type text in HTML input fields within a Toga WebView on Mac OS.

**To Reproduce**
1. Follow the tutorial at https://docs.beeware.org/en/latest/tutorial/tutorial-1.html until you are able to run `briefcase dev` successfully.
2. Modify the `startup` function so that its body is:
   ```main_box = toga.Box()
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = toga.WebView(style=Pack(flex=1))
        self.main_window.content.url = 'https://www.google.ca/'
        self.main_window.show()
   ```
3. Attempt to search for something in the Google search input.
4. When I try, I am unable to type characters. Nothing happens with my key presses. Note that specified command shortcuts do seem to work.

**Expected behavior**
I expect to be able to enter text into text boxes in a WebView in Toga.

**Environment:**
 - Operating System: Mac OS 10.15.6
 - Python version: 3.6.5
 - Software versions:
   - Briefcase: 0.3.0
   - Toga: 0.3.0.dev26

**Additional context**
I discovered that If I just comment out the `keyDown_` method in toga_cocoa [here](https://github.com/beeware/toga/blob/master/src/cocoa/toga_cocoa/widgets/webview.py#L23-L27) then I am able to enter text in a WebView.

**Comment by freakboy3742** [comment]
Thanks for the report! 

Based on your additional notes, I'm guessing the solution will be to propagate the keyDown message to the superclass - that way the "native" key handling will be executed in addition to the Toga-specific handling. If I'm right, adding:

    send_super(__class__, self, 'keyDown:', event)

to the end of the `keyDown:` message will fix the problem.
