### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1199]
I'm opening up the discussion about dropping the support of Python 3.5 in all of Beeware's repositories, especially Toga.

Dropping Python 3.5 support will open up a door for vast new tools that are out of reach right now in Toga such as:

* Format strings
* Dataclasses (introduced in Python 3.7 as a built-in library, but can be installed as a dependency in Python 3.6)
* Type hints
* etc.

We continued to support Python 3.5  until today for 2 main reasons:

1. The Python Software Foundation (PSF) still supported it. This is not the case since September 2020.
2. Some operating systems such as Ubuntu still use Python 3.5 as its default python version.

I would argue that since even the PSF dropped Python 3.5 support, we should do as well. We have much more to gain from dropping Python 3.5 support than from keeping it.

@freakboy3742 , @paulproteus , @obulat, @SamSchott, I would love to hear your thoughts on that matter.

**Comment by freakboy3742** [comment]
+1.

We've already moved away from Ubuntu 16.04 as a build platform, which was the major reason for retaining Python 3.5 support. At this point, I don't see any reason to continue supporting 3.5, and plenty of good reasons (most of which are spelled "format strings" :-) to move to a 3.6 minimum supported version.

**Comment by saroad2** [comment]
Great!

Waiting for the others to respond (maybe someone has a good reason why we should keep Python 3.5 support).

If no one would object by tomorrow, I'll start by dropping support of Python 3.5 on Travertino, Toga, and Briefcase.

**Comment by obulat** [comment]
I fully support dropping 3.5!

**Comment by SamSchott** [comment]
+1 as well

The main issue IMO could be app distribution. If people go the Briefcase or the PyInstaller route, they will of course ship their own Python runtime. The only issue could be toga apps distributed as Python packages, for instance via a platform's package manager. But this will be very niche for toga apps so it shouldn't hold us back.

**Comment by saroad2** [comment]
We've successfully dropped support for python 3.5 in all the requested repositories, therefore closing this PR.
