### ISSUE TITLE
Making a window with certain widgets smaller doesn't work on Ubuntu 18.04 and 20.04

### ISSUE THREAD

**Issue by rknuus** [beeware/toga#1205]
**Description**
When resizing a window of an application containing a `WebView` or a `MultilineTextInput` widget, making it bigger works, but making it smaller doesn't work. Neither horizontally nor vertically. Note that only a few widgets seem to prevent shrinking, e.g. the window of the [hello world tutorial application](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html) works fine.

**To Reproduce**
1. Set up an Ubuntu 18.04 or 20.04 development environment (e.g. using https://github.com/rknuus/toga-dependency-verification).
2. Start the [browser app of the tutorial](https://toga.readthedocs.io/en/latest/tutorial/tutorial-3.html).
3. Resize the window, particularly try to make it smaller.

**Expected behavior**
The window size changes in both directions.

**Environment:**
 - Operating System:
   - Ubuntu 18.04 with GTK+ version 3.22.30-1ubuntu4 of libgtk-3-0 and version 2.24-32-1ubuntu1 of libgtk2.0-0
   - Ubuntu 20.04 with GTK+ version 3.24-20-0ubuntu1 of libgtk-3-0 and version 2.24-32-4ubuntu4 of libgtk2.0-0
 - Python version: 3.6.9 on Ubuntu 18.04 resp. 3.8.5 on Ubuntu 20.04
 - Software versions:
   - Toga: 0.3.0.dev26

**Comment by MuhammadMouradG** [comment]
Hi, @rknuus, 

Thanks for your report. This behavior is intended, we decided to determine a minimum height and width (=`200px`) for the `webview` widget and (=`100px`) for `multilinetextinput` widget to add some control in our design and to avoid unexpected errors.

@freakboy3742, is there any other reason, could you please mention it?

**Comment by rknuus** [comment]
Perhaps my problem description was not accurate, my apologies.

I understand that certain widgets have some minimal space requirements. My issue is, that starting from the default size I can make the window size bigger, but I can never make it smaller again, even though the window is now bigger than it was originally, i.e. making it a bit smaller should not violate the minimal space requirements.

**Comment by freakboy3742** [comment]
Thanks for the report. I think I've seen this in the past, but wasn't able to narrow down a specific reproduction case. 

IIRC it's only an issue on Ubuntu; the underlying problem is that once the geometry is laid out for a window, that is enforcing a minimum size on the window; and the next time it tries to re-evaluate the layout geometry, that minimum size is being enforced on the new layout. This way, a window can continue to get bigger, but can never shrink. If the issue exists on webview and multiline text, that suggests the issue is the way those widgets are re-hinting their size.

**Comment by MuhammadMouradG** [comment]
Thanks @rknuus and @freakboy3742 for your clarification, I got the problem. I submitted the #1224 PR for solve this issue with some cleaning code.

**Comment by MuhammadMouradG** [comment]
This problem needs some work my #1224 PR will not solve it perfectly.
