### ISSUE TITLE
pip install --pre toga is broken on Windows

### ISSUE THREAD

**Issue by kragil** [beeware/toga#1208]
**Describe the bug**
pip install --pre toga is broken on Windows

**To Reproduce**
pip install --pre toga 

**Expected behavior**
Install toga

**Screenshots**

**Environment:**
 Windows
pip 21.0.1 from c:\users\kragi\venv\lib\site-packages\pip (python 3.9)

**Additional context**
Installing collected packages: pythonnet, toga-winforms, toga
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kragi\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kragi\\AppData\\Local\\Temp\\pip-install-550s9d_6\\pythonnet_3b7f5a17a974431aba52b4d1514b2555\\setup.py'"'"'; __file__='"'"'C:\\Users\\kragi\\AppData\\Local\\Temp\\pip-install-550s9d_6\\pythonnet_3b7f5a17a974431aba52b4d1514b2555\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kragi\AppData\Local\Temp\pip-record-ord_tyao\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kragi\venv\include\site\python3.9\pythonnet'
         cwd: C:\Users\kragi\AppData\Local\Temp\pip-install-550s9d_6\pythonnet_3b7f5a17a974431aba52b4d1514b2555\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\kragi\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kragi\\AppData\\Local\\Temp\\pip-install-550s9d_6\\pythonnet_3b7f5a17a974431aba52b4d1514b2555\\setup.py'"'"'; __file__='"'"'C:\\Users\\kragi\\AppData\\Local\\Temp\\pip-install-550s9d_6\\pythonnet_3b7f5a17a974431aba52b4d1514b2555\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kragi\AppData\Local\Temp\pip-record-ord_tyao\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kragi\venv\include\site\python3.9\pythonnet' Check the logs for full command output.

**Comment by freakboy3742** [comment]
This is a known issue, and it's outside our control. The issue is pythonnet, which is a dependency on Windows; they haven't released a version that is compatible with Python 3.9.

Unfortunately, the only option at this time is to downgrade your Python version on Windows.
