### ISSUE TITLE
Multi or switch windows feature?

### ISSUE THREAD

**Issue by mintminttea** [beeware/toga#1214]
Hi all, I am just a beginner in python. 
Just discovered this project and thinking it is so great to be able to have android support.
I have one question is toga are able to have multi windows/screen/box and then switching between them?
For example how can I able to make a login windows for user to enter their credential then switch to the main application windows when login success?
Thanks.

**Comment by freakboy3742** [comment]
This is absolutely possible. `toga.Window` is a Toga class describing windows; you create a toga.MainWindow as the main window of your app, which gives it some special properties (like a menu bar, and closing your app when the main window is closed), but you can create as many additional additional windows as you want - just create an instance, fill it with content, and call `your_window.show()`.

**Comment by mintminttea** [comment]
Hi
I can show a new windows with windows.show() in Microsoft windows platform but it did nothing in Android environment.
How can I replace or switching the current content inside MainWindow ?

**Comment by mintminttea** [comment]
Found out that from another topic that I can just update main_window.content with new box then yield.
It is just seems not supporting in windows platform.
Thanks.
