### ISSUE TITLE
Add discussion label

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1218]
Hi, again

I think adding a `discussion` label or something similar for topic like `API proposal` and similar topics will be helpful for find similar topics.

**Comment by freakboy3742** [comment]
Thanks for the suggestion! I actually have a slightly different variation on this suggestion - turning on the "Discussions" feature of Github. 

Github recently added "Discussions" as a forum to hold Q&A, help, and related conversations, while integrating them with tickets and PRs. I need to investigate the capabilities of this new feature, but I suspect it will be much better than using tickets for discussions in the way we are currently.

**Comment by MuhammadMouradG** [comment]
@freakboy3742 I think the feature is added now...
