### ISSUE TITLE
select_folder_dialog initial_directory not work in Windows

### ISSUE THREAD

**Issue by DoooReyn** [beeware/toga#1244]
**Describe the bug**
select_folder_dialog initial_directory not work in Windows.
![image](https://user-images.githubusercontent.com/9557233/113840211-09935700-97c3-11eb-9648-12676d7e929d.png)
![image](https://user-images.githubusercontent.com/9557233/113840326-24fe6200-97c3-11eb-9f10-2dc7d18ccbdb.png)

**Expected behavior**
initial_directory should be displayed in file browser dialog first.

**Screenshots**
![image](https://user-images.githubusercontent.com/9557233/113839379-36933a00-97c2-11eb-8e30-e9d35cc39ffc.png)

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.8.2
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev26
   - ...

**Comment by DoooReyn** [comment]
To fix this, `initial_directory` should be an **absolute path**.

Hope to make it easier.

**Comment by freakboy3742** [comment]
Fixed by #1528
