### ISSUE TITLE
Dialogs not working in Android

### ISSUE THREAD

**Issue by mat-l** [beeware/toga#1246]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/beeware/toga/blob/19e89a77f1bacddc09110fd5c240ea4ecbf85b2a/examples/dialogs/dialogs/app.py#L75
2. I build the Android app with 'briefcase create android' and 'briefcase build android' with Docker in the background.

**Expected behavior**
Using 'briefcase dev' I am able to run the application on my Linux laptop and the 'select_folder_dialog' or 'open_file_dialog' are working.
On Android the file or fodler picking function is not working

**Screenshots**
Instead of file picking it is only showing this:
![Screenshot_20210410_194200_de.mnethome.blockapp.blockapp.jpg](https://user-images.githubusercontent.com/5571947/114279810-c3dec480-9a36-11eb-90b0-f0598d5792e9.jpg)

Instead of the question it is only showing this:
![Screenshot_20210410_214116_de.mnethome.blockapp.blockapp.jpg](https://user-images.githubusercontent.com/5571947/114282675-91889380-9a45-11eb-9f36-52e54774f8d3.jpg)

**Environment:**
 - Operating System: Linux Fedora 33
 - Python version: 3.9.2
 - Software versions:
   - Briefcase: briefcase       0.3.5
   - Toga:
   - toga-core       0.3.0.dev26; toga-gtk        0.3.0.dev26; toml            0.10.2

**Additional context**

**Comment by freakboy3742** [comment]
Thanks for the report. File dialogs aren't currently implemented on mobile platforms (although #1158 exists as a potential fix for file dialogs on Android). 

However, we don't track "not implemented yet" features as bugs, as it doesn't help us manage the task of managing the list of features that need to be implemented.

**Comment by mat-l** [comment]
@freakboy3742 Thanks for your quick feedback.
Maybe the documentation should be adjusted, as this site https://toga.readthedocs.io/en/latest/reference/api/window.html
![grafik](https://user-images.githubusercontent.com/5571947/114295801-c7f6fa80-9aa7-11eb-9275-b58769e4a2e9.png)
communicates, that the window functions do work already on all platforms.
