### ISSUE TITLE
Background worker and notifications

### ISSUE THREAD

**Issue by cafehaine** [beeware/toga#1250]
**Is your feature request related to a problem? Please describe.**

I'm trying to build a self-hosted shopping list with network synchronization. I would like to start a daemon, and eventually show notifications on specific events (item bought by another user, …)

**Describe the solution you'd like**

A way to have a background runner (maybe with a shown systray icon?), as well as a way to show notifications.

An api like the following would be nice:
```python
import time

import toga

def runner_function():
    while True:
        time.sleep(10)
        print("Running in the background...")

def notification_open():
    print("Notification clicked!")

def main():
    toga.start_runner(runner=runner_function)
    toga.show_notification(title="Sample notification", body="Something happened!", on_click=notification_open)

if __name__ == "__main__":
    main()
```

**Describe alternatives you've considered**

None

**Additional context**

This issue might fit more in the briefcase project, but the systray icon is probably a toga feature

**Comment by freakboy3742** [comment]
Thanks for the suggestion. 

You're looking for `TogaApp.add_background_task`. There's an example of use in the `handlers` example in the Toga source tree.

There's also an [open feature request on Toga for systray apps](#97).

**Comment by cafehaine** [comment]
I guess I didn't look for it hard enough, my bad! Thanks for the tips!
