### ISSUE TITLE
Fix widget layout implementations for Django

### ISSUE THREAD

**Issue by aschn** [beeware/toga#126]
The toga_django widget implementations are not Bootstrap-ified and they should be. One way to see this issue is:

If you follow the instructions for toga tutorial 1, it shows a nice pretty native GUI. The input fields are aligned, and all elements span.

![image](https://cloud.githubusercontent.com/assets/3664000/24749204/0c11d088-1a77-11e7-801b-0a60dce7b096.png)

If you follow the instructions for briefcase tutorial 1 using django instead of iOS, the input fields are not aligned and don't span:

![image](https://cloud.githubusercontent.com/assets/3664000/24757402/ff8fbcae-1a93-11e7-8e3d-c4de47f5883e.png)

**Comment by freakboy3742** [comment]
The Django backend needs to be completely reworked, so keeping this ticket open isn't especially useful at this point.
