### ISSUE TITLE
Make app respond to Cmd-H, Cmd-Opt-H on macOS; add menu bar items

### ISSUE THREAD

**Issue by layday** [beeware/toga#1261]
Toga apps do not respond to Cmd-H and Cmd-Opt-H on macOS and there are no options to hide the app or hide other apps on the application menu.  These could be added to the `APP` command group in `toga-cocoa` so that they are always present for macOS apps, under a separate section.  I could look into what this might require although I've no experience with ObjC and friends.

**Comment by freakboy3742** [comment]
Completely agreed that this is desirable; the goal of a Toga app should be that the "hello world" demo should have all the menu items and behaviours you'd expect a native app to have. The "Hide"/"Hide others" menu items on the app menu are definitely items that we should have.

From a cursory investigation, it looks like we just need to hook into the [`hide:`](https://developer.apple.com/documentation/appkit/nsapplication/1428733-hide?language=objc) and [`unhide:`](https://developer.apple.com/documentation/appkit/nsapplication/1428761-unhide?language=objc) message on `NSApplication`, adding a menu item in the Cocoa backend. If you'd like any pointers on how to proceed, ask here, or join us on [Discord](https://beeware.org/bee/chat)
