### ISSUE TITLE
[toga-cocoa] Some enums have incorrect values on Apple Silicon Macs

### ISSUE THREAD

**Issue by SamSchott** [beeware/toga#1282]
**Describe the bug**
The enum values for `NSTextAlignment` and `NSImageResizingMode` are different in macOS for Intel and Apple Silicon Macs. This is documented in the porting guide at:

https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code

and also apparent in the headers, for example in `NSText.h`:

```objc
typedef NS_ENUM(NSInteger, NSTextAlignment) {
    NSTextAlignmentLeft      = 0,    // Visually left aligned
#if TARGET_ABI_USES_IOS_VALUES
    NSTextAlignmentCenter    = 1,    // Visually centered
    NSTextAlignmentRight     = 2,    // Visually right aligned
#else /* !TARGET_ABI_USES_IOS_VALUES */
    NSTextAlignmentRight     = 1,    // Visually right aligned
    NSTextAlignmentCenter    = 2,    // Visually centered
#endif
    NSTextAlignmentJustified = 3,    // Fully-justified. The last line in a paragraph is natural-aligned.
    NSTextAlignmentNatural   = 4     // Indicates the default alignment for script
} API_AVAILABLE(macos(10.0), ios(6.0), watchos(2.0), tvos(9.0));
```

This results in center aligned-text in toga currently appearing as right-aligned text on M1 machines and vice-versa.

**Environment:**
 - Operating System: macOS 11
 - Platform: Apple Silicon

**Comment by freakboy3742** [comment]
but.... WHYYYYYYYY 🤦 

Thanks for the heads up. `platform.machine()` will tell us what we need to know to differentiate ('arm64' vs 'x86_64').

**Comment by SamSchott** [comment]
Thanks for the quick fix! Yeah, it's a pointless change. Maybe some philosophical stance of the iOS team that center should be between left and right?
