### ISSUE TITLE
Image() path string casting

### ISSUE THREAD

**Issue by CDWimmer** [beeware/toga#1294]
**Is your feature request related to a problem? Please describe.**
The Image class (from images.py) does not expect any type for parameter `path`, this means that pathlib paths, used elsewhere through Beeware does not nicely pass without wrapping said path in a `str(pathlib.Path)`, which sucks and is too many brackets. The rest of the Image class goes on assuming that `path` is a string, e.g. calling `path.startswith('http://')`, a string method.

**Describe the solution you'd like**
Simply update Image's __init__ line to be `def __init__(self, path: str):` to add automatic casting for os.path objects and pathlib objects alike. You'd really expect a parameter named `path` to take path objects. 

**Describe alternatives you've considered**
The alternative would be a bigger rework to Image to check the type of `path` and to convert it accordingly but that's silly when the above does the same thing. Alternative 2 is force users to cast with str() every time but I can't imagine why anyone would want that.

**Comment by freakboy3742** [comment]
We're trying to converge on the use of `Path` objects; Path objects should definitely be acceptable input without any additional str() casting.

**Comment by mhsmith** [comment]
This was fixed by #1548.
