### ISSUE TITLE
implementations should use interface values (vs raw)

### ISSUE THREAD

**Issue by aerickson** [beeware/toga#1315]
**Describe the bug**
The code below explodes on iOS and Android (Mac/cocoa must do some casting?).

It works if the integers are cast via str().

```
        self.interval_input = toga.TextInput(
            placeholder=2, readonly=True, initial=2
        )
```

**To Reproduce**
1. Create an app with the code above
2. `briefcase run iOS` or `briefcase run android`
3. App will crash

**Expected behavior**
The code above should work.

**Screenshots**
n/a

**Environment:**
 - Operating System: Mac 11.4
 - Python version: 3.8
 - Software versions:
briefcase          0.3.5
toga               0.3.0.dev27
toga-cocoa         0.3.0.dev27
toga-core          0.3.0.dev27

**Comment by aerickson** [comment]
somewhat related: Selection boxes will explode on iOS if items=a_dict.values() vs a list(). Using items=a_dict.values() works fine on Android and Cocoa.

`toga_iOS/widgets/selection.py", line 19, in pickerView_titleForRow_forComponent_`

**Comment by freakboy3742** [comment]
This will be resolved (and tested) by the textinput widget audit in #1944.
