### ISSUE TITLE
Load images from ByteArray

### ISSUE THREAD

**Issue by Insectslayer** [beeware/toga#1348]
I'm trying to send a png image via socket as a ByteArray and then display it in the ImageView. However, it's only possible to load already saved image via path. And because I'm streaming the images (at around 10 FPS), I don't think I have time to save the image. Regardless, this seems like a pretty inconvenient solution, saving the image only to load it right away.

I want to create a new Image using ByteArray as input.

**Comment by bruno-rino** [comment]
I've made an attempt to implement this: https://github.com/beeware/toga/pull/1588

It's marked as Draft. There's still deprecation warnings and docs to update, but first I'd like feedback on whether overloading the positional argument for the Image constructor is well received. Its name, `path`, makes no sense anymore. I changed it to `value`.

**Comment by freakboy3742** [comment]
Closing as this was implemented in #1588.
