### ISSUE TITLE
pip install toga ERROR on MS Windows 10 using python 3.10

### ISSUE THREAD

**Issue by jvickroy** [beeware/toga#1359]
**Just trying toga for the first time and this is how the installation went:**

C:\Users\jgv\Documents\My Projects\AstroPixMetaDB [2021-10-29]\experiments>**pip install toga**
Collecting toga
  Downloading toga-0.2.15-py3-none-any.whl (4.3 kB)
Collecting toga-winforms
  Downloading toga_winforms-0.2.15-py3-none-any.whl (13 kB)
Requirement already satisfied: toga-core>=0.2.15 in c:\users\jgv\appdata\local\programs\python\python310\lib\site-packages (from toga-winforms->toga) (0.3.0.dev29)
Collecting pythonnet
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: travertino>=0.1.3 in c:\users\jgv\appdata\local\programs\python\python310\lib\site-packages (from toga-core>=0.2.15->toga-winforms->toga) (0.1.3)
Requirement already satisfied: pycparser in c:\users\jgv\appdata\local\programs\python\python310\lib\site-packages (from pythonnet->toga-winforms->toga) (2.21)
Using legacy 'setup.py install' for pythonnet, since package 'wheel' is not installed.
Installing collected packages: pythonnet, toga-winforms, toga
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jgv\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jgv\\AppData\\Local\\Temp\\pip-install-434uqp88\\pythonnet_5af821df9ae4432aa355717cd41a8f56\\setup.py'"'"'; __file__='"'"'C:\\Users\\jgv\\AppData\\Local\\Temp\\pip-install-434uqp88\\pythonnet_5af821df9ae4432aa355717cd41a8f56\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jgv\AppData\Local\Temp\pip-record-vmsdf1xr\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\jgv\AppData\Local\Programs\Python\Python310\Include\pythonnet'
         cwd: C:\Users\jgv\AppData\Local\Temp\pip-install-434uqp88\pythonnet_5af821df9ae4432aa355717cd41a8f56\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\jgv\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jgv\\AppData\\Local\\Temp\\pip-install-434uqp88\\pythonnet_5af821df9ae4432aa355717cd41a8f56\\setup.py'"'"'; __file__='"'"'C:\\Users\\jgv\\AppData\\Local\\Temp\\pip-install-434uqp88\\pythonnet_5af821df9ae4432aa355717cd41a8f56\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jgv\AppData\Local\Temp\pip-record-vmsdf1xr\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\jgv\AppData\Local\Programs\Python\Python310\Include\pythonnet' Check the logs for full command output.
WARNING: You are using pip version 21.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\jgv\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\jgv\Documents\My Projects\AstroPixMetaDB [2021-10-29]\experiments>

**Could someone explain what the issue is and how to resolve it?  Thanks.**

**Comment by freakboy3742** [comment]
There are two things going on here:

Firstly, you've installed Toga 0.2, rather than the development 0.3 releases. The 0.2 release never had good support for Windows. To install the 0.3 development version, you need to specify --pre when you pip install.

Secondly, even when you do install the development version, we do t currently support Python 3.10 on Windows. This is because one of our dependencies (Python.net) doesn't support anything after Python 3.8. 

Unfortunately, there isn't much we can do about this. The only real option is to downgrade your Python version.

**Comment by jvickroy** [comment]
Thanks for the explanation.  Could it be added to the **readme.rst**?

**Comment by freakboy3742** [comment]
It can indeed! I've just added this in #1361.
