### ISSUE TITLE
toga/examples w/o end lines:  if __name__ == '__main__': [...]  DO NOT run from macOS 10.13.6 terminal.app

### ISSUE THREAD

**Issue by clemsam** [beeware/toga#1369]
**Describe the bug**
toga/examples w/o end lines:  `if __name__ == '__main__':` [...] DO NOT run launched from macOS' terminal.app.

**To Reproduce**
1. toga example box/box/app.py called via "python3 path/to/box/app.py" simply does NOT start (= open app window).
2. toga example activityindicator/activityindicator/app.py WITH lines: if `__name__ == '__main__': [...]  DOES open app window.

**Expected behavior**
Ideally EVERY example from toga/examples should display its app window (otherwise quite irritating...).

**Environment:**
 - Operating System: macOS 10.13.6
 - Python version: python3.7

**Additional context**
Adding the problematic lines to end of non-cooperative app.py's code DOES solve the issue (for ME)...

**Comment by freakboy3742** [comment]
Thanks for the report. Looks like the `if __name__ == '__main__':` has been missed from the box example. The example starts if you use `python -m box`; but it doesn't hurt to have the other entry point there.

We should audit the other examples to make sure there aren't any others with missing main entry points.

**Comment by freakboy3742** [comment]
@clemsam Is there a reason you closed this issue? It's still a current problem...

**Comment by clemsam** [comment]
Hi, I am too inexperienced (a little shamefully said) with even starting proceedings (like placing "- m" in front of "box") that I felt that my "problem" was really answered by your mentioning how to call (start) the examples ...

**Comment by freakboy3742** [comment]
@clemsam There's absolutely no shame in lacking experience! Plus, the examples *can* run as normal Python scripts with a minor change, so it's worth making that change.
