### ISSUE TITLE
Drop Python 3.6 Support

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1376]
**Description**
Python 3.6 is reaching its **end-of-life** on *December 23, 2021* (2 weeks from now).
Therefore, I think we should consider dropping support for that version.

**Why?**
If the PSF drop support, we should too :)
Also, it will allow us to use new libraries and abilities that are available only for Python 3.7+

**Comment by freakboy3742** [comment]
Agreed that we should be under no obligation to support a Python version that Python itself doesn't support any more. The one complication is that Python 3.6 is the version of Python on Ubuntu 18.04, which doesn't EOL until April 2028 - but I don't feel especially obligated to provide free support for Python 3.6 for another 6 years.

This also simplifies our release process, as we don't need to backport 3.6 templates and support libraries. To that end: mental note that similar PRs will be needed in:

* briefcase
* briefcase-template
* Python-Apple-support
* Python-android-support
* Python-linux-support
* briefcase-iOS-Xcode-template
* briefcase-Android-gradle-template
* briefcase-macOS-app-template
* briefcase-macOS-Xcode-template
* briefcase-linux-appimage-template
* briefcase-windows-msi-template
* rubicon-java
* rubicon-objc
