### ISSUE TITLE
DatePicker and TimePicker for Android

### ISSUE THREAD

**Issue by otaj** [beeware/toga#1407]
**Is your feature request related to a problem? Please describe.**
Currently, DatePicker and TimePicker widgets are missing from Android support. I am diving into the organization of Toga code and I am thinking it could be a good first issue for me to start working on - however, it seems the standard implementation of these widgets within Android is not as widgets, but dialogs. Is it something you would be interested in, maybe with an additional Button to open up the dialog?

**Describe the solution you'd like**
I would like to have Date and Time Pickers within Toga for Android - and I am willing to work on them myself. But first, I'd like to discuss whether it makes sense to have them as Buttons that would open up appropriate dialogs.

So, do you think it makes sense to do it this way? Can I get a green light? Thanks :)

**Comment by otaj** [comment]
So, I started taking a look at it now and it seems it is absolutely not necessary to have them within dialogs - you can just use them as widgets, though having them as dialogs would be nicer. I managed to create a simple implementation of DatePicker in Android, I will probably post a PR with the changes tomorrow

**Comment by freakboy3742** [comment]
@otaj I don't have any strong opinion over how this should be implemented, other than to say "whatever is platform appropriate". I know from the iOS context that dates/times aren't a "dialog" - but when you click on them, a sheet opens that lets you select a date. I don't know Android well enough to comment on what is "platform native" - but examples drawn from HIG-compliant Android Apps are the best guide here.

**Comment by otaj** [comment]
So, the picker looks "as expected". However, there are small issues - I cannot seem to grow it over the whole width of the screen, probably because it is meant to be used within a dialog

![Screenshot_1642068487](https://user-images.githubusercontent.com/6065855/149310191-2f718314-3d2c-4238-901d-18546e6d5c8a.png)

**Comment by freakboy3742** [comment]
This was implemented in #1408.
