### ISSUE TITLE
Delay or after function

### ISSUE THREAD

**Issue by GiorgiMatcharashvili** [beeware/toga#1415]
**Is your feature request related to a problem? Please describe.**
I have been trying to make flashing text with Toga. I can make it using button, when you click the button text will disappear and when you click it again text will appear again. It looks like this:

    def startup(self):
        self.text_appearance = True

        def flash(widget):
            if self.text_appearance:
                main_box.remove(text)
                self.text_appearance = False
            else:
                main_box.add(text)
                self.text_appearance = True

        text = toga.Label("This text will disappear if you click the button")
        button = toga.Button("click me", on_press=flash)

        # Add components to the main box
        main_box = toga.Box(style=Pack(direction=COLUMN))
        main_box.add(button)
        main_box.add(text)

        # Show main window
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

But I am unable to find the function which will waits, for example, 2 seconds and then runs the flash function. Like the time.sleep(), Or to be more clear and get help from other GUI framework, like the after function from Tkinter.
The solution of my problem in Tkinter: https://stackoverflow.com/questions/27533244/how-to-make-a-flashing-text-box-in-tkinter

**Describe the solution you'd like**
To solve this problem, I would like to be able to do flashing without button, for example, something like this:

    def startup(self):
        self.text_appearance = True

        def flash(widget):
            if self.text_appearance:
                main_box.remove(text)
                self.text_appearance = False
            else:
                main_box.add(text)
                self.text_appearance = True
            self.main_window.after(2000, flash)

        text = toga.Label("This text is flashing")

        # Add components to the main box
        main_box = toga.Box(style=Pack(direction=COLUMN))
        main_box.add(text)

        # Show main window
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

        flash()

**Additional context**
Please inform me if there is a solution already. if not, please add this feature in Toga. I planed to do many things using this feature and I would love to see it.

**Comment by t-arn** [comment]
You could try this: App.add_background_task()

**Comment by freakboy3742** [comment]
Thanks for the suggestion! As @t-arn noted, you can do this today with `App.add_background_task()`:
```
class MyApp:
    def some_method(self):
        ...
        self.add_background_task(run_later)
        self.add_background_task(run_later_async)

    def run_later(self):
        yield 5
        self.main_window.title = 'It is later'

    async def run_later_async(self):
        await asyncio.sleep(10)
        self.main_window.title = "It is even later"

```

That said - "run this code in N seconds" is a common enough design pattern that it would be worth adding a utility method `run_later(timeout, method, *args, **kwargs)` that wraps a call to `add_background_task()` that implements what I've described above.

**Comment by VahilaK** [comment]
Can I work on this?

**Comment by freakboy3742** [comment]
@VahilaK Absolutely! 

One consideration to keep in mind is that we will want to have a single "run_later" method that can handle any function, generator or coroutine (i.e., we need to be able to handle a simple function, a function that has a `yield N` in it, and a function that is declared `async def`). You may want to look at `handlers.py` in `toga.core` to see how we handle event callbacks to achieve the same thing.

You'll also need to add a demonstration case; there is a `handlers` demo in the example folder that will need to be extended to include an example of your new method being used in different ways.

**Comment by VahilaK** [comment]
@freakboy3742 I added a function 'run_later' in app.py from toga.core. I updated the handlers demo but when running the handlers example, I get an error "HandlerApp object has no attribute run_later". How can I use the 'run_later' function in handlers example? If that's not possible how can I use the 'run_later' function as part of an example to test out it's functionality.

P.S: This seems like a simple workflow but I am  not very experienced with python and I am not able to figure it out. I apologize for the inconvenience.

**Comment by freakboy3742** [comment]
@VahilaK If you're getting an error that the method that you've added isn't being found, it's probably because you're not using your local (modified) version of Toga to run the app. See [this guide](https://toga.readthedocs.io/en/latest/how-to/contribute.html) for how to set up your environment for testing.

**Comment by mhsmith** [comment]
Since Toga 0.4, the event loop is available as a [property on the App object](https://toga.readthedocs.io/en/stable/reference/api/app.html#toga.App.loop). So this can be done using `self.loop.call_later` or `self.loop.call_at`, where `self` is the `App`.
