### ISSUE TITLE
'Your first Toga app' throws an error on Windows

### ISSUE THREAD

**Issue by VahilaK** [beeware/toga#1418]
**Describe the bug**
When running the helloworld file, below error is thrown.
Traceback (most recent call last):
  File "C:\Users\bphc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bphc\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bphc\Desktop\openSource\toga\helloWorld.py", line 2, in <module>
    from tutorial import __version__
ModuleNotFoundError: No module named 'tutorial'

**To Reproduce**
1. Go to 'https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html#your-first-toga-app'
2. Create 'helloworld.py' file and run it.
3. See error

**Expected behavior**
A desktop app with a single button

**Screenshots**

**Environment:**
 - Operating System:  Windows
 - Python version: 3.10.2
 - Software versions:
   - Briefcase:
   - Toga: 

**Additional context**
I followed the steps for installing, creating venv and running the file as mentioned in the docs.

**Comment by VahilaK** [comment]
Removing `from tutorial import __version__` (second line) and the version parameter passed to toga.app(line 26), resolved the issue and a desktop app with a single button is seen as expected.

**Comment by freakboy3742** [comment]
From what I can make out, you haven't followed the tutorial correctly - you've got a "helloworld.py" in a `toga` directory, but you're invoking a module called `tutorial`. 

If you want additional assistance with the tutorial, I'd suggest heading to Discord, or opening a discussion thread.
