### ISSUE TITLE
Replacing window content fails

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1439]
Calling `window.content = new_content` should replace the top level content of a window. However, this behavior isn't observed on some platforms:

* macOS works as expected.
* Android works as expected.
* Windows behaves as a no-op.
* Linux removes the old content, but only displays the new content if you call main_window.show()
* iOS displays a black screen.

**To Reproduce**

Run the following app. Clicking the start button should replace the button with the text label.
```
class HelloWorld(toga.App):
    def startup(self):
        box = toga.Box(style=Pack(direction=COLUMN))
        start_button = toga.Button(
            'Start',
            on_press=self.replace_content,
            style=Pack(padding=5)
        )

        box.add(start_button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = box
        self.main_window.show()

    def replace_content(self, widget, **kwargs):
        box = toga.Box(style=Pack(direction=COLUMN))
        label = toga.Label(
            'New Content',
            style=Pack(padding=(5, 5))
        )
        box.add(label)
        self.main_window.content = box
        # This shouldn't be needed, but is on Linux.
        # self.main_window.show()

def main():
    return HelloWorld()
```

**Expected behavior**

**Screenshots**

**Environment:**
 - Operating System: Windows, Linux, iOS
 - Python version: All
 - Software versions:
   - Briefcase: 0.3.6
   - Toga: f63f333c47ad29a7c455ddb26f89ed42416e9d99

**Additional context**

#1385 partially fixed this for GTK, replacing main window content, but requiring the call to `show()` to make the change take effect.

**Comment by saroad2** [comment]
I believe this issue was fix for Windows in #1572.

**Comment by freakboy3742** [comment]
Agreed; however, the issue on Linux requiring a show() still exists.

**Comment by RPELLED** [comment]
I attempted to solve this here - https://github.com/beeware/toga/pull/1753, let me know what you think

**Comment by freakboy3742** [comment]
#1749 contains a fix for iOS.
