### ISSUE TITLE
"Your first Toga app" (helloworld) does not work as shown in the docs

### ISSUE THREAD

**Issue by bjkeefe** [beeware/toga#1453]
I copy-pasted the code [found here](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html).  When I ran it, I got this error message:

```
$ python -m helloworld
Traceback (most recent call last):
  File "C:\Users\brendan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\brendan\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\bjk\tmp\beeware-toga\helloworld.py", line 2, in <module>
    from tutorial import __version__
ModuleNotFoundError: No module named 'tutorial'
```

If I comment out the line `from tutorial import __version__` and delete the kwarg `version=__version__` in the call to `toga.App`, the module does run; i.e., the GUI window pops up and seems to work.  However, during the run, I get a warning:

```
$ python -m helloworld
C:\Users\brendan\AppData\Local\Programs\Python\Python39\lib\site-packages\clr_loader\wrappers.py:20: DeprecationWarning:
 builtin type GC Offset Base has no __module__ attribute
  return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
```

Maybe it's just out-of-date documentation?

P.S. FWIW, a straight copy-paste of the second tutorial, "[A slightly less toy example](https://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html)" works as is, although it does produce the same DeprecationWarning.

P.P.S.  Ditto the fourth tutorial, "[Let’s build a browser!](https://toga.readthedocs.io/en/latest/tutorial/tutorial-3.html)"

**Comment by freakboy3742** [comment]
Thanks for the report - it isn't so much out of date as an update made in one location that didn't consider the other places the code was being used. I've corrected this in #1454.

The warning is nothing to be concerned about - it's an issue with an upstream library (python.net), but not one that causes a problem in practice. I have sort of assumed it was so glaring it must have been reported, but looking at python.net's issue tracker, I can't see any reference to it. I'll report it so they're aware.

**Comment by bjkeefe** [comment]
Thanks for your rapid response and quick attention, Russell.  The [new version](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html) of `helloworld` runs as expected.

I see that you [reported](https://github.com/pythonnet/pythonnet/issues/1752) the DeprecationWarning to the pythonnet people, that they claim to have fixed the issue, and that you confirmed.  Not that it's any big deal, but just so you know, I am still seeing the warning, even after re-running 

```
$ python -m pip install --pre --upgrade toga
```

Is this because it will take some time for your changes (or theirs, I guess) to propagate to wherever pip is checking for new versions?

P.S. Congratulations on the new gig!  (Saw it on Twitter.)

**Comment by freakboy3742** [comment]
The fix for the Python.NET issue is in their master branch, but hasn't been released yet. The alpha2 release still has the bug. I don't know when they're planning  to make a release; but in the meantime, the DeprecationWarning is nothing more than an inconvenience.

**Comment by bjkeefe** [comment]
Agreed.  And thanks for the additional information.
