### ISSUE TITLE
NumberInput displays irrational numbers when the step is set by a number less than 1

### ISSUE THREAD

**Issue by karthurdnt** [beeware/toga#1455]
**Describe the bug**
The NumberInput widget will display irrational numbers when the increment step is set by a rational number less than 1 (as 0.9, 0.8, 0.7, etc).

**To Reproduce**
1. set ` total = toga.NumberInput(min_value=0, max_value=10,step=0.01)` 
2. run  `briefcase dev`
 --> The number input will then get a bunch of zeros (see screenshot below)
3. try to increment one step:
--> It will increment by an irrational number close to actual step (see screenshot below)
--> and  the terminal will display:
    ```
    self.interface._value = Decimal(value).quantize(self.interface.step)
    decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
    ```

**Expected behavior**
To increment by just 0.01 and to display only two decimal numbers after the decimal separator.

**Screenshots**
When I run it:
![image](https://user-images.githubusercontent.com/102690673/161900405-1aa1b21e-494d-4eb7-8912-ea2e276ef715.png)
When I try to increment one step:
![image](https://user-images.githubusercontent.com/102690673/161900517-6061b3a0-ae9f-42ef-afaf-61d8d90e371b.png)

**Environment:**
 - Operating System: Ubuntu 21.10
 - Python version: 3.7
 - Software versions:
   - Briefcase: 0.3.6
   - toga: 0.2.15 
    - toga-core: 0.3.0.dev32          
    - toga-gtk: 0.3.0.dev32

**Additional context**
 It curiously still worked with increments of 0.5, but all the other steps of less than 1 reproduced this bug.

**Comment by nickzoic** [comment]
OK so I added in some None checks in https://github.com/nickzoic/beeware-toga/tree/nickzoic-1455-numberinput and that fixes the test failures.

I was a bit worried by `self._impl.set_value(value)` ... it should probably really be `self._impl.set_value(self._value)` ... but the GTK implementation at least ignores this anyway and sets the widget value correctly.
