### ISSUE TITLE
Toga.Selection causing crash

### ISSUE THREAD

**Issue by sbhobbes** [beeware/toga#1471]
**Describe the bug**
toga.Selection causes terminal crash when items property is populated with list of integers.  Exception is not handled, no traceback log on Python either. 

**To Reproduce**
1. Create a list of integers.
2. Create a toga.Selection object and set the items property to the list of integers. 
3. Put the selection object into a box and display on the screen. 
4. App will crash without descriptive exception messaging. 

**Expected behavior**
Data type error message. Windows instead throws a CLI memory corruption error with no traceability back to the widget. 

**Environment:**
 - Operating System: Windows 10, Android 12 (also on virtual android emulators for pixel)
 - Python version: 3.9
 - Software versions:
   - Briefcase:
   - Toga:
   - ...

**Additional context**

**Comment by freakboy3742** [comment]
Thanks for the report. I suspect this will be closely related to #1467; I suspect the underlying problem will be something that is missing a call to convert the integer into a string.
