### ISSUE TITLE
Window without a on_close handler cannot be closed through the GUI

### ISSUE THREAD

**Issue by samschott** [beeware/toga#1482]
**Describe the bug**
When creating a new window without setting a `on_close` handler, the window cannot be closed through the GUI in Cocoa.

This seems to be because `toga_cocoa.Window.cocoa_windowShouldClose()` always returns `False` and this return value in turn is used as the window delegate's `windowShouldClose:` return value:

https://github.com/beeware/toga/blob/400b6935c4689bedb134324b38eb1286af5b5ec6/src/cocoa/toga_cocoa/window.py#L290-L293

When a `on_close` handler is set, the implementation layer wraps this handler to close the window directly afterwards, bypassing `NSWindowDelegate  windowShouldClose:`.

**To Reproduce**
```Python
import toga


class WindowDemoApp(toga.App):

    def startup(self):

        # Set up main window
        self.main_window = toga.MainWindow(title=self.name)
        self.main_window.content = toga.Box()

        # Set up secondary window
        self.secondary_window = toga.Window(title="Secondary Window")
        self.secondary_window.content = toga.Box()
        self.app.windows += self.secondary_window

        # Show the windows
        self.main_window.show()
        self.secondary_window.show()


def main():
    return WindowDemoApp('Window Demo', 'org.beeware.widgets.window')


if __name__ == '__main__':
    app = main()
    app.main_loop()
```

**Expected behavior**
Windows with `closeable=True` should be closable by the user.

**Environment:**
 - Operating System: macOS
 - Python version: 3.10
 - Software versions:
   - Toga: 0.3.0.dev33

**Comment by samschott** [comment]
Another nit about `on_close`: it is currently not documented in the doc-string.

**Comment by freakboy3742** [comment]
Oh bother - I caught the variant of this bug that related to the main window, but didn't check secondary windows. Thanks for the report.
