### ISSUE TITLE
Button, with focus, on_press handler does not respond to Enter/Return keypress

### ISSUE THREAD

**Issue by Jim-Salmons** [beeware/toga#1495]
**Describe the bug**
When a Button widget has focus as shown by the color/bold halo, pressing the Enter/Return key does not trigger the `on_press` event handler the way a mouse click does.

**To Reproduce**
1. Do the `hello_world` tutorial example to point of having the 'Your name' text input and 'Say Hello!' button. 
2. Fill in a name and press Tab to move focus to the Button.
3. Press the Enter/Return key and nothing happens.
4. Click the Button with the mouse cursor and the `say_hello` handler triggers.

**Expected behavior**
When a Button has focus and the Enter/Return key is pressed, the `on_press` handler should respond the same as if the Button was clicked by the mouse cursor.

**Environment:**
 - Operating System: M1 macOS Monterey 12.4
 - Python version: 3.10.4
 - Software versions:
   - Briefcase: 0.3.7
   - Toga: 0.3.0.dev32

**Additional context**
My conda environment is using the `osx-arm64` config for M1 use, however I have noted the same behavior when running an `osx-64` env.

**Comment by wxllow** [comment]
i have this issue too, but the space button works to press the button

**Comment by Jim-Salmons** [comment]
> i have this issue too, but the space button works to press the button

Good catch @wxllow :-) I'll check this out as a helpful workaround for the moment.

I have a `toga` fork here: https://github.com/Jim-Salmons/toga - where I have been able to support creating a Button with the macOS-specific `key_equivalent` attribute and set/change it once created. But I am struggling to support the recognition of focus-change by tab-traversal. The event handling of focus traversal would seem to be critical to provide the macOS mechanism of [becomeFirstResponder](https://developer.apple.com/documentation/appkit/nsresponder/1526750-becomefirstresponder) and [resignFirstResponder](https://developer.apple.com/documentation/appkit/nsresponder/1532115-resignfirstresponder) needed to have the `Return/Enter` key ('\r') trigger the focus-highlighted Button.

I honestly am way out of my depth with regard to macOS widget coding to make much headway on this but will keep chipping away. If anyone with great macOS dev skills steps up, I will gladly help and test wherever I can.

**Comment by Jim-Salmons** [comment]
A-ha! My bad. 🤦‍♂️ I believe the current behavior is consistent with Apple User Interface Guidelines for focus traversal and interaction behavior. (See [here](https://developer.apple.com/design/human-interface-guidelines/inputs/focus-and-selection) for Apple UX dox overview and links to other detailed resources.)

Having spent decades on Windows, I recently switched to an M1 iMac for the macOS accessibility features due to a severe spinal cord injury that significantly reduced my dexterity and mobility. On Windows, "pressing" a focused button is done via the Enter/Return key. On macOS, the Enter/Return key will _always_ press the designated default button, if set, regardless of widget focus.

To "press" the focused button under macOS, as @wxllow pointed out, the focused button can be "pressed" by the spacebar key! 🥳 IDNKT. Although I haven't checked it, this implies that Toga Buttons should appropriately behave on iPadOS as well as macOS via physical and onscreen keyboard interaction.

Although Apple recommends against programmatic focus-changing, it is possible and can be done intentionally. As in the case for certain of the metadata discovery and curation activities for my Digital Humanities limited-purpose apps, there is a primary workflow that can be intuited based on "if this, then next" actions. In this case, Toga developers need only include a `nextWidget.focus()` call in the `on_Press` handler for a Button. This brings the focus to the most-likely next widget as indicated by the focus-ring highlight. The user then only needs to press the spacebar to "press" that focused button and so on.

I am marking this Closed as it works as expected.

**Comment by Jim-Salmons** [comment]
Works as expected. See https://github.com/beeware/toga/issues/1495#issuecomment-1153245037 for explanation.
