### ISSUE TITLE
NumberInput interface needs an on_change event

### ISSUE THREAD

**Issue by voltagex** [beeware/toga#150]
Looking into this but I need some help.

**Comment by Ocupe** [comment]
Do you still need some help @voltagex ?

**Comment by voltagex** [comment]
Yep. I will have some time to look at this again tonight (GMT+10) and on
the weekend.

**Comment by obulat** [comment]
This issue can be closed, it was solved in https://github.com/beeware/toga/commit/5e34abb4c67ca14ad717b3a560709e930d64af00
