### ISSUE TITLE
WebView2Loader.dll not found

### ISSUE THREAD

**Issue by adetobi22** [beeware/toga#1530]
```
Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

I got the above error trying to run my toga app. It's a simple app that creates a window and display a local HTML file with toga.WebView as it's content.

Here is the code below : 

```
import toga
from toga.style.pack import Pack

class Application (toga.App):
    def startup (self):
        self.url = 'file:///../Templates/index.html'
        self.main_window = toga.MainWindow(title= self.name)
        self.display = toga.WebView(style=Pack(flex=1))
        box = toga.Box( children= [self.display])

        self.main_window.content = box
        self.display.url = self.url

        self.main_window.show()

def main():
    return Application('Recipe','org.pyproject.recipe')

if __name__ == '__main__':
    main().main_loop()

```
I also tried changing the URL to https://google.com, but it still didn't work.

Environment: Windows 11
Python Version : 3.7.9

**Comment by Spitskool42** [comment]
I think for the webview in windows you need to have the webview dll installed:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

When packaging and installing your app I think this will also be told.

**Comment by freakboy3742** [comment]
@adetobi22 Thanks for the report; unfortunately, I'm not able to reproduce this on my own machine - although, I'm on Windows 10, not 11, as I don't have access to a Windows 11 machine at present.

One vital detail that you left out of your report was the version of *Toga* that you're using; your report is similar to one that was reported a while ago (#1460), but that issue should have been fixed. Can you tell us the version of Toga

Also - can you tell us:
* Where are you running the code? Is it on a local disk? A network drive? In your home folder?
* What permissions does your user account have? Is it an administrator account, or a user account?
* How are you invoking this app? Are you using terminal or PowerShell, or are you running from inside an IDE? Are you using a virtual environment? Are you using the `py` shim, or invoking `python` directly?
* Is there anything else "interesting" about your setup that might be impacting on execution? e.g., do you have a firewall or virus detection code running? 

If you're feeling adventurous, it would also be helpful if you could set some breakpoints in `toga_winforms/libs/extensions.py`, and confirm if the paths it's loading are consistent with the locations in the WebView2 folder.

@Spitskool42 The error being reported is with the DLL that Toga packages, not the WebView2 libraries; plus, Windows 11 comes with the Webview2 libraries out of the box, so there's nothing additional that needs to be installed.

**Comment by adetobi22** [comment]
I'm running the latest version of Toga. 
And I'm running it in local disk on an administrator account
I use a virtual environment for my project.
And I'm invoking python in Windows CMD
@freakboy3742

**Comment by freakboy3742** [comment]
@adetobi22 We need you to be a little more precise than that. 

"Latest" could mean 0.3.0dev35, or a git hash; and which git hash will depending on exactly what you've installed and when. It also doesn't allow for the possibility that pip has used a cached version. The output of `pip freeze` is the easiest way to provide this detail.

"Invoking python" could mean `python foo.py`, `py foo.py`, `python -m foo`, `py -m foo`, `briefcase run`, `python path/to/foo.py`, and several others. We need to know *exactly* how you're invoking your app.

It would also be helpful if you could provide the entire log of the program running, not just the last couple of lines (or confirm that what you've provided *is* the last couple of lines).

A couple of other things to confirm:
* Can you confirm that `WebView2Loader.dll` actually exists in your site-packages after installing toga, and that it isn't 0 size?
* Are you running on a 64 bit or 32 bit machine (or perhaps on ARM64?)

**Comment by adetobi22** [comment]
The Problem was with my python  aplication. I took out python and re installed it, boom, all the missing dll were fixed.

**Comment by adetobi22** [comment]
Check how many versions is installed in your system. or take out all the python versions and reinstall python.
