### ISSUE TITLE
On Android, threads can be blocked by stdout activity

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1546]
If a user has a background thread that prints to stdout, that content will not be displayed unless there is some other stdout activity on the main thread. It is possible the thread may even be blocked by stdout activity.

**To Reproduce**

Sample app:
```
import asyncio
import time
from threading import Thread
import toga
from toga.style import Pack
from toga.style.pack import COLUMN


class SampleApp(toga.App):
    def my_thread(self):
        print("Thread start")
        self.i = 1
        while True:
            time.sleep(0.1)
            print(f"Thread {self.i=}")
            self.i += 1

    async def flush(self, widget):
        print("Flush", self.i)

    async def async_flush(self, widget):
        while True:
            await asyncio.sleep(1)
            print("Async Flush", self.i)

    def on_press(self, widget):
        print("start thread...")
        self.thread_1 = Thread(target=self.my_thread)
        self.thread_1.start()
        print("thread started...")

    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))
        button = toga.Button('Start thread', on_press=self.on_press)
        flush = toga.Button('Flush', on_press=self.flush)
        self.Text1 = toga.Label('Test 1')
        main_box.add(button, flush, self.Text1)

        # self.i = 0
        # self.add_background_task(self.async_flush)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

def main():
    return SampleApp()
```

Run this app on Android. 

Pressing the "Start thread" button should start a background thread that outputs 10 stdout lines per second. However, It will at best, output 1 or two lines of output, then stop. If you click the "Flush" button, it will output the current count, and one more line of thread output.

If you uncomment the installation of the `async_flush` handler, the same behavior is observed on the 1 second loop; you'd expect to see a count increase of 10 on every iteration.

If you remove the `sleep(0.1)` call from the thread, the behavior is different; you get "bursts" of activity; but it's definitely being gated by "flushes" of the stdout. At the very least, stdout on the thread isn't being flushed until it is flushed on the main thread; it is *possible* (but difficult to confirm) this is stopping the thread from executing entirely.

If you remove the `print()` call from the thread, but retain the `sleep()`, you get the same "blocking" behaviour, and the counter is only updated once per flush.

**Expected behavior**
The thread's output should be consistently updated every 0.1s, and output to the android log. This is the behavior observed on macOS.

**Environment:**
 - Operating System: Android
 - Python version: All
 - Software versions:
   - Briefcase: 0.3.8
   - Toga: e9ea8cd4

**Additional context**

Discovered as part of the discussion on #1538.

One theory - it could be a GIL issue associated with the subthread.

**Comment by mhsmith** [comment]
Thanks: I see the same behavior in all the variations you listed.

> If you remove the print() call from the thread, but retain the sleep(), you get the same "blocking" behaviour, and the counter is only updated once per flush.

This shows that the problem happens even when stdout isn't being used. Looks like it's failing to re-acquire the GIL after the sleep.

Anyway, all the variations work correctly on Chaquopy, so I won't look into this any further.

**Comment by freakboy3742** [comment]
You're correct that testing of threading with Rubicon et al was fairly superficial; if Chaquopy isn't affected by this, then I'm happy to ignore it for now on the basis that's the direction we're probably going.

**Comment by mhsmith** [comment]
Fixed by moving to Chaquopy.
