### ISSUE TITLE
Taking table data

### ISSUE THREAD

**Issue by WiNE-iNEFF** [beeware/toga#1563]
Hello everyone. I start work with toga beeware yestarday and now i look in toga documentation and test some code. And now I am faced with a problem related to tables.
I have code:
```
def tableselect(table, row):
            print(row)
data1 = ["test, test", 'FateSB1']
table = toga.Table(['World'], data=data1, on_double_click=None, on_select=tableselect, multiple_select=True)
```
According to the documentation, as far as I understand, my code should, when selecting a table cell (row), call the function in on_select = myfunc and pass 2 values ​​(row, table) and get the contents of the table. But in my case I get this <toga.sources.list_source.Row object at 0x000000000457E808>
<toga.sources.list_source.Row object at 0x000000000457E888>

**Comment by bruno-rino** [comment]
You need to access the table fields inside the Row object. In your case, `row.World` will be your data.

Take a look at the examples, they help:
- https://github.com/beeware/toga/blob/main/examples/table/table/app.py

Using a list of strings works, but you'll probably want to use the Sources API:
- https://toga.readthedocs.io/en/latest/background/data-sources.html
- https://github.com/beeware/toga/blob/main/examples/table_source/table_source/app.py
