### ISSUE TITLE
Should `TextInput` have an `is_valid` property?

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1582]
**Is your feature request related to a problem? Please describe.**
In 2020 we added the `validators` property to `TextInput` in *Toga*. With validators, one can validate that the entered content of the text input is valid according to given checkers. This is done via the `validate` methods that run all validators and display an error message if the value is invalid.

My question is this: `validate` returns a boolean indicating if the value is valid or not after running all validators. Should we also introduce an `is_valid` property to `TextInput` that returns if the value is valid **without running all validators again**?

On the one hand, it is unnecessary to run all validators if we already know that the value is valid/invalid. In Windows for example, we can simply access the `ErrorProvider` and check if an error is set or not.

On the other hand, `validate` already returns the desired property (is the value valid or not) and introducing a new property is a sort of repetition. The user could simply run `TextInput.validate()` (which is a public method) and get if the content is valid or not.

If you think that this property can be beneficial, I'll go ahead and implement it.

**Comment by freakboy3742** [comment]
The idea of an "is this valid" property makes some sense; on Cocoa, the answer will *always* be True (as a text input won't lose focus until it is in a valid state), but I can see how on Windows (or other backends that allow inputs to be in an error state), it could be useful - e.g., preventing form submission while an input is invalid. 

If at all possible, the implementation is that it should *not* be based on caching the last invocation of `validate()` - we should be reading the current error state, not maintaining a proxy of the last computed value.
