### ISSUE TITLE
Transform `Canvas` into an image

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1596]
**Is your feature request related to a problem? Please describe.**
After drawing some things with a `Canvas` widget, one might want to transform these drawings into a bitmap.
This can help the user:
* Save the canvas drawings to a file
* Copy the drawings to clipboard
* Some other stuff

**Describe the solution you'd like**
There should be a `Canvas.as_bitmap()` method that converts the content of the `Canvas` into a map. The bitmap can be represented as:
* `toga.Image` instance
* Plain matrix (list of lists, not `numpy.array`!)
* a new `toga.Bitmap` class

**Describe alternatives you've considered**
An alternative would be to implement the objectives stated above directly, ie. implement method such as `Canvas.save_to_clipboard()` or `Canvas.save_to_path(path)`. In any case, `Canas.as_bitmap()` should be implemented, at least as an internal method.

**Comment by freakboy3742** [comment]
Definitely a reasonable suggestion. I'd suggest `as_image()` is probably what we're looking for here, as that is functionally why most people will need this functionality (saving a chart for inclusion in a document, for example).
