### ISSUE TITLE
Let's reach that 100% coverage!

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1601]
**Description**
Lately we've managed to reach 100% coverage in briefcase (beeware/briefcase#887).

I think it is about time that we had 100% coverage for toga-core. At the time of opening this issue we stand on 93% coverage, which is pretty close! This will also remove the need for CodeCov.

100% coverage does not guarantee a bug-proof software, but it is an important step towards it.

**Comment by freakboy3742** [comment]
Won't argue with the goal - 100% coverage is absolutely desirable.

However, if we're doing a big push on testing, I'd rather it wasn't a simple "run to the line" for coverage. As I've mentioned elsewhere, moving to PyTest natively is high on my todo list; along the way, I'd like to audit the tests to make sure we actually have *good* tests, not just coverage.

**Comment by bailaoshijiadao** [comment]
ExampleWebView routine accesses video web page, how to play it in full screen? Now you can only zoom in to the size of the application box

**Comment by mhsmith** [comment]
@bailaoshijiadao: Please create a separate issue for your question, and make sure to mention what OS you're running on.

**Comment by freakboy3742** [comment]
For those tracking this issue: once #2075 (which includes #2058, #2020), #2065 (which includes #2017 and #2011), and #2029 (which includes #1903) are merged, we will have 100% coverage on core, android, cocoa, iOS, gtk, and winforms.
