### ISSUE TITLE
toga-winforms v0.3.0.dev38 gives Error on Windows app

### ISSUE THREAD

**Issue by pdimitroulis** [beeware/toga#1602]
Toga-winforms v0.3.0.dev38 gives AttributeError: 'TextInput' object has not attribute '_on_change'

**To Reproduce**
1. Create an app that uses toga.TextInput(),
2. Set toga-winforms==0.3.0.dev38 under Windows requirements in pyproject.toml file.
3. Update dependencies: `update -d`
4. Build and run app on Windows

**Screenshots**
![attribute_error](https://user-images.githubusercontent.com/6691022/194653140-a06a8ef9-cab7-41a5-907e-b5126a2e8507.PNG)

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.8.10
 - Software versions:
   - Briefcase: 0.3.9
   - Toga: 0.3.0.dev38

**Comment by freakboy3742** [comment]
Thanks for the report. 

As a clarification: the error only manifests if the widget is constructed with a `value` argument. If the input is constructed empty, this error doesn't occur. As a result, the `textinput` example works as written; but if you add a `value=` argument to one of the inputs, you get this error on startup.
