### ISSUE TITLE
toga.ScrollContainer doesn't work on android

### ISSUE THREAD

**Issue by foxopop** [beeware/toga#1611]
**Describe the bug**
When using toga.ScrollContainer, even with a single declaration, the app runs in Windows, but the android app can't be opened

**To Reproduce**
- write for example this simple line in your code :
   self.container = toga.ScrollContainer(horizontal=True, vertical=True)
- generate the apk and install it in your android phone ( ASUS )
- when your launch the app, the error "<nom appli> a cessé de fonctionner. Rouvrir l'application" appears 

**Expected behavior**
The app should launch without error

**Screenshots**

**Environment:**
 - Operating System: Android 8.0.0
 - Python version: 3.10.6
 - Software versions:
   - Briefcase: 0.3.9
   - Toga: 
toga                          0.2.15
toga-android                  0.3.0.dev38
toga-core                     0.3.0.dev38
toga-winforms                 0.3.0.dev38

**Additional context**
Neither work when putting ScrollContainer in a box

**Comment by mhsmith** [comment]
If you install the APK using `briefcase run`, it will show the app's log, which should include more details of the error.

Please also try upgrading to the current version, 0.3.10, and recreating the Android project using `briefcase create android`.

>   toga                          0.2.15
>   toga-android                  0.3.0.dev38
>   toga-core                     0.3.0.dev38
>   toga-winforms                 0.3.0.dev38

All Toga versions should be the same. But I guess this is the output of `pip list`, in which case, it'll only affect `briefcase dev`. 

When using `briefcase build` or `briefcase run`, the versions in pyproject.toml will take effect, so make sure they're all consistent.

**Comment by foxopop** [comment]
I upgraded to birefcase 0.3.10, but nothing changed.
After this, I modified my toml file like this :

### **before**
requires = [
    'toga-android>=0.3.0.dev38',
]

### **after**
requires = [
    'toga-android==0.3.0.dev35',
    'toga-core==0.3.0.dev35',
]

And it worked 👍 
Thanks a lot

Question : what do you mean by "install the APK using briefcase run" : I haven't briefcase on my phone !? :
To install the APK, I copy it to the phone, and I just launch it.....
