### ISSUE TITLE
Is there an instruction of building on Android?

### ISSUE THREAD

**Issue by butla** [beeware/toga#162]
I've seen https://pypi.python.org/pypi/toga-android but I can't find any doc about building for Android. Is this supported?

**Comment by Ry10p** [comment]
@butla 
Hey!

I have gotten as far as building a project but not able to upload it to the android phone yet...

maybe you can figure that part out and let me know?...

Here are my instructions:
```
$ pip install cookiecutter briefcase
$ cookiecutter https://github.com/pybee/briefcase-template
```
This will ask a bunch of questions of you. We'll use an app_name of "tutorial_0", and a formal_name of "Tutorial 0". Set the other values as you like

You'll now have a few files in this folder, including tutorial_0.

Check out what the provided tutorial_0/app.py file contains:

```
(BeeWare)user$ cd tutorial_0
(BeeWare)user$ cat tutorial_0/app.py
```
```
def main():
    # This needs to return an object that has a main_loop() method.
    return None
```

This won't do much as it is, but we can make it useful.

Add this into the app.py to make it useful:

```
class MyApp:
    def main_loop(self):
        print("Hello world")


def main():
    return MyApp()

```
**Make Sure You Have Gradle Installed**

now Lets Create That Android project! 

Create an Android project

It is all ready for using briefcase. You can invoke it, using:

`$ python setup.py android
`
**NOW** we must run (activating the virtualenv), the command line tool
 `./gradlew  `

from within the android dir to build the theapp.apk(debug)

I hope this helps!

**Comment by butla** [comment]
Thanks! I'll try to run it sometime during this EuroPython :)

**Comment by butla** [comment]
I'm not experienced with Gradle, but it seems that `gradlew` installs Gradle, so why do I need to install it beforehand?

**Comment by butla** [comment]
@Ry10p Ok, I've managed to run this and create an application that logs a string to Android's log. Yes, I know, that's an amazing feature. But even that caused problems for me.

My first problem is that I don't know much about Gradle. Should I just go through it's entire documentation, or is there a simpler way?
The other thing is my lack of knowledge about the steps that need to happen so the python code is built for Android and can interact with its APIs. In other words, I'd like to have a document that outlines what Toga does for Android.

I've found that your simple example is different in principle (main_loop not being a no-op) than [app.py from toga_android](https://github.com/pybee-attic/toga-android/blob/master/toga_android/app.py). On the other hand, I have no idea how current that file is.

I'm gonna write down the **full procedure** that was required for me on **Ubuntu 16.04**. Please provide any comments or clarifications needed.

**System setup**
1. `$ sudo apt install openjdk-8-jdk gradle`
1. Install [Android SDK Tools](https://developer.android.com/studio/index.html) (in "Get just the commandline tools" section). I'll assume that you've unpacked the zip to `~/bin/android_sdk`. I was trying to install it from Ubuntu packages, but after installing just android-sdk you won't have a functional environment. E.g. I didn't know how to install additional Android platforms.
1. Install Android API 15 (I'm not sure if this is necessary). `$ ~/bin/android_sdk/tools/bin/sdkmanager "platforms;android-15"`
1. Install platform-tools (stuff like `adb`): `$ ~/bin/android_sdk/tools/bin/sdkmanager platform-tools`
1. Add stuff needed by the Android tools to your `~/.bashrc`
    ```
    export ANDROID_HOME=$HOME/bin/android_sdk
    export PATH=$PATH:$HOME/bin/android_sdk/platform-tools
    ```

**Project setup**
1. Install cookiecutter to your user's Python tools (make sure you have `~/.local/bin` in `PATH`): `$ pip3 install --user cookiecutter`
1. Create the project's structure with cookiecutter: `$ cookiecutter https://github.com/pybee/briefcase-template`
1. Modify `<project_name>/<project_name>/app.py`. You can do it like this:
    ```python
    class MyApp:
        def main_loop(self):
            print("It's actually working!!!")


    def main():
        # This needs to return an object that has a main_loop() method.
        return MyApp()
    ```
1. Create a virtualenv (I've used Python 3.5) and **activate** it.
1. Generate the project's structure: `$ cd <project_name>; python setup.py android`
1. For some reason, Gradle didn't see `voc` tool from my virtualenv, so I had to replace all instances of `voc` in `<project_name>/android/build.gradle` with the absolute path to `voc` in my virtualenv (get that by running `$ which voc` run from the virtualenv).
1. Turn on USB debugging on your Android device and connect it over USB, or start an emulator.
1. Start watching your application's logs in some window: `$ adb logcat Python:* *:S` (`*:S` means that you silence all the other logs; if you want to have at least the errors from the rest of the system, use `*:E`)
1. Build and install the application: `$ cd android && ./gradlew run`. You should the the message printed by the application in the log.

**Comment by Ry10p** [comment]
@butla 

Hey!

I'm Sorry you had some issues with the build process.

As far as I can see you have hit everything you needed to do in the project instructions.  It all seems exact in terms of how I set my production ENV also using Ubuntu 16.04.

The question about gradle vs gradlew is that "The difference lies in the fact that ./gradlew indicates you are using a gradle wrapper. The wrapper is generally part of a project and it facilitates installation of gradle."  More information can be found in the links at the bottom.

I was unclear myself if the installation of gradle was needed, but I have it installed for use with CORDOVA, and I didnt want you to run into any problems so I figured I would mention it.

Im sorry again if it was confusing.


https://stackoverflow.com/questions/39627231/difference-between-using-gradlew-and-gradle

https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by Ry10p** [comment]
@butla 

As far as...."The other thing is my lack of knowledge about the steps that need to happen so the python code is built for Android and can interact with its APIs. In other words, I'd like to have a document that outlines what Toga does for Android."

TOGA Aka Beeware (Briefcase), is still in the early stages of its development, so a document of all the calls to the android API wont be ready for a little bit.  

Im currently working on porting the widgets into the toga system.  Currently the toga-gtk (Ubuntus bindings) are not complete so we have limited functionality in comparison to someone using Mac OS.  

The process of creating the widgets is porting the widgets (android api calls)  to the Toga-gtk project  from GTK (Python3-gtk https://python-gtk-3-tutorial.readthedocs.io/en/latest/introduction.html , https://developer.gnome.org/gtk3/3.0/ ).  Once we have that we can work in creating a formal documentation explaining the total use.

@butla  are you maybe interested in helping out? There is a lot to do and I'm a student so I don't have all the skills in the world lol.

**Comment by Ry10p** [comment]
@butla  

Did I cover your question correctly?

Also a bit more of an informative introduction to the Beeware project is in a link bellow.

https://www.youtube.com/watch?v=hKMdTaMfFrM

**Comment by Connor124** [comment]
Could I recommend that you add this to the README or docs so that people can actually find it.

**Comment by danyeaw** [comment]
@Connor124 That is a great idea, and we could definitely use help improving the documentation. Is that something you are interested in helping out with?

**Comment by Connor124** [comment]
As much as I'd love to help, I haven't ever been actually able to build anything with Toga for Android. I did try https://github.com/eliasdorneles/tictactoe-voc, though and it works fine, but doesn't use Toga.

**Comment by butla** [comment]
@Ry10p Sorry I didn't respond then, but I was also swamped with work :)

What I wanted from the docs is some high level overview of how Toga works for Android. That is what steps it takes for a python code to end up as an APK runnable by Android. Does it translate python somehow? What's the Java library that's working as an API between Python code and Android's APIs? Questions like that.

If I had this high-level understanding of what's supposed to happen, I could easier contibute something, and reason about why the Gradle builds were failing for me, when I tried running them.

**Comment by danyeaw** [comment]
@butla Toga translates into the Android API to our cross-platform Toga API. VOC converts the Python to Java Bytecode. Briefcase packages it all up so that it can run on Android.

Have you looked at the documentation for briefcase?
https://briefcase.readthedocs.io/en/latest/background/getting-started.html
It already has the step-by-step on how to get things setup, I don't think this should be in the Toga docs. The Toga docs should just be about how you can design a cross-platform native application.

**Comment by butla** [comment]
@danyeaw I don't think that Briefcase's documentation got any more detailed then since I last saw it. The problem for me was that I just hit a wall with Gradle errors, while not knowing much about Gradle or Groovy, and without any source of knowledge about what the toolchain should actually do (how Gradle, briefcase, VOC, and whatever other component come together to translate the code and build the app). So I couldn't debug the "simple how-to" which just wasn't working for me.

The reliability of the tools might have improved, I don't know.

**Comment by freakboy3742** [comment]
I'm going to close this ticket; we've got a contractor actively working on Android support under a grant from the PSF. One of the products of that work will be additions to the Briefcase tutorial for deploying Toga on Android.

**Comment by butla** [comment]
Awesome 🙂
