### ISSUE TITLE
Android: implement App.exit

### ISSUE THREAD

**Issue by foxopop** [beeware/toga#1622]
**Describe the bug**
In dev mode, when I exit my app with a button that execute the 2 instructions below, the app raises a ThrowLastAsClrException exception.

        self.app.exit()
        sys.exit()

**To Reproduce**

1) Write the following app :

```
import toga
import sys
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class HelloWorld(toga.App):

    def clicQuitter(self, widget):
        self.app.exit()
        sys.exit()

    def startup(self):
        main_box = toga.Box()

        btnQuitter = toga.Button( 'Quitter', on_press = self.clicQuitter, style=Pack(flex=1, padding=(0,50)) )       
        boutons = toga.Box( id='boutons', style=Pack(direction=ROW, padding_top=10) )        
        boutons.add(btnQuitter)       
        main_box.add( boutons )

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

def main():
    return HelloWorld()

```

2) execute " briefcase dev"

3) clic on the "Quitter" button

**Expected behavior**

The  app must return to the DOS prompt, without message

**Screenshots**
```
[helloworld] Starting in dev mode...
Traceback (most recent call last):
  File "D:\DocsFX\Docs_informatiques\python\beeware\helloworld\src\helloworld\app.py", line 14, in clicQuitter
    sys.exit()
  File "D:\DocsFX\Docs_informatiques\python\beeware\beeware-venv\lib\site-packages\toga\handlers.py", line 66, in _handler
    result = handler(interface, *args, **kwargs)
  File "D:\DocsFX\Docs_informatiques\python\beeware\beeware-venv\lib\site-packages\toga_winforms\widgets\button.py", line 19, in winforms_click
    self.interface.on_press(self.interface)
   à Python.Runtime.PythonException.ThrowLastAsClrException()
   à Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   à Python.Runtime.Dispatcher.Dispatch(Object[] args)
   à __System_EventHandlerDispatcher.Invoke(Object , EventArgs )
   à System.Windows.Forms.Control.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.Button.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

(beeware-venv) D:\DocsFX\Docs_informatiques\python\beeware\helloworld>

**Environment:**
 - Operating System: windows 10 Famille
 - Python version:  3.10.6
 - Software versions:
   - Briefcase: 0.3.9 ou 0.3.10 ou 0.3.11
   - Toga: toga                          0.2.15
      toga-android                  0.3.0.dev38
      toga-core                     0.3.0.dev38
      toga-winforms                 0.3.0.dev38

**Additional context**
It seems to me that it worked correctly in a previous version, but I don't know version of what because I've changed briefcase, toga

**Comment by freakboy3742** [comment]
Does "App exit" even make sense in an Android context? As noted on #1623, iOS explicitly *doesn't* have a concept of an app exiting; it may suspend or go to sleep, but you'll never see an iOS app that has a "quit app" button. I don't have a lot of "daily driver" experience with Android, but I haven't seen an app with a "Quit" button - is this something that should even exist?

**Comment by mhsmith** [comment]
Let's centralize discussion on this in #1623.
