### ISSUE TITLE
Restructure repository

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1627]
After this week's release is done, I propose we make the following changes:
* Move the content of the top-level `src` directory (`core` and the backends) to the top level of the repository.
* Move the `toga` package's setup.py, setup.cfg and MANIFEST.in to a subdirectory of the top level.
  * The `toga` package's MANIFEST.in currently pulls in most of the repository. This significantly slows down the packaging step in the CI, and I'm not sure what it's supposed to achieve.
 
This would have the following advantages:
* The paths to files in `core` and the backend would be shortened, and would no longer have two `src` directories as has been the case since #1614.
* The release scripts and workflows could be simplified, because all packages would now be a top-level subdirectory, whereas the current arrangement has them in 3 different places (`demo`, `src/*`, and the top-level `toga`).

**Comment by freakboy3742** [comment]
The top level src change makes sense, but I'm not sure I follow the motivation in the second suggestion. 

Having all setup.py definitions in a subdirectory definitely makes life easier; but the purpose of the top level `toga` package (especially the source package) is so that there's a "here's the entire project" tarball. Is the motivation to demote that package to be purely a "here's an install shim" package? If that's the case, what's the proposed story for obtaining the "full tarball"?

**Comment by mhsmith** [comment]
> Is the motivation to demote that package to be purely a "here's an install shim" package?

Yes, that's the idea. 

> If that's the case, what's the proposed story for obtaining the "full tarball"?

I'm not really sure what the use case would be for such a tarball, because anyone who wants to actually contribute to the project should just do a Git clone. But if for some reason they don't want to do that, they can now download a snapshot from the "Source code" link on the [GitHub release page](https://github.com/beeware/toga/releases), which has a simple and predictable URL.

**Comment by freakboy3742** [comment]
Yeah - I guess it's more a matter of habit that I added a "full package" source tarball. Thinking about it some more, I guess it doesn't make that much sense - as you say, contribution happens via GitHub. Based on some conversations I've had this week, I'm wondering if it even makes sense to stop producing sdists *at all*, and only produce wheels.
