### ISSUE TITLE
Source installs no longer working

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1632]
#1614 made some changes to the packaging of modules to support the release package workflow.

The wheels generated from this process appear to work fine; however, source installs don't appear to be working. I've had problems on both macOS and Android.

**To Reproduce**
1. `briefcase run` or `briefcase run android` on Tutorial 0.

**Expected behavior**

App should start.

**Environment:**
 - Operating System: macOS
 - Python version: 3.10
 - Software versions:
   - Briefcase: 0.3.11
   - Toga: 96881f093

**Comment by layday** [comment]
> The wheels generated from this process appear to work fine

They do, but the `src` folder's contents are bundled in the main toga wheel as of 0.3.0.dev39 and get installed by pip as if they were packages.

**Comment by layday** [comment]
At some point in the not too distant past setuptools was madde to auto-discover packages under `src`, so the following line needs to be added to the toga `setup.cfg` under `[options]` to prevent it from bundling everything under `src` in the wheel:

```
packages =
```

cc @abravalheri in case he has a better suggestion.
