### ISSUE TITLE
Toga demo "Tree" tab works on Raspberry Pi but not Windows 

### ISSUE THREAD

**Issue by Resonanz** [beeware/toga#1651]
Run the Toga demo app on Windows and the "Tree" tab is empty. (Python 3.11.0)

Do the same on Raspberry Pi (Linux) and the "Tree" displays "Root1" etc. (Python 3.7.3)

![image](https://user-images.githubusercontent.com/6218191/199853881-c0ced1e8-81e8-4c08-a68a-baae9e1db46c.png)

**Comment by freakboy3742** [comment]
Thanks for the report; the Tree widget on Windows is known to be bare-bones; if you [check the implementation of Tree on Winforms](https://github.com/beeware/toga/blob/main/src/winforms/src/toga_winforms/widgets/tree.py), it won't be surprising that it doesn't work.

At this point, we don't keep open issues for individual incomplete widgets, as it doesn't actually aid progress on the project. There's a lot of widgets that are missing, and individual features on widgets that are missing; having individual tickets for each one doesn't help us progress towards the goal of completion.
