### ISSUE TITLE
Minor documentation fix

### ISSUE THREAD

**Issue by Resonanz** [beeware/toga#1653]
On this page there is a missing "single quote" after "box_b":

https://toga.readthedocs.io/en/latest/reference/api/containers/box.html

```
import toga

box_a = toga.Box('box_a')
box_b = toga.Box('box_b)

box = toga.Box('box', children=[box_a, box_b])
```

**Comment by freakboy3742** [comment]
Thanks for the report. 

For reference - it's almost as easy to modify the docs as it is to open a ticket describing a problem with the docs. The original source is on [this page](https://github.com/beeware/toga/blob/main/docs/reference/api/containers/box.rst); GitHub lets you make single-file edit PRs from inside the Github GUI.
