### ISSUE TITLE
Stop making .dev releases

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1670]
Setuptools_scm isn't compatible with the way we currently use the .dev suffix, because it uses that suffix for its own purposes.

The simplest solution is to make a v0.3.0 tag now (it doesn't matter on which commit), and let setuptools_scm generate v0.3.1.devX versions after that point. Then the next public release will be 0.3.1.

@freakboy3742: Are you OK for me to go ahead and do this?

**Comment by freakboy3742** [comment]
We're well overdue for a formal 0.3.0 release, so I have no problem dropping `dev` releases. Personal preference would be to cut an rc1 so we can shake out any packaging problems before we push a 0.3.0 final, but as soon as we're sure the RC releases are doing everything we want, we should cut 0.3.0 final.

**Comment by mhsmith** [comment]
Related: https://github.com/beeware/briefcase-template/issues/38
