### ISSUE TITLE
Validate platform implementation using a json schema

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1685]
**Is your feature request related to a problem? Please describe.**
At the moment, in order to check that each widget implementation of a platform (winforms, cocoa, gtk, etc.) has all the desired methods that the interface layer needs, we look at the methods and parameters of `toga_dummy` and make sure they are identical to each and every platform.

In the future, we might want to replace the usage of `toga_dummy` with "simple" `mock`. In order to get there, we need to find another way to test the schema of all implementation layers.

One such way is to define the schema using a [json-schema](https://json-schema.org/) and to compare the implementations according to it.

**Describe the solution you'd like**
Here is an example of how such schema should look like for the `toga.Switch` widget:
```json
{
    "className": "Switch",
    "methods": [
        {
            "methodName": "__init__",
            "parameters": ["interface"]
        },
        {
            "methodName": "set_value",
            "parameters": ["value"]
        },
        {
            "methodName": "get_value",
            "parameters": []
        }
        ...
    ]
}
```
We can save all those schemas in a `schemas` directory and compare each implemntation layer to a schema.

**Describe alternatives you've considered**
There are other ways of defining schema other than json-schema, even though it is quite popular.

**Comment by mhsmith** [comment]
I suspect that once we have tests that ensure the backend APIs actually *work*, there won't be much point in maintaining the existing tests that simply assert that the APIs *exist*.

**Comment by freakboy3742** [comment]
On top of that - I think it's highly unlikely we'll replace toga_dummy with a simple mock. The Dummy backend isn't (or shouldn't be) just an API stand-in - it is (or should be) a functional reference implementation of the backend API, with easily assertable properties. In an ideal world, you'd be able to test your app against the dummy backend and have a reasonable degree of confidence that your app will run on *any* platform.

Thanks for the suggestion, but I'm going to close this ticket.
