### ISSUE TITLE
Warnings when running Hello World script

### ISSUE THREAD

**Issue by pauljurczak** [beeware/toga#1718]
### Describe the bug

```
(.venv) paul@desktop:~/st/toga$  cd /home/paul/st/toga ; /usr/bin/env /home/paul/st/toga/.venv/bin/python /home/paul/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 34737 -- /home/paul/st/toga/print.py 
/home/paul/st/toga/.venv/lib/python3.11/site-packages/toga_gtk/app.py:65: DeprecationWarning: There is no current event loop
  self.loop = asyncio.get_event_loop_policy().get_event_loop()
/home/paul/st/toga/.venv/lib/python3.11/site-packages/toga_gtk/app.py:40: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.native.set_wmclass(app.interface.name, app.interface.name)
WARNING: Can't find icon resources/toga; falling back to default icon
hello
```

### Steps to reproduce

1. Install the prerequisites and Toga in venv.
2. Run the script from https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html.
3. Click on Help->About First App

```
import toga


def button_handler(widget):
    print("hello")


def build(app):
    box = toga.Box()

    button = toga.Button("Hello world", on_press=button_handler)
    button.style.padding = 50
    button.style.flex = 1
    box.add(button)

    return box


def main():
    return toga.App("First App", "org.beeware.helloworld", startup=build)


if __name__ == "__main__":
    main().main_loop()
```

### Expected behavior

No warnings?

### Environment

- Operating System: Ubuntu 22.04.1
- Python version: 3.11.1
- Software versions:
  - Briefcase:
  - Toga: 0.3.0.dev39
  - ...

### Logs

```

```

**Comment by pauljurczak** [comment]
Thank you for looking into it.

**Comment by tuhinmallick** [comment]
Is this issue still available then I would like to give it a try.

**Comment by freakboy3742** [comment]
@tuhinmallick This is definitely still available to look at. There's 2 separate issues to be resolved - the first is a fairly straightforward API rename; the second is the GTK API warning. You don't need to solve both; a PR solving either of them in isolation would be acceptable.

**Comment by tuhinmallick** [comment]
Thanks @freakboy3742  I will try to segregate the issues in different PR if possible.

I have made a PR #1725 please review it and let me know if the change should be done on both dialog.py and app.py or only in app.py
