### ISSUE TITLE
Beeware supports type annotations?

### ISSUE THREAD

**Issue by onsunsl** [beeware/toga#1744]
### What is the problem or limitation you are having?

I am a new user of beeware. I am trying to run the demo but when I enter the code in the ide, I have no idea what attributes or values to fill in the widget. It is strongly recommended that beeware apply python type annotations. 

Hare is a demo from the document.

```python
import toga


def button_handler(widget):
    print("hello")


def build(app):
    box = toga.Box()

    button = toga.Button("Hello world", on_press=button_handler)
    button.style.padding = 50
    button.style.flex = 1
    box.add(button)

    return box


def main():
    return toga.App("First App", "org.beeware.helloworld", startup=build)


if __name__ == "__main__":
    main().main_loop()

```

When I want to modify the properties of the button, I cannot obtain the properties of the style according to the prompt of IDE, because there is no type annotation in the source code of toga. I need to consult the documentation to know what properties it has. I think it's very user-unfriendly.

### Describe the solution you'd like

I hope to introduce python type annotations in all codes of beeware, which is very convenient like the `httpx` library

![image](https://user-images.githubusercontent.com/16914781/212796079-eb7d1e08-6914-43fd-b58a-873ea16efa4b.png)

### Describe alternatives you've considered

```python

class Button(Widget):
    
    def __init__(
            self,
            text=NOT_PROVIDED,  # BACKWARDS COMPATIBILITY: The default value
                                # can be removed when the handling for
                                # `label` is removed
            id=None,
            style: Style =None,
            on_press: callable =None,
            enabled: bool =True,
            factory: Any =None,
            label: Any =None,  # DEPRECATED!
    ):
    pass

```

### Additional context

Good annotations can effectively save users' development time. Thank you every one.

**Comment by freakboy3742** [comment]
Thanks for the suggestion. I'm not fundamentally opposed to the addition of type annotations; however, they're also not a substitute for documentation, and IDE tooling that displays that documentation in context.

I'll leave this ticket open as an indicator that we're sympathetic to PRs that add type annotations that improve discoverability of APIs - however, in the short term, I'd expect to see most of the effort in this space directed towards documentation, rather than type annotations.

**Comment by onsunsl** [comment]
thanks for your reply.

**Comment by freakboy3742** [comment]
I'm going to close this ticket; we've been added annotations as part of the widget audit, and we've made changes to the documentation to surface those annotations.
