### ISSUE TITLE
Add "rehint()" on the background of the widget after changing font size [Core] [Cocoa]

### ISSUE THREAD

**Issue by Dayof** [beeware/toga#176]
To reproduce this error I made this code https://gist.github.com/Dayof/f25e73a902b3c1d0c2b83dc6e3fba8f9 .

The following image shows the a normal behavior of a ``Label``, with the ``Font`` size modified, inside of a ``Box``:

![1](https://user-images.githubusercontent.com/8198348/26858450-af18f7d2-4b07-11e7-83ea-97389c792b75.png)

And in the next image shows the a bad behavior of a ``Label``, with the ``Font`` size modified, inside of a ``Box`` and this ``Box`` is inside of a ``SplitContainer``:

![2](https://user-images.githubusercontent.com/8198348/26858456-b505a42e-4b07-11e7-9e2f-5c36a8eeb3a8.png)

After applying a ``test_status.rehint()`` the size of the ``Label`` adjust as should it be:

![3](https://user-images.githubusercontent.com/8198348/26858472-c835e874-4b07-11e7-823a-5603d9c3e373.png)

This method (rehint()) should be activated on ``Toga`` background after change a ``Label``s ``Font``, without forcing the user worry about this.

**Comment by barryjohnthompson** [comment]
Hi! I'd be interested in taking a look at this issue, if it still needs to be done?

**Comment by Donyme** [comment]
***AttributeError: 'Label' object has no attribute 'set_font'***
Am receiving this error upon running the code

**Comment by freakboy3742** [comment]
@mav-erick It's entirely expected that the *core* widget doesn't have a `set_font` method. The core widget has a `font` property; altering that attribute calls set_font on the backend. My guess is that it's the property setter that needs the rehint call.

(This is a general pattern in Toga - the front end exposes the "most Pythonic" API it can; the backend then defines specific "do X" APIs to implement that frontend design)

**Comment by RishabhAgarwal-2001** [comment]
@freakboy3742 I am facing issue in changing the font and colour of the `label` in Toga Gtk implementation. I tried altering the `font` property of the label through the code below, but no change was noticed. 
`class Test_App( toga.App ) :

    def startup( self ) :
        self.main_window = toga.MainWindow( title=self.name )

        body_box = toga.Box(id='Main Box')
        label = toga.Label("Quick Quiz")
        label.style.font = toga.fonts.Font(family='Times New Roman', size=50)
        body_box.add(label)
        self.main_window.content = body_box

        self.main_window.show()`

![image](https://user-images.githubusercontent.com/45998880/85969805-54876f00-b9e6-11ea-9bc9-c5a1a0a1108e.png)

Is this functionality still to be coded for Linux?

**Comment by freakboy3742** [comment]
@RishabhAgarwal-2001 Well, the fact that the font isn't changing would seem to suggest that it is... :-)

**Comment by freakboy3742** [comment]
Closing on the basis was fixed with #974
