### ISSUE TITLE
How to eliminate the problems that occur in running your second sample program?

### ISSUE THREAD

**Issue by haisheng666** [beeware/toga#1773]
### Describe the bug

[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.clear_error()
[GTK+] Not implemented: TextInput.set_on_lose_focus()
[GTK+] Not implemented: TextInput.set_on_gain_focus()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.clear_error()
[GTK+] Not implemented: TextInput.set_on_lose_focus()
[GTK+] Not implemented: TextInput.set_on_gain_focus()

### Expected behavior

[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.clear_error()
[GTK+] Not implemented: TextInput.set_on_lose_focus()
[GTK+] Not implemented: TextInput.set_on_gain_focus()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.clear_error()
[GTK+] Not implemented: TextInput.set_on_lose_focus()
[GTK+] Not implemented: TextInput.set_on_gain_focus()

### Environment

- Operating System:
- Python version:
- Software versions:
  - Briefcase:
  - Toga:
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
This is all expected behavior. The test app is using APIs that aren't currently implemented on the GTK backend. Toga is v0.3, and there are lots of features that haven't been implemented yet.
