### ISSUE TITLE
how to use micphone for mobile phone

### ISSUE THREAD

**Issue by lj267lj267** [beeware/toga#1775]
### What is the problem or limitation you are having?

have no APIs for micphone of mobile phone

### Describe the solution you'd like

record sound on mobile phone

### Describe alternatives you've considered

have no

**Comment by freakboy3742** [comment]
Toga doesn't currently have APIs for native device hardware. 

You can access native APIs using the bridging layer (Rubicon on macOS/iOS, Chaquopy on Android, Python.net on Windows, PyGObject on Linux).
