### ISSUE TITLE
Cocoa MultilineTextInput.value returns an ObjCStrInstance

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1779]
```
rubicon-objc       0.4.5
toga-cocoa         0.3.0
toga-core          0.3.0
```

```pycon
Python 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 09:09:08) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import toga
>>> mti = toga.MultilineTextInput(value="hello")
[Cocoa] Not implemented: MultilineTextInput.set_on_change()
>>> mti.value
<rubicon.objc.collections.ObjCStrInstance 0x1110204c0: NSBigMutableString at 0x111639ae0: hello>
```

This can cause apparently impossible situations like a string changing its value:
```pycon
>>> x = mti.value
>>> print(x)
hello
>>> mti.value = "world"
>>> print(x)
world
```

When we come to do the backend tests for this widget, or any other widget with string attributes, we should assert that the value returned through the Toga public API is actually a Python `str`.

**Comment by bruno-rino** [comment]
I just ran into this. 

TextInput casts the value to `str`:
https://github.com/beeware/toga/blob/main/cocoa/src/toga_cocoa/widgets/textinput.py#L211-L212

while MultilineTextInput does not:
https://github.com/beeware/toga/blob/main/cocoa/src/toga_cocoa/widgets/multilinetextinput.py#L78-L79

Seems like a simple fix; are you waiting to address this during the widget audit?

**Comment by mhsmith** [comment]
It looks like we missed this during the audit. We should go through all the widget properties that return strings, and add `isinstance` checks to the testbed.

**Comment by tswinb** [comment]
I will look at this one!
