### ISSUE TITLE
Text within MultilineTextInput remains black in macOS Dark Mode

### ISSUE THREAD

**Issue by jon-tes** [beeware/toga#1783]
### Describe the bug

When using macOS in dark mode, the text within MultilineTextInput widgets remains black, making it difficult to read.

### Steps to reproduce

1. Add a MultilineTextInput widget to an app
2. Ensure macOS dark mode is enabled
3. View the app in dev mode or run the app 
4. Type text into the MultilineTextInput widget
5. See error

### Expected behavior

The color of the text within the MultilineTextInput widget should be white when in dark mode and black in light mode. This works as expected with TextInput widget.

### Screenshots

<img width="270" alt="Screenshot 2023-02-16 at 1 44 35 PM" src="https://user-images.githubusercontent.com/42925864/219470705-d344d219-f0c1-46ed-8fd9-085fccfef03f.png">

### Environment

- Operating System: macOS 13.1
- Python version: 11
- Software versions:
  - Briefcase: 0.3.12
  - Toga: 0.3.0

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report. Clarifying some details:
* Are you running your app directly as a Python module (e.g., `python -m myapp`), or through briefcase? 
* Have you applied any styling to your app, or is it a simple "multiline text input in a window"?
* You mention that text input isn't affected; does this problem appear to affect any other widget, or just Multilinetextinput?
* Is your system set up as "pure" dark mode, or as "auto" (i.e., adapt during the day)?

**Comment by jon-tes** [comment]
Hello, thank you for the quick response, I really appreciate it!

Here are the additional details:
- The issue can be reproduced when the app is ran as a module, through briefcase, and on end user devices after packaging the app.
- My app has quite a bit of styling. While troubleshooting, I also created a very simple app in a separate virtual environment with no styling and just a multiline text input widget in a window and was able to reproduce the issue there as well (under the same app running conditions stated above).
- All other widgets appear to be unaffected, Multilinetextinput is the only widget with the issue.
- The issue can be reproduced with both "pure" and "auto" darkmode".

What's even stranger is that I had packaged a version of this same app on January 12th that didn't have the issue. It wasn't until about February 9th when I repackaged the app after some updates that I noticed the issue. I  In my troubleshooting since, I've tried to uninstall and reinstall briefcase and toga, along with creating several instances of virtual environments, and even switching python versions, with no luck.

**Comment by freakboy3742** [comment]
Thanks for those clarifications. Looks like [this is a known quirk](https://stackoverflow.com/questions/52829249/nstextview-draws-black-on-almost-black-in-dark-mode) - there's an extra attribute that needs to be set on NSTextView to make it adhere to dark mode settings.

I can't explain why this would have worked before Feb 9, though - this appears to be a long-standing Cocoa bug/feature. best guess is that maybe you had a local style that was changing something. 

Either way - I've just pushed #1785 to address this problem; thanks again for the report!
