### ISSUE TITLE
ImageView causes resize to act weird

### ISSUE THREAD

**Issue by LunaMeadows** [beeware/toga#1795]
### Describe the bug

When adding an ImageView to a box, and then adding the box to a splitcontainer if I attempt to resize the window the window will grow very large up and down but not sideways. If I move the divider, it will slowly grow up and down. 

Code to recreate

```
import toga
from toga.style.pack import COLUMN, Pack, BOTTOM, ROW, CENTER, JUSTIFY
def build(app):
    box = toga.Box('box1', style=Pack(direction=ROW, padding_top=100, alignment=BOTTOM))

    # button = toga.Button('Hello world', on_press=button_handler)
    image_camera_viewer = toga.ImageView(image=toga.Image('0_0.jpg'), style=Pack(width=420))
    box.add(image_camera_viewer)

    box2 = toga.Box('box2')

    split = toga.SplitContainer()
    split.content = [(box2, .3), (box, .7)]

    return split

    return box


def main():
    return toga.App("Testing", "org.test.test", startup=build)


if __name__ == "__main__":
    main().main_loop()`
```

### Steps to reproduce

Add ImageView to box
Add box to splitcontainer

### Expected behavior

Window should grow when resizing whole window and not resize at all when moving divider

### Environment

- Operating System: Ubunto 20.04
- Python version: 3.8
- Software versions:
  - Briefcase: N/A
  - Toga: 0.3.0

**Comment by mhsmith** [comment]
I've noticed this too. I was able to work around it by setting a fixed width and height on the ImageView.

**Comment by LunaMeadows** [comment]
That fixes it, thanks!

**Comment by mhsmith** [comment]
Let's leave the issue open, because there is clearly a bug here.
