### ISSUE TITLE
In the created application for Android, the background color of the Label does not change.

### ISSUE THREAD

**Issue by rem3228** [beeware/toga#1805]
### Describe the bug

Hello! I am using code:

```
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class StartApp(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        name_label = toga.Label(
            "Your name: ",
            style=Pack(padding=(0, 5), background_color='red')
        )
        self.name_input = toga.TextInput(style=Pack(flex=1))

        name_box = toga.Box(style=Pack(direction=ROW, padding=5))
        name_box.add(name_label)
        name_box.add(self.name_input)

        button = toga.Button(
            "Say Hello!",
            on_press=self.say_hello,
            style=Pack(padding=5)
        )

        main_box.add(name_box)
        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def say_hello(self, widget):
        print(f"Hello, {self.name_input.value}")

def main():
    return StartApp()
```

I compiled the code on Windows, the background of the Label changed to red, as expected. But if I compile under android, then the background of the Label does not change. Why can this be so? I am used command: briefcase update android, briefcase build android and briefcase run android. 

### Steps to reproduce

1. briefcase update android
2. briefcase build android
3. briefcase run android
4. See that background color of the label does not changes.

### Expected behavior

In the created application for Android, the background color of the Label does not change to red, while everything works in the one created for Windows.

### Screenshots

![Screenshot_3](https://user-images.githubusercontent.com/105379721/224155746-24a03483-4de3-4f37-8a0a-7192153aa9cb.png)

![Screenshot_2](https://user-images.githubusercontent.com/105379721/224153014-e1cc1476-a9e5-4b82-b029-a1966969c8d0.png)

### Environment

- Operating System: Windows 
- Python version: 3.10
- Software versions:
  - Briefcase: 0.3.12
  - Toga: 0.3.0

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report - this is a known omission in the implementation of Label. It was recently fixed in the main branch of Toga.

**Comment by rem3228** [comment]
Hello, thanks for the answer. When can we see this change in the pip
package? Or how to upgrade it using github  main branch  ?

пт, 10 мар. 2023 г. в 02:17, Russell Keith-Magee ***@***.***>:

**Comment by mhsmith** [comment]
I'm not sure when the next release will be on PyPI, but here's how to use the main branch:

Normally I'd recommend using the `git+https` syntax to install both `toga-core` and `toga-android`, but it looks like that won't work with the old version of pip we use for Android, giving the error:
```
No matching distribution found for toga-core==0.3.1.dev77+g4f6f7ab9 (from toga-android==0.3.1.dev77+g4f6f7ab9)
```
So instead, you'll have to clone the `toga` repository, then edit your pyproject.toml file to replace this line:
```
    "toga-android~=0.3.0"
```
With this:
```
    "path/to/toga/android",
    "path/to/toga/core",
```
where `path/to/toga` is the location of your clone.

**Comment by rem3228** [comment]
Thanks a lot, it worked!

пт, 10 мар. 2023 г., 22:12 Malcolm Smith ***@***.***>:
