### ISSUE TITLE
MultilineTextInput on Android: Text is not at the top of the widget

### ISSUE THREAD

**Issue by t-arn** [beeware/toga#1807]
### Describe the bug

MultilineTextInput on Android has a set_alignment method that should set Gravity.TOP but this never happens.
And so, the text does not start at the top of the widget:
![Screenshot_1678480227](https://user-images.githubusercontent.com/8982757/224422655-837ceb0f-a03c-4b94-b73b-f3b331dff938.png)

It is also not possible to call the set_alignment method on the interface.

### Steps to reproduce

1. Build the multilinetextinput example for Android and run it

### Expected behavior

The text should be at the top of the widget as it is on Windows:
![image](https://user-images.githubusercontent.com/8982757/224423183-366f3a7a-4937-4e58-8b8d-fa2c0692d3a9.png)

### Environment

- Operating System: Android
- Python version: 3.9.12
- Software versions:
  - Briefcase: 0.3.12
  - Toga: main branch, commit [4f6f7ab] of 2023-03-05

**Comment by freakboy3742** [comment]
Fixed by #1808
