### ISSUE TITLE
[Android] Not implemented: Window.select_folder_dialog()

### ISSUE THREAD

**Issue by rem3228** [beeware/toga#1810]
### Describe the bug

I built an application for android, and used a command in it, by clicking on which, I want to select a folder with files, but in the log I see the following: 
03-11 07:59:02.231 11776 11776 I python.stdout: [Android] Not implemented: Window.select_folder_dialog()
Dialog box does not open.
Code that fires when a command is clicked:

```
def open_folder(self, widget):
        self.main_window.select_folder_dialog("Выберите папку", initial_directory=os.path.dirname(os.path.realpath(__file__)), on_result=self.set_folders)
```

### Steps to reproduce

1. briefcase create android
2. briefcase build android 
3. briefcase run android
4. Click on the command
5. See log 

### Expected behavior

[Android] Not implemented: Window.select_folder_dialog()

### Screenshots

![image](https://user-images.githubusercontent.com/105379721/224472929-b2d440e7-87a9-449d-8214-7a368243dc0e.png)

### Environment

- Operating System: Windows 11
- Python version: 3.10.6
- Software versions:
  - Briefcase: 0.3.13
  - Toga: 0.3.0

### Logs

```
03-11 07:59:02.231 11776 11776 I python.stdout: [Android] Not implemented: Window.select_folder_dialog()
03-11 07:59:02.231 11776 11776 D MainActivity: onOptionsItemSelected() complete
```

**Comment by proneon267** [comment]
As the error indicates, that function is currently not implemented for Android. 

See Pull Request: [https://github.com/beeware/toga/pull/1158](https://github.com/beeware/toga/pull/1158)
See issues: [https://github.com/beeware/toga/issues/1171](https://github.com/beeware/toga/issues/1171)

**Comment by rem3228** [comment]
> As the error indicates, that function is currently not implemented for Android.
> 
> See Pull Request: #1158 See issues: #1171

Thanks for the answer. Is this solution? Where to get these libraries? Pip doesnt find them.
```
from com.chaquo.python import Python
from java import jclass

Intent = jclass('android.content.Intent')

context = Python.getPlatform().getApplication()  # Could also be widget.app._impl.native
fileChose = Intent(Intent.ACTION_GET_CONTENT)
fileChose.addCategory(Intent.CATEGORY_OPENABLE)
fileChose.setType("text/plain")
results = await widget.app._impl.intent_result(Intent.createChooser(fileChose, "Choose a file"))
data = results['resultData'].getData()
bytesJarray = bytes((context.getContentResolver().openInputStream(data).readAllBytes()))
```

**Comment by mhsmith** [comment]
You don't need to install any additional libraries: those imports are from Chaquopy, which is installed automatically on Android.

**Comment by rem3228** [comment]
Ok thanks everyone for the help
