### ISSUE TITLE
Add a `clear()` method to remove all children

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1828]
### What is the problem or limitation you are having?

At present, you can:
* add a single child to a widget (`widget.add(child)`)
* remove a single child to a widget (`widget.remove(child)`)
* add multiple children to a widget in a single call (`widget.add(child1, child2)`)
* Remove multiple children from a widget in a single call  (`widget.remove(child1, child2)`)

However, there is no API to remove *all* children from a node.

### Describe the solution you'd like

`widget.clear()` should remove all children from a widget. As of Travertino 0.2.0, a `clear()` API exists; however, invoking it could have unexpected consequences, as it doesn't include the Toga-side cleanups implied by this change.

### Describe alternatives you've considered

`widget.remove(*widget.children)` is a workaround at present, but isn't a great API.

**Comment by malikoth** [comment]
I'd like to tackle this!  #pyconsprints2023
