### ISSUE TITLE
Add support for custom fonts on remaining platforms

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1837]
### What is the problem or limitation you are having?

The Toga interface allows for the addition of user-provided TTF files as a font declaration. However, this interface is currently only implemented on Windows and Android.

### Describe the solution you'd like

An implementation of custom font handling on GTK, Cocoa, iOS and Web.

### Describe alternatives you've considered

The status quo doesn't *break* anything, but it also doesn't give full flexibility to the user.

**Comment by freakboy3742** [comment]
@LunaMeadows has been investigating what is needed on Linux/GTK, and has found that the fontconfig library is likely a key part of the puzzle. fontconfig exposes gobject bindings... but they are woefully incomplete. Barely exposing the configuration interface, and not exposing the APIs needed to load/register fonts. This is how far they've gotten in building and updated set of GI bindings for FontConfig.

https://gist.github.com/LunaMeadows/eb7cea8d4797eabd5fd5171dc182df81

**Comment by mhsmith** [comment]
This is implemented for GTK in #1903, and for Cocoa in #1399. iOS has not yet been started.
