### ISSUE TITLE
On Enter option for text inputs

### ISSUE THREAD

**Issue by LunaMeadows** [beeware/toga#1844]
### What is the problem or limitation you are having?

Currently there is no way to detect when a user presses the enter key. There are many implementations where this could be useful instead of having to have a user type in the text input and then use a button to do a task. 

### Describe the solution you'd like

An on_enter option similar to on_click that the button has. It may also be useful to allow the specification of if the enter key should be consumed or not. This could still be handled by just setting the text input to the active object in the method called but may be nice to have as just on option.

### Describe alternatives you've considered

Using pynput or keyboard would work on desktop systems but they do not seem to work on at least android devices for different reasons. 

### Additional context

https://github.com/LunaMeadows/toga/tree/on_enter-branch This branch has the textinput files and the view.py file in android edited to allow for an on_enter key press for android devices.

**Comment by freakboy3742** [comment]
From a design perspective "on_enter" could be interpreted as "when focus enters"; the key in question is also labeled "return" on many keyboards. We may want to rethink the specific "on_enter" naming. However, the general pattern of catching a "confirmation" keypress on TextInput would definitely be worthwhile.

**Comment by freakboy3742** [comment]
Fixed by #1880.

**Comment by coolcoder613eb** [comment]
What about other platforms, like macOS?

**Comment by freakboy3742** [comment]
This feature has been implemented on all platforms except web. It will be available in the next release.
