### ISSUE TITLE
readonly value of MultilineTextInput for iOS is inverted

### ISSUE THREAD

**Issue by o-fedorov** [beeware/toga#1859]
### Describe the bug

For iOS, `readonly=False` makes `MultilineTextInput` read-only.  `readonly=True` makes it editable.

### Steps to reproduce

1. Build the multilinetextinput example for iOS: <https://github.com/beeware/toga/tree/main/examples/multilinetextinput>. Optionally, add `print(self.multiline_input.readonly)` to some places, like `startup` method, or in `readonly_toggle_pressed` before and after the change.
2. Launch the app.
3. Note that at startup the input is not editable.  If there is a `print` statement, it outputs `False`.
4. Click on `"Toggle readonly"`.  The input is now editable, and `print(self.multiline_input.readonly)` will return `True` after the toggle is executed.

### Expected behavior

By default (when `readonly` parameter is not provided to `MultilineTextInput`, it should be editable.  Setting `multiline_input.readonly` to `True` should make it read-only. Settign it to `False` should make it editable.

### Environment

- Operating System: iOS, "iPhone 14"
- Python version: 3.8
- Software versions:
  - Briefcase: 0.3.13
  - Toga: 0.3.0

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report - a fairly obvious mistake (and fix). We should be auditing MultilineTextInput in the near future; but if you want to submit a PR, we'd be happy to merge it.

**Comment by o-fedorov** [comment]
@freakboy3742 done
