### ISSUE TITLE
Add a Toga.SimpleApp base class

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1870]
### What is the problem or limitation you are having?

Toga.App includes a number of features that may not be desirable on all apps. 

On Windows and GTK, the main window of a Toga app includes a menubar.

On iOS and Android, the main window contains a titlebar.

The titlebar provided by the web backend may also be undesirable in some situations.

### Describe the solution you'd like

Toga should offer a `Toga.SimpleApp` base class that only includes the bare minimum of decorations.

`SimpleApp` should not support menus or toolbars. It should not draw a titlebar on its main window. Any commands that are registered should only be accessible as keyboard shortcuts.

`Toga.App` should subclass `Toga.SimpleApp` to add these additional features.

The MainWindow instantiated by the app may also need a "Simple" variant.

### Describe alternatives you've considered

Provide a formal API to turn off menus, toolbars etc on a feature-by-feature basis. This is problematic because of platforms like macOS, where menus are non-optional.

### Additional context

#733 was an original request for this feature.

**Comment by Jzhenli** [comment]
Hi, what's the status for this feature?

**Comment by Jzhenli** [comment]
> It's waiting for an implementation. It's not on the short term roadmap of the core team, but if someone were to provide an implementation, it would get reviewed, and if the review was positive, merged into main.
 
this issue have been closed, so now we can remove the title bar for android app?  if can, would u give brief example? thanks.
![image](https://github.com/user-attachments/assets/185ba05f-c091-4256-ab50-f6a370b766ab)

**Comment by freakboy3742** [comment]
It's been fixed in the main branch, but isn't in a stable release yet. 

As for how to use it - when you set the main window, use an instance of `toga.Window`, not `toga.MainWindow`. See [the SimpleApp example](https://github.com/beeware/toga/blob/main/examples/simpleapp/simpleapp/app.py) for usage (noting again that you will need to use the *git* version of Toga to have this feature, not just the version you get from `pip install toga`)

**Comment by Jzhenli** [comment]
> It's been fixed in the main branch, but isn't in a stable release yet.
> 
> As for how to use it - when you set the main window, use an instance of `toga.Window`, not `toga.MainWindow`. See [the SimpleApp example](https://github.com/beeware/toga/blob/main/examples/simpleapp/simpleapp/app.py) for usage (noting again that you will need to use the _git_ version of Toga to have this feature, not just the version you get from `pip install toga`)

@freakboy3742 how to install the git version?
