### ISSUE TITLE
Window without `on_close` handler can't be closed with the window decoration

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#1872]
### Describe the bug

If a window is defined without an `on_close` handler, The close button (X or red button on the window frame) cannot be used to close the window

### Steps to reproduce

1. Run the `windows` example
2. Click on the "create windows" button
3. Try to close the window with "no on_close handler"

The window should, but will not close. There are no errors or log messages.

Programmatically invoking `window.close()` *does* work.

### Expected behavior

The window should close.

### Environment

- Operating System: Windows, macOS, Linux
- Python version: All
- Software versions:
  - Toga: 0.3.1

### Additional context

As a workaround, adding `on_close=lambda w: True` to the window will allow it to close.

This is likely caused by 0d9d43a from #1833.

**Comment by mhsmith** [comment]
Overlaps with #1714.

**Comment by freakboy3742** [comment]
There may be some conceptual overlap, but this is a specific regression in the `on_close` handler; this functionality worked in 0.3.0. #1714 is new (albeit definitely required) functionality.
