### ISSUE TITLE
DetailedList showing empty rows

### ISSUE THREAD

**Issue by alexcg1** [beeware/toga#1920]
### Describe the bug

Using Toga for the first time, trying to add `DetailedListBox` to my window. *Something* shows up in the box that contains the `DetailedListBox`, but it just looks like a single empty list cell. `on_select` confirms that it's a list cell.

### Steps to reproduce

Run this code:

```python
import toga
from toga.style.pack import Pack

history_data = [
    {
        'icon': toga.Icon.DEFAULT_ICON,
        'title': 'Foo',
        'subtitle': 'Bar',
        'pk': 100,
    },
]


def build(app):
    history = toga.DetailedList(
        id='foo',
        data=history_data,
        on_select=selection_handler,
    )

    history_box = toga.Box()
    history_box.add(history)

    box = toga.Box(style=Pack(padding=(5, 5)))

    box.add(history_box)

    return box


def main():
    return toga.App('DetailedList test', 'foo.bar', startup=build)


def selection_handler(widget, row):
    print('Row {} of widget {} was selected'.format(row, widget))


if __name__ == '__main__':
    main().main_loop()
```

### Expected behavior

A populated listbox shows up

### Screenshots

![image](https://user-images.githubusercontent.com/4182659/235446971-06292534-f8c3-4292-9dec-540a19f54f3f.png)

### Environment

- Operating System: Manjaro Linux
- Python version: 3.10
- Software versions:
  - Briefcase:
  - Toga: 0.3.1
  - ...

### Logs

```

```

### Additional context

- If I add other stuff to `box`, that stuff renders fine
- No matter how many rows I add in list, always seems to render just one empty cell

**Comment by LunaMeadows** [comment]
Looking into this, and looks like a temporary fix is setting a width for the detailed list manually makes it show the items in the list.

**Comment by alexcg1** [comment]
Fantastic, thanks @LunaMeadows !
