### ISSUE TITLE
Image View in Box

### ISSUE THREAD

**Issue by KyucraftV2** [beeware/toga#1923]
### Describe the bug

When you create an image_view, put this in a Box and put this box in main_window. The image doesnt appear.
I have this code : 
```
#Testing add image
self.box1 = toga.Box(style=Pack(direction=COLUMN))
image = toga.Image(r"resources\img.png")
image_view = toga.ImageView(id='view1', image=image)
self.box1.add(image_view)
self.mainBox.add(self.box1)

#Create the main window
self.main_window = toga.MainWindow(title=self.formal_name)
self.main_window.content = self.mainBox
self.main_window.show()
```

But if on the line `self.mainBox.add(self.box1)`, I have `self.mainBox.add(image_view)`, the image appear

### Steps to reproduce

1. Use the code
2. Run the app
3. See the image doesnt appear

### Expected behavior

Normally the image needs to appear when its in a box like if the image is not in box.

### Environment

- Operating System: Windows
- Python version: 3.8
- Software versions:
  - Briefcase: 0.3.14
  - Toga: 0.3.1

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report. 

I'm fairly certain this will turn out to be a layout issue. Image is a weird widget at present in that it doesn't enforce a minimum size constraint, so I suspect what is happening here is that the Image is collapsing to 0 size. I think the immediate workaround will be to add a fixed height and width (or a flex=1) to the style definition for the image; the longer term fix will be to ensure that there's a default intrinsic size derived by the size of the image itself.

**Comment by KyucraftV2** [comment]
Okey thanks a lot, when i fix the height and width it works, but with the flex=1 it doesnt work
