### ISSUE TITLE
Getting which platform Toga is running on when using emulator

### ISSUE THREAD

**Issue by gaiamolinaro** [beeware/toga#1934]
### What is the problem or limitation you are having?

I am developing an app for Android and checking its functionality with an Android emulator. 
I want to verify whether the app is running on Android. 

### Describe the solution you'd like

 Is there a way to check which mode (e.g., windows, mac, Android) the app is running on even when using the emulator?

### Describe alternatives you've considered

I initially used `sys.platform` but this returns "linux" when running the app on the emulator.

**Comment by freakboy3742** [comment]
This isn't strictly a *Toga* concern - it's a feature of the underlying Python implementation. It's also a subject that has been discussed with the CPython core team, and is one of the outstanding issues that needs to be resolved before iOS and Android support is made official in CPython.

At present, `sys.platform` returns "Linux" on Android, which is "technically correct" (the best kind of correct :-), but isn't very helpful from an end-user perspective. Toga provides `toga.platform.current_platform` as an internal representation that will return `android`; however, that won't help you differentiate between physical device and emulator.

On iOS, there's a significant difference between the simulator and physical devices - the simulator has a completely different ABI to a physical device. Recent builds of the BeeWare support package use the `platform` module to provide details of the iOS device, including a `platform.is_simulator()` method to return if the device is a simulator. 

However, on Android, the emulator is running an actual Android OS image on emulated hardware. From the perspective of Android, an emulator is "just another device" - albeit a weird one that is likely running on x86 hardware (depending on your host machine). I'm not sure if there's a meaningful identifier that can be used to identify an emulator at runtime; if there is, then it should probably be integrated into the `platform.is_simulator()` implementation. @mhsmith might be able to provide some ideas about possible workarounds.

However, from Toga's perspective, I'm going to close this feature request, as it's not something that *Toga* should be concerned with or have an explicit API for.
