### ISSUE TITLE
Equivalent of CSS `gap` (padding between children)

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1943]
If you want to add many children to a box with equal spacing between them, you have to add `padding` individually to every child, which is tedious. It would be useful to have something like the CSS [`gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) property, which is applied on the parent, and adds space between all of its children.

**Comment by freakboy3742** [comment]
Definitely agreed that the use case exists. However, I'm generally opposed to making large feature additions to Pack, on the basis that it decreases the incentive to implement the "right" fix, which is to complete the implementation of Colosseum.
