### ISSUE TITLE
Android: use Chaquopy syntax directly

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1980]
The Android native classes are imported into `toga_android.libs`, and then from there into the files that use them. This doubles the amount of editing you have to do to import a new class.

Now that we've been using Chaquopy for 9 months, we might as well switch to using its `import` syntax directly.

At the same time, we can also:
* Remove all other dependencies on the [Rubicon compatibility layer](https://github.com/beeware/briefcase-android-gradle-template/blob/v0.3.14/%7B%7B%20cookiecutter.format%20%7D%7D/app/src/main/python-briefcase/rubicon/java/__init__.py) (there are only a few).
* Move the [Android event loop implementation](https://github.com/beeware/briefcase-android-gradle-template/blob/v0.3.14/%7B%7B%20cookiecutter.format%20%7D%7D/app/src/main/python-briefcase/rubicon/java/android_events.py) from the Briefcase template into Toga itself, similarly to Winforms. 
  * Migrate any open issues as well.

This will not break compatibliity with any Briefcase templates released since the Chaquopy migration: they will provide the Rubicon compatibility layer, but Toga simply won't use it anymore.

However, projects which are using pre-Chaquopy Briefcase templates will break the next time they reinstall their requirements, because the briefcase-template pyproject.toml had no upper limit to its Toga version number at that time. They can work around this by adding an upper limit manually, or by upgrading to a newer version of Briefcase.

The current briefcase-template version does have a limit (`~=0.3.1`), so that will allow us to mark any future incompatible changes to Toga, and this will be the last time we break existing projects in this way.

Related: #1979.

**Comment by freakboy3742** [comment]
FWIW - I'm not overly concerned about compatibility with pre-Chaquopy Briefcase. We're still pre-1.0 on both Toga and Android; I don't think it's unreasonable to expect users to keep on top of changes in both projects when we're still in rapid development.

**Comment by mzdk100** [comment]
I want to know the relationship between Chaquopy and BeeWare. As far as I know, using free Chaquopy directly has a 5-minute running limit, and BeeWare also relies on it. Why is there no such limit?

**Comment by mhsmith** [comment]
Chaquopy has been free and open-source for over a year now, so there's no longer any time limit.

**Comment by mzdk100** [comment]
I see.
Then I have a small question. The value obtained using sys.platform on Android is 'Linux'. How can I obtain the specific platform value ('Android')?

**Comment by freakboy3742** [comment]
`sys.platform` is what the CPython interpreter returns on Android. This has been the subject of some discussion with the CPython core team; it's possible that this might be modified to return `linux-android` at some point in the near future, but at least for now, it will always return `linux`.

If you want to know what platform you're on, Toga provides `toga.platform.current_platform`, which will return `android`.

**Comment by dgmouris** [comment]
Hey I was wondering on the renaming of the imports do you want to essentially move the `JavaClass(...)` (shown below)
https://github.com/beeware/toga/blob/6ad77eba18729d569f21a80687335ab79647f388/android/src/toga_android/libs/activity.py#L6

into the files like so?
https://github.com/beeware/toga/blob/6ad77eba18729d569f21a80687335ab79647f388/android/src/toga_android/app.py#L9

Or would you like them defined in `toga_android/libs/__init__.py`?

**Comment by mhsmith** [comment]
The idea is to get rid of the `libs` package entirely.

For JavaClass, Chaquopy allows standard import syntax, so we can change this:
```
from .libs.activity import MainActivity
```
... to this:
```
from org.beeware.android import MainActivity
```

JavaInterface can also be replaced with a normal `import`, but the `class` statement will have to change slightly. For example, in widgets/button.py we would change this:
```
from ..libs.android.view import OnClickListener

class TogaOnClickListener(OnClickListener):
```
... to this:
```
from android.view import View
from java import dynamic_proxy

class TogaOnClickListener(dynamic_proxy(View.OnClickListener)):
```

**Comment by dgmouris** [comment]
Hey @mhsmith, 

Thank you for the help. I'm just going through these imports and I just wanted to make sure I'm going in the right direction.

For example:
https://github.com/beeware/toga/blob/8d798c69c0dfa27de26c1e2fb295d2b8270779fb/android/src/toga_android/window.py#L4-L9

Would become the following:
```python
from android import R
from android.view import ViewTreeObserver

from .container import Container


class LayoutListener(dynamic_proxy(ViewTreeObserver.OnGlobalLayoutListener)):
```
(I have it in a branch here https://github.com/dgmouris/toga/blob/5ec3edd2533de10b1665bfc9190f4c8a481d5c37/android/src/toga_android/window.py#L5-L11)

Thanks for your time.

**Comment by mhsmith** [comment]
Yes, everything on that branch looks fine so far. Please create a draft PR so we'll be notified of your progress.

You can test your changes using the testbed app as shown [here](https://toga.readthedocs.io/en/latest/how-to/contribute-code.html#running-the-testbed). For example, after updating box.py, you can run:
```
cd testbed
briefcase run android --test -- tests/widgets/test_box.py
```

There are tests in the main branch for every class except Canvas, Window and App. I'm working on Canvas today, and I'll be working on Window and App next week. Although, every widget tests Window and App indirectly, so you can still use the testbed to verify them.

**Comment by dgmouris** [comment]
Thanks @mhsmith I'll be testing all of the changes today, and noting the pieces that have no tests around it.

Much appreciated for the help on this.
