### ISSUE TITLE
Update Documentation (For DetailedList, etc.)

### ISSUE THREAD

**Issue by volxage** [beeware/toga#2013]
### What is the problem or limitation you are having?

I had to dig through the source code in order to realize that you could address the ListSource directly to append and remove rows. This wasn't so bad because the source code was very readable, but there's no mention of the member functions associated with ListSource anywhere in the documentations. I think many users of toga will eventually need to know about this capability.

### Describe the solution you'd like

I'd like for there to be an extra section in the docs for objects like the ListSource.

### Describe alternatives you've considered

A separate documentation site might be better to keep the existing site simple.

**Comment by freakboy3742** [comment]
The documentation for ListSource will be fixed by #1955; you can find a preview of the docs page [here](https://toga--1955.org.readthedocs.build/en/1955/reference/api/resources/sources/list_source.html).
