### ISSUE TITLE
(GTK) Changing DetailedList's Source makes rows invisible

### ISSUE THREAD

**Issue by volxage** [beeware/toga#2026]
### Describe the bug

Assigning data to a DetailedList works at first, but reassigning the data always causes the rows to become small and "invisible" (no data is visible on them). By hovering the mouse over them you can still select them, and the correct number of rows are present, but the DetailedList is still unusable in that state because of its appearance.

### Steps to reproduce

```
import toga
from toga.style import Pack

list1 = [{"title" : str(n), "subtitle": "sub", "icon" : None} for n in range(30)]
list2 = [{"title" : str(n), "subtitle": "sub", "icon" : None} for n in range(30,60)]

def build(app):
    box = toga.Box()
    dl = toga.DetailedList(style=Pack(flex=1), on_select=on_sel)
    dl.data = list1
    box.add(dl)
    return box

def on_sel(widget, row):
    widget.data = list2

def main():
    return toga.App("First App", "org.volxage", startup=build)

if __name__ == "__main__":
    main().main_loop()


```

Running this code, you can see the rows initially render correctly, but after selecting a row the symptoms appear.

### Expected behavior

The data is supposed to be reassigned without causing the rows to be "invisible".

### Environment

- Operating System: Arch Linux
- Python version: 3.11.3-2
- Software versions:
  - Briefcase: (Not applicable) 0.3.14
  - Toga: Latest git commit ([48eaff3](https://github.com/beeware/toga/commit/48eaff3c547c260f438e3c79c9c37a67848fb381))

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report; I'm in the middle of an audit of DetailedList right now, so I'll make sure this is addressed.
