### ISSUE TITLE
win10 vs2019 F5 Debug Breakpoint is invalid, is this related to pydev? So how to turn off ptdev in F5 debug mode

### ISSUE THREAD

**Issue by ufft47** [beeware/toga#2038]
### What is the problem or limitation you are having?

win10 vs2019 F5 Debug Breakpoint is invalid, is this related to pydev?
 So how to turn off ptdev in F5 debug mode

### Describe the solution you'd like

win10 vs2019 F5 Debug Breakpoint is invalid

### Describe alternatives you've considered

Sorry, this question has been bothering me for 2 or 3 weeks, and Google, chat GPT can't find an answer, so I have to come up and ask，
In addition, I wrote a SimpleTogo similar to pySimpleGUI. I think it is really useful for building UI. I will sort it out in a few days

**Comment by mhsmith** [comment]
If this is still a problem, please provide the requested information, and we'll reopen the issue.
