### ISSUE TITLE
toolbar parameter of Window is not used

### ISSUE THREAD

**Issue by NMertsch** [beeware/toga#2043]
### Describe the bug

`Window.__init__(...)` has an unused parameter [toolbar](https://github.com/NMertsch/toga/blob/930f4e386de8535d91fbef3d85f216464d5e4423/core/src/toga/window.py#L43).

As a user, I'd be surprised if I call `Window(..., toolbar=my_custom_widget)` and nothing happens.

### Steps to reproduce

-

### Expected behavior

Either `Window` has no `toolbar` parameter, or it does something.

### Environment

(all)

**Comment by freakboy3742** [comment]
Thanks for the report. This is a little surprising to me - I can only assume it's an artefact of some *very* old history, because toolbars are constructed by Commands, not by passing in any argument to Window.
