### ISSUE TITLE
Scroll container not working at all

### ISSUE THREAD

**Issue by infelicitatis** [beeware/toga#2048]
### Describe the bug

The Scroll container does't work as expected in toga 0.3.1 (newest i can install via pip)

Even when using the  "you put a box in a box" tutorial, the right scroll-container with elements other than a table in in it doesnt work (while the left scroll-container with only a table in it works strangely).

there should be 10 buttons, hello world 0-9, but i can only see hello world 0-5 and cant scroll any further. 
there is a scroll bar, but it shows that there is no room to scroll, when there clearly is.

also when i expand the window on windows, the hello world buttons get visible, but scrolling doesnt work nevertheless.

i tested for win and android

### Steps to reproduce

1. copy code from https://toga.readthedocs.io/en/stable/tutorial/tutorial-2.html
2. run briefcase dev or briefcase build
3. app opens
4. can't scroll in right container

### Expected behavior

can scroll in right container

### Screenshots

![scroll doesnt worktoga](https://github.com/beeware/toga/assets/63267760/6349b41d-2d71-4385-9c1f-22510fa2a49e)

### Environment

- Operating System: eindows / android
- Python version: 3.10.5
- Software versions:
  - Briefcase: 0.3.15
  - Toga:0.3.1
  - ...

### Logs

[helloworld] Starting in dev mode...
===========================================================================
WARNING: Using empty string for missing value in data. Define a 'missing_value' on the table to silence this message
WARNING: Can't find icon icons/brutus; falling back to default icon
WARNING: Can't find icon icons/brutus; falling back to default icon
WARNING: Can't find icon icons/cricket-72.png; falling back to default icon
WARNING: Can't find icon icons/brutus; falling back to default icon

**Comment by freakboy3742** [comment]
Thanks for the report - we've recently done a lot of testing and improvements to ScrollContainer, and this problem was found and fixed as part of #1969. It will be incorporated into the next Toga release (0.3.2)
