### ISSUE TITLE
SplitContainer not expanding correctly.

### ISSUE THREAD

**Issue by chipbeaulieu** [beeware/toga#2060]
### Describe the bug

I create a simple vertical two part split container with a label in each pane. When I run the app and increase the size of the window, the split changes accordingly as expected. However, if I first move the split divider in either direction, and then resize the window, the split divider will first go back to the location it was at start up and then move.

macOS Ventura 13.4.1
MacBook Pro M2 ARM Processor

Code:
```
class Main(toga.App):
    def startup(self):
        self.main_window = toga.MainWindow(title=self.name)

        l = toga.Label("Left",style=Pack(text_align=LEFT,width=100))
        r = toga.Label("Right",style=Pack(text_align=LEFT,flex=1))

        split = toga.SplitContainer()
        split.content = [l,r]

        box = toga.Box()
        box.style.update(direction=COLUMN)
        box.add(split)

        self.main_window.content = box

        self.main_window.show()
```

### Expected behavior

I expect the split divider to start at its current location and move smoothly as the window expands.

### Environment

- Operating System: macOS 13.4.1
- Python version: 3.11
- Software versions:
  - Briefcase:
  - Toga: 0.3.1
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report - I believe this has been fixed recently as part of #1984, which will be in the next Toga release. 

If you're able to reproduce the problem you're seeing on the main branch, let us know; otherwise, I'm going to close this as fixed.
