### ISSUE TITLE
Add API to capture screenshots of windows.

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2062]
### What is the problem or limitation you are having?

As an app developer, it is sometimes necessary to capture the current state of a GUI window as an image. 

The most notable use case is in CI testing, where the screen isn't visible, and test failures are most obvious in their visual presentation; however, there may be some other uses.

### Describe the solution you'd like

1. A new cross-platform `Window.as_image() -> toga.Image` API.

2. As an example of the API in action, modify the `testbed` test harness so that when a widget test fails, a screenshot of the screen is captured and written to the cache directory. 

### Describe alternatives you've considered

Do nothing. Screenshots aren't essential; they're a nice-to-have feature.

### Additional context

* The Canvas widget already has an `as_image()` API, demonstrating how to save a single widget as an image. The Window screenshot API should be almost identical, but applied to the root content widget.
* The Canvas GUI tests already have tests that write the `as_image()` representation to disk if the canvas hasn't rendered correctly. 
* It should be possible to catch a failed test in the teardown of the `widget_probe()` fixture of `testbed`; if an AssertionError is raised during the `yield`, that will be a test failure; if this occurs, take a screenshot of the window/screen, write to the app cache folder, and re-raise the assertion (so that it is picked up by Pytest).

**Comment by dr-gavitron** [comment]
Implemented that in toga-gtk. Facing problem in WinForms. To make things simple, `pygetwindow` library is needed... Where to add that dependency for Windows only?

**Comment by freakboy3742** [comment]
@dr-gavitron If you read back to the tickets that are linked to this one, there's already an implementation of this on all platforms as part of #2103.
