### ISSUE TITLE
Add API to capture screenshots of desktop/screen

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2063]
### What is the problem or limitation you are having?

As an app developer, it is sometimes necessary to capture the current entire desktop state of a GUI as an image. 

The most notable use case is in CI testing, where the screen isn't visible, and test failures are most obvious in their visual presentation; however, there may be some other uses (e.g., an actual "screenshot" app)

### Describe the solution you'd like

1. A cross-platform API to capture an image of the full screen. 

2. As an example of the API in action, modify the `testbed` test harness so that when a test fails, a screenshot of the screen is captured and written to the cache directory. 

### Describe alternatives you've considered

Do nothing. Screenshots aren't essential; they're a nice-to-have feature.

### Additional context

* See #2062 for a similar feature at the level of a Window.
* The API proposed in #1930 provides an entry point for accessing screens; based on that API, `App.screens[n].as_image()` would seem a logical API.
* The Canvas GUI tests already have tests that write the `as_image()` representation to disk if the canvas hasn't rendered correctly. 
* It should be possible to catch a failed test in the teardown of the `window_probe()` and/or `app_probe` fixtures in `testbed`; if an AssertionError is raised during the `yield`, that will be a test failure; if this occurs, take a screenshot of the window/screen, write to the app cache folder, and re-raise the assertion (so that it is picked up by Pytest).

**Comment by proneon267** [comment]
Since, #1930 is merged, I think this can be closed.

**Comment by freakboy3742** [comment]
Agreed - thanks for the housekeeping!
