### ISSUE TITLE
Add more styles and events for the button

### ISSUE THREAD

**Issue by leaffeather** [beeware/toga#2077]
### What is the problem or limitation you are having?

Currently it seems that toga on Android platform could not support multi-windows. And it is said that the OptionContainer is not compatible with mobile OSs. It limits the separation of different functions to a large extent. It is neither intuitive nor beautiful enough to distinguish different function regions in a way of using buttons with simple color or text style distinctions

### Describe the solution you'd like

In order to enhance user experience and consider the current available widgets, I think the coordination between buttons and boxes can realize the relatively similar effect of the tab. However, the current button style is not enough to satisfy the modern UI design for applications. 

### Describe alternatives you've considered

I suggest that the button should add the following styles and events. The suggestion is also useful to other widgets but such functions working on the button is obviously more urgent and important. 
1. Add the underline style of the text. 
2. Hide the border (someone has already submitted) or further specify which sides should be hidden. Or in a different way, add an image button (someone has already submitted as well) or add an on_press event for the label (if so, the border control of the label would become more vital). This also means that it is best to adjust the thickness of the border.
3. Add an event to response when the mouse cursor stops on the button on desktop OSs and a long press is on it on mobile OSs
4. If possible, like in HTML, we could finally directly customize any styles of the button by the CSS script. For example, gradient colors and various animation effects.

**Comment by freakboy3742** [comment]
Closing on the basis that this proposal is fundamentally in conflict with [Toga's design philosophy](https://toga.readthedocs.io/en/stable/background/philosophy.html).

In Toga, Buttons are intentionally designed to follow the HIG of the platform they're on. If you don't like the way buttons look on your platform, take that up with your operating system manufacturer, pick a different operating system, or pick a different GUI toolkit. 

As for ImageButton - that's a long standing feature request (#774), and one that has been discussed *extensively* (see the discussions and issues linked to that ticket). It's waiting for someone to implement that feature. The solution will *not* be to add "on_press" notifications to label.

**Comment by mhsmith** [comment]
@leaffeather: If what you're actually trying to achieve is an OptionContainer on Android, then we would probably accept a PR which implements it using a [bottom navigation bar](https://m2.material.io/components/bottom-navigation).

**Comment by mhsmith** [comment]
Or [tabs](https://m2.material.io/components/tabs) would be even better actually, since they allow an unlimited number of items and they don't require icons.
