### ISSUE TITLE
ImageView does not work properly on GTK

### ISSUE THREAD

**Issue by Hikari1026** [beeware/toga#2084]
### Describe the bug

When using ImageView to display an image inside a box, the image is not shown (even though i can see a small 1x1 white pixel). Kind of duplicate of [#1923] except that setting width and height as pointed out in the mentioned issue does not work. However this should be a GTK error as the image is shown correctly on Android.

```
main_box = toga.Box(style=Pack(direction=COLUMN))
my_image = toga.Image(self.paths.app / 'helloworld.png')
view = toga.ImageView(my_image, style=Pack(width=400, height=400))
main_box.add(view)

self.main_window = toga.MainWindow(title=self.formal_name)        
self.main_window.content = main_box
self.main_window.show()
```

### Steps to reproduce

1. Run the app with the provided snippet

### Expected behavior

The provided image should appear

### Environment

- Operating System: Arch Linux
- Python version: 3.8.17 (I've also tried 3.11.3)
- Software versions:
  - Briefcase: 0.3.15
  - Toga: 0.3.1

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report - the main branch contains a number of significant changes to ImageView (and a number of other widgets); are you able to reproduce this with that version, rather than 0.3.1 stable? I'd test myself, but I'm currently on the road and don't have access to my Linux test machine.

**Comment by Hikari1026** [comment]
I've tested the main branch and it works as intended. Thank you for the quick reply and for the amazing work!
