### ISSUE TITLE
textinput.readonly bug on Android

### ISSUE THREAD

**Issue by Nana-Chans** [beeware/toga#2105]
### Describe the bug

Set textinput.readonly True, then set textinput.readonly to False, but it's not able to be modified on Android.

### Steps to reproduce

1. self.text = toga.TextInput()
2. self.text.readonly = True
3. self.text.readonly = False

### Expected behavior

It can be modified

### Environment

- Operating System: win10
- Python version: 3.8
- Software versions:
  - Briefcase: 0.3.15
  - Toga: 0.3.1
  - ...

### Logs

```

```

**Comment by mhsmith** [comment]
This has probably been fixed in the development version of Toga. Try editing your pyproject.toml file to replace `toga-android` with the following:
```
    "git+https://github.com/beeware/toga@237ccee#subdirectory=core",
    "git+https://github.com/beeware/toga@237ccee#subdirectory=android",
```

Then run `briefcase run android -ur`.
