### ISSUE TITLE
CI is failing in my fork

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#2111]
### Describe the bug

After a long time that I did not touch anything Beeware-related, I updated my main branch and merged it to my main branch in my fork. 

Unfortunately, it caused the CI to fail on the main branch, and I haven't understood why.
You can see the CI status [here](https://github.com/saroad2/toga/actions/runs/6089352773/job/16522571428).

I appreciate your help!

### Steps to reproduce

Any rerun of the CI process causes it to fail.

### Expected behavior

CI should finish successfully in the main branch.

### Environment

- Operating System: all
- Python version: Python 3.10
- Software versions:
  - Briefcase:
  - Toga: latest
  - ...

### Logs

```

```

**Comment by mhsmith** [comment]
Toga now uses setuptools-scm to automatically generate version numbers from Git tags. So you'll need to pull the tags from the main repository into your fork.

**Comment by saroad2** [comment]
You're right. That worked! Thank you.
