### ISSUE TITLE
Suggest improving the type prompts for toga libraries.

### ISSUE THREAD

**Issue by mzdk100** [beeware/toga#2121]
### Describe the bug

I used pycharm for development, but found that some writing methods do not have available code prompts.
For example, there is no code prompt related to "toga.App" after entering "main_window.app." This is because in toga's window.py, the app attribute of the Window class does not provide a type prompt:
class Window
    ...
    self._app = None
    ...
Suggest changing to:
class Window
    ...
    self._app: "toga.app.App" = None
    ...

### Steps to reproduce

In the pycharm editor.

### Expected behavior

Improve some types of prompts, such as entering:
'main_window.app.'can display code prompts such as 'add_background_task()', 'formal_name', etc.

### Environment

- Operating System:
- Python version:
- Software versions:
  - Briefcase:
  - Toga:
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
We're in the middle of adding type annotations to all our code, specifically to assist IDEs and to provide documentation. The current main branch has *almost* complete type annotations, with a couple more PRs pending that will bring even more type annotations. These will all be in the next Toga release.

On that basis, I'm going to close this ticket as already complete.
