### ISSUE TITLE
Allow capturing Enter key in input box

### ISSUE THREAD

**Issue by treyhunner** [beeware/toga#213]
I'm not sure what the best API for this is.

`on_press` makes sense for buttons, but there are multiple ways the Enter key could be handled in input boxes.

We could capture a keypress event or we could capture an enter key specifically.

Thoughts on a good API for capturing this?

**Comment by freakboy3742** [comment]
Agreed this is something that should be captured. My initial suggestion would be that an `on_enter` handler should exist so users can catch this class of input; but I'm open to other suggestions.

**Comment by ydocsgnillats** [comment]
I'd like to help out with this if it's still open!

**Comment by freakboy3742** [comment]
@ydocsgnillats Absolutely! We should probably take this opportunity to think about the overall design of the signals that TextInput could meaningfully generate:

 * content has changed by a single character
 * widget has lost focus
 * widget has lost focus by pressing enter (is this the same as the previous one?)
 * anything else?

**Comment by ydocsgnillats** [comment]
I may also need some help being pointed in the right direction. I like the idea of an on_enter handler. What is the relevant file I should be adding this to? The only other thing I could think of that may be relevant to the TextInput signals may be for some kind of active validation(i.e. matching email address confirmation, checking for valid email address as it's typed), but that may be out of the scope of this or not necessary.

**Comment by saroad2** [comment]
Adding validations is actually a pretty cool idea (maybe wrapping the text box with a red border and displaying an error messages). 

As for directions, First you should go to *src/core/toga/widgets/textinput.py* and implement the ability as an **interface**.
Then, go to *src/{my_computer_platform}/toga/widgets/textinput.py* and add the **implementations** of the ability for your operating system.
Lastly, go to the *examples* folder and add an example of the ability (it is best to add it to an existing example).
You may have to add `not_implemented` messages to the other platforms, but I would help you do that if you'll have any problems with that.

I hope this helps, and if you need anything else, please feel free to ask further questions here.

**Comment by freakboy3742** [comment]
I believe this was addressed as part of the validators and focus handling API changes.

**Comment by shula** [comment]
That's a broader issue:

Many control ("out there in the world") expect ESC or ENTER to do stuff.
typically these are not handled by the O.S.

e.g. 
When A DetailedList item is focused, ENTER key will act on that item;
ESC key is de-facto for "cancel", "disable", "clear" or for many situations.
TAB usage can be behave in 2 different ways in a multiline text edit control.
In a mobile device with external keyboard, ENTER and ESC are the only means to control the app.

Can we take control over these k"special" keypresses? in every control?

**Comment by freakboy3742** [comment]
> That's a broader issue; we discussed it previously.

Discussed what, where?
 
> I'll just mention the DetailedList: When an item is focused, I want to perform action by pressing ENTER on that item;

This issue is about TextInput, and handling Enter as an acceptance. If you have a feature request about DetailedList, please open a new issue.

**Comment by mhsmith** [comment]
Continued in #2705.
