### ISSUE TITLE
Document the testbed/probe architecture

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2137]
### What is the problem or limitation you are having?

We now have a test suite that is nearing 100% code coverage of the platform backends. However, the architecture of this testbed isn't obvious until you know what is going on. This is an impediment to contributors adding new features.

### Describe the solution you'd like

We should add an architectural explainer about the test backend. This would be a background document, similar to the one explaining [the "three layers" architecture](https://toga.readthedocs.io/en/stable/background/architecture.html).

### Describe alternatives you've considered

No real alternative here, other than hoping contributors work out what is going on by osmosis.

### Additional context

I recently [wrote up a 10c version of this](https://github.com/beeware/toga/pull/2130#issuecomment-1736443774) in response to someone asking how to test a new feature, and the very next ticket I responded to needed a link to that description. If that isn't a cry for documentation, I don't know what is.

**Comment by freakboy3742** [comment]
This probably doesn't need to be a completely separate document - it could be another section on the existing architecture guide. This should probably also cover what the core tests cover in comparison to what the testbed tests cover.

**Comment by mhsmith** [comment]
I think you've already done this at https://toga.readthedocs.io/en/latest/how-to/contribute-code.html#how-the-testbed-works.

**Comment by freakboy3742** [comment]
🤦 

Thanks past Russell, you've saved me some work :-)
