### ISSUE TITLE
Let’s draw on a canvas! tutorial text doesn't fit in the box

### ISSUE THREAD

**Issue by bcraigie** [beeware/toga#2164]
### Describe the bug

![tiberius_does_not_fit](https://github.com/beeware/toga/assets/18425507/d47be667-f1a5-4ed3-b881-0e6bb74e3d3d)

You'll see from the image, produced from the tutorial code (without any changes), running on Windows 11, the word Tiberius doesn't fit in the box.

### Steps to reproduce

1. Go to https://toga.readthedocs.io/en/stable/tutorial/tutorial-4.html
2. Copy the full code (after here's the source code)
3. paste it into a file
4. run the file in Python

### Expected behavior

The text should fit in the box.

I can fix it by changing these lines:

```
88      # x = 32
88      x = 28

93     # rect_stroker.rect(x - 2, y - height + 2, width, height + 2)
93       rect_stroker.rect(x - 2, y - height, width + 12, height + 4)
```

But it seems to me that the self.canvas.measure_text isn't getting the correct text size.  You'll see I had to add 10 to the width and 2 to the height, and nudge the text down and the box left.

It would also be nice to add a bit of left and right padding so the horns are not right up against the edges, and it would be interesting for the Toga novice such as myself to see how to do that too - I tried but couldn't figure it out. :-)

### Screenshots

Screenshot after applying small tweaks.

![tiberius_now_fits](https://github.com/beeware/toga/assets/18425507/9e5380e9-b9d6-4c95-a77b-99913dc0da5f)

### Environment

- Operating System: Windows 11
- Python version: 3.9.7
- Software versions:
  - Briefcase:
  - Toga: 0.3.1
  - ...

### Logs

```

```

**Comment by mhsmith** [comment]
This bug has been fixed in the development version of Toga. Until that's released, you can use it by installing the following requirements with pip:

```
    "git+https://github.com/beeware/toga#subdirectory=core",
    "git+https://github.com/beeware/toga#subdirectory=winforms",
```

Or if you're using Briefcase, edit your pyproject.toml file to replace `toga-winforms` with those lines, then add the `-r` option next time you run `briefcase dev` or `briefcase run`.

> It would also be nice to add a bit of left and right padding so the horns are not right up against the edges, and it would be interesting for the Toga novice such as myself to see how to do that too - I tried but couldn't figure it out. :-)

The simplest way would be to edit the MainWindow `size` to make it a bit wider, than make a `translate` call on the Canvas to shift the image sideways.
