### ISSUE TITLE
pytest-freezegun produces warnings in core tests

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#2171]
Every time you run the core tests, you get this warning:
```
../../../../.venv/bw-38/lib/python3.8/site-packages/pytest_freezegun.py:17
  /Users/msmith/.venv/bw-38/lib/python3.8/site-packages/pytest_freezegun.py:17: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):
```

This was reported 2 years ago (https://github.com/ktosiek/pytest-freezegun/issues/35), but has received no response from the maintainer. The project itself has had no commits in over 3 years.

We should replace pytest-freezegun, either with pytest-freezer (https://github.com/ktosiek/pytest-freezegun/issues/44), or with simple [pytest monkeypatches](https://docs.pytest.org/en/7.1.x/how-to/monkeypatch.html).

**Comment by freakboy3742** [comment]
Ugh - I've seen that one go past, but hadn't investigated the cause. 

Avoiding the dependency entirely would always be my first preference, but monkeypatching time functions is very difficult to get right, so I think I library is probably warranted. Given pytest-freezer is being maintained by the core pytest project, that seems like a reasonably safe option.
