### ISSUE TITLE
Is there any sensors related api in toga on Android?

### ISSUE THREAD

**Issue by cycleuser** [beeware/toga#2183]
### What is the problem or limitation you are having?

For mobile devices like Android phones or pads, the sensors such like the gravity and acceleration can be really useful.
Is there any supports on reading the sensors from Android hardware? 

### Describe the solution you'd like

Reading sensors from Android devices would be really cool and distinguished from desktop operating systems.
Besides, using camera and microphone on Android would be even more awesome.

### Describe alternatives you've considered

Years ago, kivy used to offer these in some degree.
But personally speaking, I think the usage of kivy is too painful.
Hope toga gonna be a much better alternative.

**Comment by freakboy3742** [comment]
Right now, there isn't any *cross platform* support for device sensors in Toga's API. This is on our TODO list; we're hoping to add the first of these APIs over the rest of this year.

In the meantime, you can access any native capability (including sensors) by writing directly against the native platform API. On Android, that means using the [Chaquopy API](https://chaquo.com/chaquopy/doc/current/python.html); on iOS, that means the [Rubicon ObjC API](https://rubicon-objc.readthedocs.io/en/stable/). You'll also need to manually modify any app permissions that might be required.
