### ISSUE TITLE
Copy what's in Briefcase's docs

### ISSUE THREAD

**Issue by ahonnecke** [beeware/toga#2187]
<SNIP>
As for toga-chart's documentation, it probably wouldn't hurt to copy what's in Briefcase's docs....although, it looks like the docs here could use a little TLC; for instance, I see a reference to Python 3.5 and it isn't using the [furo](https://github.com/pradyunsg/furo) theme.

_Originally posted by @rmartin16 in https://github.com/beeware/toga-chart/issues/61#issuecomment-1791393232_

**Comment by freakboy3742** [comment]
Toga-chart barely has *any* documentation, so... yes, there are updates required. :-) 

However, this issue has been raised against the *Toga'* repository, and Toga's docs *do* have [much of the same contributor documentation that Briefcase has](https://toga.readthedocs.io/en/latest/how-to/index.html), customised for Toga's needs.
