### ISSUE TITLE
Input Event Listener

### ISSUE THREAD

**Issue by IagoBeuller** [beeware/toga#2245]
### What is the problem or limitation you are having?

Toga is missing this feature, that can be used to do a lot of things, such as custom widgets.
Is missing on_hover/on_enter and on_leave as well, but these were already asked for.

### Describe the solution you'd like

Window.on_key_press
Window.on_key_released
Window.on_mouse_move -> x, y, dx, dy
Window.on_text

### Describe alternatives you've considered

Canvas.on_key_pressed
Canvas.on_key_released
Canvas.on_mouse_move -> x,  y, dx, dy
Canvas.on_text

**Comment by freakboy3742** [comment]
It's not clear to me how adding key/mouse events to *window* will improve the API for writing custom widgets. It's also not clear how adding these to *canvas* is any better - canvas is a vector graphics area, not a set of primitives for drawing new widgets.

It's also not clear to me what "on_text" is meant to do at all.

Can you provide a more concrete example of how "writing custom widgets" will be made easier by having these APIs on Window (or, for that matter, on Canvas)?

Also - to be clear: writing custom widgets is almost explicitly *not* a goal for Toga. As a general rule, Toga aims to wrap platform-specific capabilities, not to provide an API to write cross-platform widgets. Generally speaking, if you need a new widget, the approach will be to write a generic API with platform-specific implemenations. There are some notable examples where that *won't* be the case, but advocating for a new API in Toga to make building custom widgets easier needs to start with some strong examples for why this is desirable *at all*.
