### ISSUE TITLE
Ubuntu 22.04.3 / GTK-Critical issue: gtk_box_gadget_distribute error when refreshing a GUI

### ISSUE THREAD

**Issue by KxuKxu667** [beeware/toga#2247]
### Describe the bug

I am building a rather complex project with Briefcase. Using the Toga framework, I have built a GUI with indicators in the first tab on the main window, and the data is refreshed every second. When the window is visible, every second the console shows this error: 

(__main__.py:7828): Gtk-CRITICAL **: 11:36:41.152: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

This does not show up in MacOS, which is the system I wrote the code on. I'm trying to push the project to Linux and Windows too. I'm a newbie and wrote most of the code using AI, this is too complicated for me to try to debug.

### Steps to reproduce

I will provide more information if needed, at this point I'm afraid I would be sending either too little or too much code.

### Expected behavior

I expected the GUI to refresh quietly as it does on MacOS.

### Environment

- Operating System: Ubuntu 22.04.3 LTS (in a VM)
- Python version: 3.10.12
- Software versions:
  - Briefcase: 0.3.16
  - Toga: 0.4.0

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report - but there's not much we can do without a reproduction case. Unless we have a way to reproduce the problem, there's not much we can do to fix it.

**Comment by KxuKxu667** [comment]
duly noted ! thank you.

**Comment by rmartin16** [comment]
Coincidentally hit this today on pop 22.04:
```python
import toga


class HelloWorld(toga.App):
    def startup(self):
        """Construct and show the Toga application."""
        self.main_window = toga.MainWindow(title="gtk_box_gadget_distribute")
        self.main_window.content = toga.Box(
            children=[toga.ScrollContainer(content=toga.Label("label"))]
        )
        self.main_window.show()


def main():
    return HelloWorld()
```
While Toga's example app for `ScrollContainer` does not cause the error, I was able to reduce my app to what's above and still see the GTK error.

However, this error only happened for me with `0.4.0`....not `main`.

**Comment by KxuKxu667** [comment]
Update: this issue is no longer showing up in the console output.
