### ISSUE TITLE
[Android] JavaScript alert() or prompt() not working on WebView

### ISSUE THREAD

**Issue by Pairman** [beeware/toga#2254]
### Describe the bug

On Android, Toga WebView cannot create dialogs from JS alert() or prompt() in loaded web pages. 

Toga on windows has no issue showing JS alerts or prompts. I cannot test this on Ubuntu since I'm using a headless build server.

### Steps to reproduce

1. Use toga to load a webpage (either local or online, with alert() or prompt() set as onclick attribute of buttons) like this:
```
self.main_window = toga_MainWindow(title = self.formal_name)
                self.main_window.content = toga_Box(
                        children = [
                                toga_WebView(url = "http://127.0.0.1:5001", style = toga_style_Pack(flex = 1))
                        ]
                )
                self.main_window.show()
```
2. Build, package and run on Android.
3. JS alert() or prompt() does nothing when buttons with them as onclick functions are clicked.

### Expected behavior

Alert() or prompt() should create jump boxes / dialogs (with input fields) when executed.

### Environment

- Operating System: Ubuntu 20.04 amd64(build) and Android 13 arm64 (test)
- Python version: 3.10.12
- Software versions:
  - Briefcase: 0.3.16
  - Toga: 0.4.0
  - ...

### Logs
No logs. I'm testing on a real android device.

**Comment by mhsmith** [comment]
This would require implementing the WebChromeClient class, so please subscribe to #1020 for updates about that.
