### ISSUE TITLE
[Feature Request] Markdown Widget

### ISSUE THREAD

**Issue by Heus-Sueh** [beeware/toga#2300]
### What is the problem or limitation you are having?

I would like to show the text made in markdown somehow, but I haven't found any way to do that

### Describe the solution you'd like

a widget capable of rendering markdown text would be pretty cool

here is a flutter widget it might be interesting to see how it was implemented
https://github.com/asjqkkkk/markdown_widget

### Describe alternatives you've considered

another solution would be to perhaps use the webview in some way

### Additional context

none

**Comment by freakboy3742** [comment]
As you've flagged in your "alternatives" discussion - Markdown is a markup language that renders to HTML; a WebView widget can render HTML. A "Markdown widget" is essentially:

```
import markdown
import toga

my_view = toga.WebView()
my_view.set_content(None, markdown.markdown(your_markdown_string))
```

(I'm using the [python-markdown](https://python-markdown.github.io) API here, but any markdown library should have an equivalent).

On that basis, I'm going to mark this WONTFIX; If I've missed some useful feature that a markdown widget should have, let me know and I'm happy to reopen.
