### ISSUE TITLE
Add content argument to MainWindow instantiation

### ISSUE THREAD

**Issue by hyuri** [beeware/toga#2307]
### What is the problem or limitation you are having?

Right now, to create a MainWindow and add content to it, we have to do it in two steps and in a not so elegant way:

```
self.main_window = toga.MainWindow(
	title=self.formal_name
)

self.main_window.content = self.main_box
```

### Describe the solution you'd like

Allow assigning "content" during instantiation of MainWindow as well, so we can do it in one step and more elegantly:

```
self.main_window = toga.MainWindow(
	title=self.formal_name,
	content=self.main_box
)
```

This would be consistent with, for example, ScrollContainer.

### Describe alternatives you've considered

1. Make it consistent with other classes — that use "children" — and use "child" instead:

```
self.main_window = toga.MainWindow(
	title=self.formal_name,
	child=self.main_box
)
```

2. Or keep things as they are, at least until other higher priority tasks are completed, as this is a minor improvement

**Comment by freakboy3742** [comment]
That's an odd inconsistency - I'm surprised I didn't notice this before. Agreed that it's something we should address. 

`content=` would seem the obvious API spelling.

**Comment by Franklin19c** [comment]
Currently working on this at PyCon  Sprints.

**Comment by mhsmith** [comment]
@Cameronsplaze is now looking at this in #2586.

**Comment by Franklin19c** [comment]
I believe that I have everything ready.  I'll submit the PR now.  This is my first PR for any projects like this, and I had limited time at the sprints.  Please don't let me hold anything up.
