### ISSUE TITLE
Add a way to reset widgets to their default values

### ISSUE THREAD

**Issue by hyuri** [beeware/toga#2317]
### What is the problem or limitation you are having?

I'm using a multi-page design where every time the user comes back to the same [already rendered/cached] page, in certain pages, I need the widgets' properties (like Selection.value, Button.enabled, etc.) to reset to their default values. Currently, there's no built-in way to do that, so the only way is to create this functionality from scratch for every app.

### Describe the solution you'd like

Add a .reset() method to Widget, that will restore the widget's properties to their default values (values set during instantiation).

Additionally — and I'm not sure where this one would go — it would be even more helpful to also have a method to reset all widgets in the DOM to their default values, which would essentially call the .reset() method of all nodes in the tree. Perhaps it could be a .reset_children() method in every widget that can have children? This way, we can reset even pages/trees not being currently displayed (not attached to MainWindow).

With these two methods, it would become a piece of cake to reset widgets.

### Describe alternatives you've considered

Not change anything and leave users to figure out their resetting functionality the hard way.

**Comment by freakboy3742** [comment]
I'm not sure I'm convinced that the use case you describe warrants the overhead that would be required to implement it.

To implement a "reset", every widget would need to keep a copy of all data and options passed in as initial values. That's an overhead that *every* widget would need to maintain, just so a handful of users in a handful of cases can potentially call `reset()`.

It may also be expensive, difficult - or possibly even *impossible* - to implement. If a widget is backed by a data store that is populated by API calls, then it may not be possible to "save" the state of the data. That means we'd need to introduce a "persistence" API on data stores, and define behavior when "persistence" can't be implemented.

That then leads to the question of *which* properties should be restored - what if I want to restore the value of the data, but not the enabled status? Or restore enabled, but not visibility? 

Ultimately, my inclination is that if this is something an app needs, it's something the app should implement - persisting the and restoring values that they care about (the "hard way" option you've listed as an alternative). That way, the reset behaviour can match whatever the end-developer needs, and only the developers who need that functionality will need to carry the overhead of that option. 

On that basis, I'm going to close this ticket as WONTFIX. However, I'm open to reopening this if there's a particular groundswell indicating that it would be more useful that it first appears (or at least, more useful than it seems to me).

**Comment by hyuri** [comment]
Good points. Seemed generally useful to me but I'm definitely biased towards my current use case.

Thinking out loud here, before the idea is thrown away: perhaps a way to reduce overhead could be for the copy of the initial values to only be stored if the user explicitly passes "resettable=True"? An "if resettable" would decided on whether to even create the copy variables or not. And, consequentially, the reset function would only do anything if resettable=True, of course.

For the question of which properties to reset, at first thought it seems to me the user could pass them — Button.reset(*args). And the case of simply Button.reset() — absence of *args —, it resets all.

Still, these ideas wouldn't address the example you raised with more complex data attachments.

In any case, definitely low priority, and I'm out of my range here, but maybe someone else can come up with a better case for it like you suggested.

**Comment by freakboy3742** [comment]
If we were going to go down this path, I'd take a different approach - add a "preserve" function that returns the current state of the widget, and a "restore" method that accepts the return value of "preserve". 

This would give you the functionality you require for your use case; but would also provide the primitives needed for a larger scale "app restore", which could be useful for "restore app state on restart" functionality - the sort of functionality that makes apps behave nicely on machine restart, or wake-from-sleep.

That doesn't change the issues with data sources etc - but it's at least an angle on the problem that (a) isn't quite so niche, and (b) doesn't require an overhead on every widget "just in case it's needed". I've opened #2329 to describe this more general feature request.

(And this time, I'll actually press the close button :-) )
