### ISSUE TITLE
parameter "on_confirm" not working in TextInput widget on Windows

### ISSUE THREAD

**Issue by hgf777-br** [beeware/toga#2324]
### Describe the bug

I am getting a Type Error when using this paramenter:

TypeError: TextInput.__init__() got an unexpected keyword argument 'on_confirm'

### Steps to reproduce

try to use this parameter with the TextInput widget.

### Expected behavior

Run a function when I press Enter or Return in a TextInput widget

### Environment

- Operating System: Windows 11
- Python version: 3.11
- Software versions: 
  - Briefcase:  0.3.15
  - Toga: 0.3.1
  - ...

### Logs

```

```

**Comment by rmartin16** [comment]
Please upgrade to version 0.4.1 of Toga; the `on_confirm` argument for `TextInput` was introduced in version 0.4.0.

**Comment by hgf777-br** [comment]
Thank you! I will do that.
