### ISSUE TITLE
I can't change the style while app is running.

### ISSUE THREAD

**Issue by lihuaming07** [beeware/toga#2365]
### Describe the bug

It is normal that button(or some other widgets) will change its own style when some events happen.However, I try many ways and find it unable to make it.

### Steps to reproduce

1. This is my code.
```python
   def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        self.start_button = toga.Button(
            "start",
            style=Pack(background_color='pink'),
            on_press=self.start,
        )
        self.flag = False
        main_box.add(self.start_button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    async def start(self, widget):
        self.data = 'hi'
        await self.diolog(self.data)
        if not self.flag:
            self.flag = True
            self.start_button.style = Pack(background_color="blue")
            self.start_button.refresh()
        else:
            self.flag = False
            self.start_button.style.apply('background_color', 'black')
            self.start_button.refresh()
        print(self.flag)

    async def generate_question(self):
        pass

    async def diolog(self, info):
        self.main_window.info_dialog(
            'information',
            str(info),
        )
```
2. Run it by toga.
3. Click the button **_start_**
4. See error: Nothing happen to the button _start_. Expectantly, it will change it background color such as black and blue.Instead of,it is still in pink.

### Expected behavior

It will change its own color like bule or black.

### Screenshots

![Uploading image.png…]()

### Environment

- Operating System:Windows 11
- Python version:3.8.10
- Software versions:
  - Briefcase: 0.3.16
  - Toga: 0.4.1
  - ...

### Logs

```

```

**Comment by rmartin16** [comment]
You can just change `background_color` directly once a widget exists.

For instance,
```python
     async def start(self, widget):
         self.data = 'hi'
         await self.diolog(self.data)
         if not self.flag:
             self.flag = True
             self.start_button.style.background_color = "blue"
         else:
             self.flag = False
             self.start_button.style.background_color = "black"
         print(self.flag)
```

The example `color` app [demonstrates](https://github.com/beeware/toga/blob/f4dee4fdf6b1f3fb5639a12f639323afb8151f2a/examples/colors/colors/app.py#L19) this in more detail.

Additionally, in general, you shouldn't need to call the `refresh()` method yourself; Toga will refresh widgets for you as appropriate.
