### ISSUE TITLE
Introduce namedtuple types for position and size

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2388]
### What is the problem or limitation you are having?

Toga makes extensive use of tuples to pass around size and position values (e.g., the size and position of a window)

Tuples work for this purpose, and are extremely convenient from the perspective of the user providing input; but can make usage obscure because they rely on understanding that, for example `mysize[0]` is width, and `mysize[1]` is height.

### Describe the solution you'd like

Toga should define namedtuples for Size and Position data types. This would allow the usage of `mysize.width` and `mysize.height`, `myposition.x` and `myposition.y`  at runtime.

These type declarations should be in a `toga.types` package, but exposed through the `toga` namespace, so `toga.Size()` and `toga.Position()` would be legal references.

Any setter or method that accepts a tuple should continue to do so in addition to the new type; however, internally, Toga should cast the "raw" tuple to the named tuple as early as is convenient. Any value returned by a Toga API should be in the namedtuple form. 

A `SizeT` type alias for "Size in nametuple or raw tuple form" should be defined (and similar for position), so that there's a convenient way for inputs to declare that both forms are valid. SizeT would only be used for *input*; output should always have the type annotation `toga.Size`.

Any internal code referencing `size[0]` could then be updated to reference `size.width` etc; however, this should be considered optional, as the existing `size[0]` usage should continue to work.

### Describe alternatives you've considered

* Do nothing, and continue to use raw tuples
* Use a full class, rather than a namedtuple. This essentially gains no benefit over namedtuple, other than needing to define all the extra methods to make the new class behave like a tuple.

### Additional context

Care should be taken to ensure that backends return data in the new types, rather than tuples. Adding type checks to the testbed backend may be advisable to ensure that the returned types are always honoured.

**Comment by Dundy703** [comment]
Could I give this a shot?

**Comment by freakboy3742** [comment]
@Dundy703 Go right ahead! We've got a [contribution guide](https://toga.readthedocs.io/en/stable/how-to/contribute-code.html) to help step you through the process of setting up a development environment and generating your first PR. If you've got any questions, let us know.

**Comment by freakboy3742** [comment]
By coincidence, I've needed to introduce a LatLng namedtuple type as part of #2379; that PR hasn't merged yet, but anyone implementing a fix for this issue may find that PR helpful as a guide - most of the infrstructure introduced there will be identical to what is needed by this issue.

* [A LatLng namedtuple](https://github.com/beeware/toga/pull/2379/files#diff-186e9f3e46a864c8a564434f3e77bbb69e5fd7805c1a475845005fb7a95d78b9)
* [Exposing types into the toga namespace](https://github.com/beeware/toga/pull/2379/files#diff-69a8c70d6297659b02042a083fa35def1585ab9cb5a415fefdaaccd51433715b)
* [Using a namedtuple type](https://github.com/beeware/toga/pull/2379/files#diff-fed743e45b0d5c3c02a72c0659f40c251db6c2c9e5a69823cc3b15a5625d80f2)
* [Documentation for a namedtuple](https://github.com/beeware/toga/pull/2379/files#diff-03fcf86e1980492b595236b583ba97160834259a32f023d85da84725da723205)
* [Documentation configuration to support namedtuples](https://github.com/beeware/toga/pull/2379/files#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3)

**Comment by rashenck** [comment]
Going to picking this up at the Pycon US sprint!
