### ISSUE TITLE
light.exe : error LGHT0134 : The code page '65001' is not a valid Windows code page.

### ISSUE THREAD

**Issue by goldenbubble2023** [beeware/toga#2410]
### Describe the bug
```
(venv) PS F:\PythonProject\beeware\helloworld> chcp
Active code page: 65001
(venv) PS F:\PythonProject\beeware\helloworld> briefcase package

*************************************************************************
** WARNING: No signing identity provided                               **
*************************************************************************
    Briefcase will not sign the app. To provide a signing identity,
    use the `--identity` option; or, to explicitly disable signing,
    use `--adhoc-sign`.
*************************************************************************

[helloworld] Building MSI...
Compiling application manifest...
Compiling... done
Compiling application installer...
helloworld.wxs
helloworld-manifest.wxs
Compiling... done
Linking application installer...

light.exe : error LGHT0134 : The code page '65001' is not a valid Windows code page.
Update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.
Linking...

Unable to link app helloworld.
```
### Steps to reproduce

1. On step 'Tutorial 3 - Packaging for distribution-Building your installer'
2. Type 'briefcase package'
3. See error light.exe : error LGHT0134 : The code page '65001' is not a valid Windows code page. 
 

### Expected behavior

Expect Packaged dist\Hello_World-0.0.1.msi step completes

### Environment

- Operating System: win 10
- Python version: 3.10
- Software versions:
  - Briefcase: 0.3.17
  - Toga: 0.42
  - ...

### Logs

```

```

**Comment by rmartin16** [comment]
I can't reproduce this on Windows 10 or 11. And there's scant information about `LGHT0134` anywhere on the internet. I find https://github.com/wixtoolset/issues/issues/4538, though, which suggests such an error could happen when unsupported characters are used in certain fields.

@goldenbubble2023, Are you using non-ASCII characters for any metadata in your project? Also, can you upload the log file that Briefcase created for the error?

**Comment by goldenbubble2023** [comment]
[briefcase.2024_02_20-11_47_41.package.log](https://github.com/beeware/toga/files/14339130/briefcase.2024_02_20-11_47_41.package.log)
@rmartin16 thanks for the support, I was following tutorials, all codes I used in app.py are from examples, not even a custom code. 
this is a log file I tried one more time minutes ago. I was not sure if the error is from win10, I adjusted win10 code page to 65001,but currently nothing changes.

**Comment by rmartin16** [comment]
@goldenbubble2023, can you try `chcp 1252` or `chcp 437` before running Briefcase? Are you running Briefcase from inside VS Code or a similar IDE? Or directly from a terminal shell window like `cmd` or `PowerShell`?

Ultimately, this error is coming from the [WiX Toolset](https://wixtoolset.org/docs/v3/) and they don't seem to have any documentation about this error. The WiX project structure created by Briefcase specifies `UTF-8` as the codepage to use to create the MSI; so, we aren't trying to avoid UTF-8 or anything...

**Comment by mhsmith** [comment]
If this is still a problem, please provide the information requested above, and we'll reopen the issue.
