### ISSUE TITLE
GTK unable to put a menu item after submenu

### ISSUE THREAD

**Issue by RastislavKish** [beeware/toga#2418]
### Describe the bug

I would like to achieve the following menu structure in a Greeter app:

```
Greeting {// The root group and menu
    - Style { //A subgroup and a submenu
        - Formal //Command
        - Informal //Command
    }
    - Greet //A command
}
```

However, when trying to do so, I end up with the following menu structure instead:

```
Greeting {// The root group and menu
    - Style { //A subgroup and a submenu
        - Formal //Command
        - Informal //Command
        - Greet //Command, shouldn't be here
    }
}
```

### Steps to reproduce

1. Run the example code below
2. Click on the Greeting menu and see its structure, which is laid out as mentioned above

### Expected behavior

With the proper configuration of parent groups and orders, the menu should be laid out like described in the goal structure.

### Environment

- Operating System: Ubuntu Mate 22.04 64-bit
- Python version: 3.10
- Software versions:
  - Toga: 0.4.2

### Logs

```

```

### Additional context

Here is the example code (the commands are dummy):

```
import toga
from toga import App, Command, Group, MainWindow

class GreeterWindow(MainWindow):

    def __init__(self):
        super().__init__(None, "Greeter")

        greeting_group=Group("Greeting")
        style_group=Group("Style", parent=greeting_group, order=1)

        formal=Command(self.formal,
            text="Formal",
            group=style_group,
            order=1,
            )
        informal=Command(self.informal,
            text="Informal",
            group=style_group,
            order=2,
            )
        greet=Command(self.greet,
            text="Greet",
            group=greeting_group,
            order=2,
            )

        self.toolbar.add(formal, informal, greet)

    def formal(self, sender):
        pass
    def informal(self, sender):
        pass

    def greet(self, sender):
        pass

class GreeterApp(App):

    def __init__(self):
        super().__init__("greeter", "com.example.greeter")

    def startup(self):
        self.main_window=GreeterWindow()
        self.main_window.show()

GreeterApp().main_loop()
```

Thanks!

**Comment by freakboy3742** [comment]
Thanks for the report - I can confirm I can reproduce this. It appears to be GTK; macOS and Windows both render the menu correctly.

The problem appears to be that the lookup of menu sections isn't contextual; as a result, the greeter is being added to the currently active section (the submenu), rather than the main section of the top level "greeting" menu. I should have a fix for this shortly.
