### ISSUE TITLE
on_exit handler and exit() for android.

### ISSUE THREAD

**Issue by greenshelll** [beeware/toga#2419]
### What is the problem or limitation you are having?

As far as im aware of, currently, using the back button for the android immediately closes the app.  The on_exit handler doesnt work. Are there any work arounds we could use at the moment? if its possible. 

As things are now, the simplicity is alright, but I feel like this functionality is necessary.

### Describe the solution you'd like

Exactly how on_exit handler and exit() method would work in windows.
It would be helpful to have an onDestroy handler for the app, as the 'Back' button serves as a core and standard navigation control for android.

### Describe alternatives you've considered

None.

### Additional context

I would like to use it for navigation purposes (more specifically, changing to previous screens) and saving operations (autosave changes).

**Comment by mhsmith** [comment]
This was previously reported as #1623, which was closed by #2075, but that may have been a mistake.

**Comment by mhsmith** [comment]
Unfortunately there's no easy workaround at the moment. Please subscribe to #1623 for future updates.

**Comment by greenshelll** [comment]
I see. thank you very much.
