### ISSUE TITLE
pyinstaller  toga,can't run!

### ISSUE THREAD

**Issue by joysky77** [beeware/toga#2436]
### Describe the bug

Traceback (most recent call last):
  File "app.py", line 674, in <module>
  File "app.py", line 670, in main
  File "toga\app.py", line 466, in __init__
    self.factory = get_platform_factory()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "toga\platform.py", line 56, in get_platform_factory
    raise RuntimeError("No Toga backend could be loaded.")
RuntimeError: No Toga backend could be loaded.

### Steps to reproduce

how to ?

### Expected behavior

when I use pyinstaller to package app,and run the app, error

### Environment

- Operating System:win11
- Python version:3.12
- Software versions:
  - Briefcase:
  - Toga:last
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
I'm not sure why this has been reported as a bug with Toga - it seems like it's a bug with Pyinstaller, or whatever you need to do to configure the app with Pyinstaller. 

Unless you can point to something that Toga is doing wrong, this isn't a bug with Toga. The line of code you've highlighted suggests that your app doesn't have a Toga backend available.

FWIW, BeeWare's recommended mechanism for packaging apps is [Briefcase](https://github.com/beeware/briefcase).

**Comment by davetapley** [comment]
FYI fixed the `No Toga backend could be loaded`, but probably lots more work, tracking here:

- https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/803
