### ISSUE TITLE
Soften runtime requirement for Android SwipeRefreshLayout

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2454]
### What is the problem or limitation you are having?

The Android backend currently requires that `androidx.swiperefreshlayout:swiperefreshlayout:1.1.0` be available as a runtime dependency, even if you're not using the DetailedList widget where it is used.

### Describe the solution you'd like

Briefcase now allows for end-user customisation of gradle dependencies. The dependency on SwipeRefreshLayout should only be required if you actually use the DetailedList widget. If you don't, an app should run without this dependency being declared.

### Describe alternatives you've considered

Do nothing. Apps will continue to work; there's just an extra dependency that isn't used. 

### Additional context

Three changes are required:

1. Catch an `ImportError` related to [importing `SwipeRefreshLayout` in DetailedList](https://github.com/beeware/toga/blob/main/android/src/toga_android/widgets/detailedlist.py#L9) if the package isn't available. 
2. Raise an error in the [DetailedList `create() method](https://github.com/beeware/toga/blob/main/android/src/toga_android/widgets/detailedlist.py#L91) if the import wasn't successful
3. Add note in the DetailedList documentation [notes section](https://github.com/beeware/toga/blob/main/docs/reference/api/widgets/detailedlist.rst?plain=1#L132), that clarifies the required dependency.

The implementation of MapView will be a useful point of comparison - it has [`ImportError` handling when `OSMMapView ` isn't available](https://github.com/beeware/toga/blob/main/android/src/toga_android/widgets/mapview.py#L8), raises an error if MapView is used [when OSMMapView isn't available](https://github.com/beeware/toga/blob/main/android/src/toga_android/widgets/mapview.py#L42), and has documentation [describing the required dependency](https://github.com/beeware/toga/blob/main/docs/reference/api/widgets/mapview.rst?plain=1#L110)

**Comment by gwen-sarapata** [comment]
I'll take a look at this at PyCon US 2024

**Comment by mhsmith** [comment]
Fixed by #2595.
