### ISSUE TITLE
README badge rendering on GitHub changed

### ISSUE THREAD

**Issue by rmartin16** [beeware/toga#2491]
### Describe the bug

I think GitHub changed the way the badges are being rendered in the README....so, instead of being side by side, they are stacked. I think the badges should be side by side.

Note: Other repos, such as Briefcase, are also affected.

### Steps to reproduce

See the [README](https://github.com/beeware/toga/blob/main/README.rst).

![image](https://github.com/beeware/toga/assets/387848/f70a507e-190c-4db7-a5a4-ebeb33a54803)

### Expected behavior

Badges render side by side.

### Environment

- Operating System: n/a
- Python version: n/a
- Software versions:
  - Briefcase: `0.3.18.dev173+g43cb52f0`
  - Toga: `0.4.3.dev422+gfb971fde6`

**Comment by aimiktena** [comment]
Hi @freakboy3742,
I would like to contribute to fixing this issue for my university assignment. Could you please assign this issue to me ? 
Looking forward to working on it!

**Comment by freakboy3742** [comment]
@aimiktena Procedurally, we don't use formal issue assignment - an informal "I'm looking into this" is all we need.

**Comment by rmartin16** [comment]
Found the GH issue for this: https://github.com/github/markup/issues/1801

> In order to get multiple images in one paragraph in HTML 5, you need to use substitutions, [as currently described in the documentation for the image:: directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#image).

Example fix in another repo: https://github.com/jshwi/docsig/commit/f86bd021542621b400b9848e714727d7e54539ff#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f
