### ISSUE TITLE
Rust pak

### ISSUE THREAD

**Issue by NadaComa** [beeware/toga#2581]
### Describe the bug

Building an app for android which depends on "openai" gives the error message 

    Cargo, the Rust package manager, is not installed or is not on PATH.
    This package requires Rust and Cargo to compile extensions. Install it through
    the system's package manager or via https://rustup.rs/

### Steps to reproduce

1. Take the tutorial app
2. add "import openai" to app.py
3. create and build for android

### Expected behavior

Ideally the package manager would be install automatically

### Screenshots

Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.18.1.tar.gz (25 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/martin/beeware-tutorial/helloworld/build/helloworld/android/gradle/app/build/python/env/debug/bin/python /home/martin/beeware-tutorial/helloworld/build/helloworld/android/gradle/app/build/python/env/debug/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp76r2xhm_
         cwd: /tmp/pip-install-wp2j9vwc/rpds-py
    Complete output (6 lines):
    
    Cargo, the Rust package manager, is not installed or is not on PATH.
    This package requires Rust and Cargo to compile extensions. Install it through
    the system's package manager or via https://rustup.rs/
    
    Checking for Rust toolchain....
    ----------------------------------------
ERROR: Failed to install rpds-py>=0.7.1 from https://files.pythonhosted.org/packages/2d/aa/e7c404bdee1db7be09860dff423d022ffdce9269ec8e6532cce09ee7beea/rpds_py-0.18.1.tar.gz#sha256=dc48b479d540770c811fbd1eb9ba2bb66951863e448efec2e2c102625328e92f (from jsonschema>=2.6.0->openapi->-r requirements.txt (line 2)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command '/home/martin/beeware-tutorial/helloworld/build/helloworld/android/gradle/app/build/python/env/debug/bin/python'' finished with non-zero exit value 1

### Environment

- Operating System: Debian 12
- Python version: 3.9
- Software versions:
  - Briefcase: 0.3.18
  - Toga:0.4.4
  - 

### Logs

```

```

**Comment by rmartin16** [comment]
The error says you're trying to install `openapi` yet your issue details says `openai`; can you clarify which package you're talking about?

If you want to use `openai` on Android, then you need to use an older version of `pydantic`; you can use `pydantic==1.9.0` or possibly more recent versions that don't depend on Rust.

In general, though, many packages with compiled extensions are not yet available for mobile platforms, especially where Rust is concerned; see more info [here](https://briefcase.readthedocs.io/en/latest/background/faq.html#can-i-use-third-party-python-packages-in-my-app).

**Comment by NadaComa** [comment]
Sorry for the typo. Indeed I wanted to get openai to run and setting pydantic==1.9.0 as resource resolved the issue.

Additional question: Running the app on the emulator, I cant resolve hostnames in my LAN. The DNS would be 192.168.0.254, but gradle sets 10.0.2.3 which seems to resolve the global web just fine but misses 192.168.0.*
Is there a network config file somewhere in the android build directory?

**Comment by rmartin16** [comment]
If you run `briefcase run android -vv`, the console output will include the command that Briefcase uses to start the emulator.

It'll look something like this:
```
/home/russell/.cache/briefcase/tools/android_sdk/emulator/emulator @beePhone -dns-server 8.8.8.8
```
Briefcase defaults to using Google's DNS. If you run this command yourself before running Briefcase, you can set the DNS to your own local DNS. Once that emulator is running, run `briefcase run android` again and that running emulator will be an option to choose to run your app.

**Comment by NadaComa** [comment]
Great, another minor question I can't find in the docus.

How do I get the path to store app-only data?

Out of the box toga wants to write to "/" which it does not have permission for.

Android seems to have the context.filesDir() function. Can I call this somehow from withing toga?

**Comment by rmartin16** [comment]
You can use `self.paths` in your `toga.App` subclass or `toga.App.app.paths` once your app has been created.

Some of the paths may not exist before using them; you can use something like `self.paths.config.mkdir(parents=True, exist_ok=True)` each time your app runs to ensure the directory always exists.

**Comment by NadaComa** [comment]
Sorry, I need some more assistance, but I am almost there :-)

I want to use trafilatura==1.9.0, which is pure python but relies on libxml2 and libxslt.
Now your secondary respository contains those libraries and adding them to the "requires" section in the pyproject file (e.g. chaquopy_libxml2~=2.9.8) will get them installed. But trafilatura still triggeres the compliation of libxml2 (propbably due to the chaquopy prefix) and fails.

Is there any easy way to say: just use the chaquopy version? Or any howto outlining how to deal with such a situation?

**Comment by freakboy3742** [comment]
The instructions you've linked will help you set up a recipe to build wheels for a project. You can then add those wheels directly to your `requires` list in your pyproject.toml, or submit the recipe you've constructed as a pull request to chaquopy so that others can use the recipe, and chaquopy can publish a version of that wheel.

**Comment by mhsmith** [comment]
> But trafilatura still triggeres the compliation of libxml2 (propbably due to the chaquopy prefix) and fails.

`trafilatura` has a pure-Python wheel on PyPI, so I'm not sure how it could trigger the compilation of anything. Please post the full error message you received.
