### ISSUE TITLE
App crashes without logs/error message when camera permissions are required, but required metadata not added to pyproject.toml

### ISSUE THREAD

**Issue by gtm19** [beeware/toga#2589]
### Describe the bug

If :
- `permission.camera` is missing from app's `pyproject.toml` file, and
- `self.camera.request_permission()` is called from within a `toga.App` instance, and
- the app is run using `briefcase run [-ur]`

Then it crashes and produces no logs.

If you dig around in the 'Report' dialog generated by macOS, you get the following message:

> This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data

### Steps to reproduce

1. Instantiate a briefcase app
2. Add a call to `self.camera.request_permission()` in a method
3. Add the method as a callback to a button
4. `briefcase run -ur` and push the button

If you run `briefcase dev` the app seems to work and does not warn that the permissions have not been set.

### Expected behavior

A warning during development, and an error when running a bundled app, that the `permission.camera` metadata is missing from the `pyproject.toml` file

### Environment

- Operating System: MacOS Sonoma 14.4.1
- Python version: 3.12.1
- Software versions:
  - Briefcase: 0.3.18
  - Toga: 0.4.4

### Logs

[briefcase.2024_05_22-05_55_05.run.log](https://github.com/beeware/toga/files/15401453/briefcase.2024_05_22-05_55_05.run.log)

**Comment by freakboy3742** [comment]
I *think* this issue only occurs on Sonoma; I did the initial development on Ventura, and didn't have this problem, but I have since updated my laptop and can confirm that it's definitely happening now.
