### ISSUE TITLE
background_color="transparent"  is not transparent for buttons

### ISSUE THREAD

**Issue by l-o-u-i-s-g** [beeware/toga#2603]
### Describe the bug

if  I overlay a button with background_color set to transparent over a colored box   then the background on the part that is overlayed is not transparent, it is simply the same background color as the parent box.

### Steps to reproduce

#  create a box with a black background
testbox1 = toga.Box(style=Pack(width=500, height=500, padding=0, background_color="#000000"))
# create a button with a transparent background
button = toga.Button (text="test", style=Pack(width=500, height=265, padding=5, font_size=50, color="#ffffff", background_color="transparent", padding_left= -100,) 

#add both object to samebox
pbox.add(testbox1)
pbax.add(button)

### Expected behavior

I was expecting to see the black background to show trough  the part of the button that is overlayed. Something like the following image: 
![overlay2](https://github.com/beeware/toga/assets/76489821/e010c59e-b557-42c8-b140-10e2c4320b9b)

### Screenshots

![overlay](https://github.com/beeware/toga/assets/76489821/604c7d58-3ad2-4abe-b537-1a8e48fc23e6)

### Environment

- Operating System:  Linux
- Python version: 3.12.3
- Software versions:
  - Briefcase: 0.3.18
  - Toga: 0.4.4
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
The handling of `TRANSPARENT` on button backgrounds is [documented behavior](https://toga.readthedocs.io/en/stable/reference/api/widgets/button.html#notes)

**Comment by l-o-u-i-s-g** [comment]
Missed that..  for future reference if anyone else is looking for the same effect  it can be accomplished using rgba colors , I assumed at first that we could only use Hex colors as this is what was used in examples.
