### ISSUE TITLE
How to hide the toolbar

### ISSUE THREAD

**Issue by planework** [beeware/toga#2609]
### What is the problem or limitation you are having?

How to hide the toolbar

### Describe the solution you'd like

How to hide the toolbar

### Describe alternatives you've considered

How to hide the toolbar

### Additional context

How to hide the toolbar

**Comment by freakboy3742** [comment]
If you don't want a toolbar, don't add one. Toga won't add a toolbar unless you assign commands to the window's toolbar class.

However, if you're asking about removing the *menu* bar - that's a long standing feature request; see #1870. There's a prototype implementation in #2244; we're hoping to finalize this work in the coming month or so.
