### ISSUE TITLE
How to save an image on album（Android）

### ISSUE THREAD

**Issue by xi-yue-233** [beeware/toga#2610]
### What is the problem or limitation you are having?

I have a program to generate some images on toga.path.data，how can I move or save them on album?

### Describe the solution you'd like

save image on album

### Describe alternatives you've considered

move move from data path to album

**Comment by freakboy3742** [comment]
At present, Toga doesn't have any cross-platform support for photo libraries/albums. 

Photo albums aren't implemented as directories of files; they're separate applications, and interacting with them requires using cross-app data sharing mechanisms, not simple "file open/file save" operations. 

At present, if you want to use the photo library, you will need to use the [native Android Photos API](https://developers.google.com/photos), using the [Chaquopy](https://chaquo.com/chaquopy/doc/current/python.html) bridging layer to access the Java APIs.

I've opened #2611 to provide a more complete description of this feature.
