### ISSUE TITLE
Intermittent crash in macOS CI, after test_secondary_window_with_content

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#2631]
This has now happened in 2 out of the last 3 merges to main:

* https://github.com/beeware/toga/actions/runs/9440671114/job/26000510273
* https://github.com/beeware/toga/actions/runs/9440341374/job/25999536477

And also a couple of weeks ago:

* https://github.com/beeware/toga/actions/runs/9296068601/job/25584229302

It always happens at the same point:

```
tests/test_window.py::test_title PASSED                                  [  9%]
tests/test_window.py::test_secondary_window[second_window_kwargs0] PASSED [  9%]
tests/test_window.py::test_secondary_window_with_args[second_window_kwargs0] PASSED [ 10%]
tests/test_window.py::test_secondary_window_with_content PASSED          [ 10%]

Test suite didn't report a result.
Saving log... started

Log saved to /Users/runner/work/toga/toga/testbed/logs/briefcase.2024_05_30-02_51_53.run.log

Saving log... done
Error: Process completed with exit code 200.
```

**Comment by freakboy3742** [comment]
Confirmed I've seen this recently as well. When it occurs, it reliably occurs at the same point in the suite, but it doesn't occur every time, making it a PITA to reproduce.
