### ISSUE TITLE
Incorporate Wayland in to testing strategy

### ISSUE THREAD

**Issue by rmartin16** [beeware/toga#2668]
### What is the problem or limitation you are having?

Toga is not currently exercised with wayland as part of continuous integration. Given the popular distros are shipping with wayland as the default now, it seems prudent to test against it using the testbed app in CI.

### Describe the solution you'd like

Add a job to the testbed matrix to use wayland.

There are currently issues with using Toga on wayland; notably, some Gtk support is relatively recent. Therefore, the Gtk library even on Ubuntu 24.04 doesn't appear new enough to support all the features of Toga; for instance, assigning the current window got merged a year ago. I did have better success on Arch but still some issues.

I also haven't tried running wayland in a GitHub Actions runner....so, that'll need to be figured out as well as creating a headless session; I did some experimentation with weston but encountered some major issues requiring more investigation.

### Describe alternatives you've considered

Status quo.

**Comment by freakboy3742** [comment]
Agreed we should do this - as soon as we can work out how.
