### ISSUE TITLE
CommandSet should have a `remove` method

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#2701]
This would make dynamic updates much easier. Currently the only public workaround is to call `clear` and then `add` all the other commands back.

**Comment by freakboy3742** [comment]
As of the current main, it's also possible to use `del commands[command_id]`; however, I agree that it would be consistent to (a) allow instances as well as IDs, and (b) allow a `.remove()` alternate spelling for that functionality.

**Comment by mhsmith** [comment]
> As of the current main, it's also possible to use `del commands[command_id]`

I don't think so, because there's no `__delitem__` method.

**Comment by freakboy3742** [comment]
I stand corrected - I added `__getitem__` in #2636 so that commands could be modified; for some reason, I thought I added `__delitem__` as well so that default commands could be deleted.

**Comment by rmartin16** [comment]
To that end...I was going to add reasonable superclass ABCs for a lot of these structures in #2252 but I found that many had at least a few missing methods for their claimed interfaces....so I omitted those changes. Should we consider adding these superclasses to ensure we have the appropriate interfaces implemented?

**Comment by freakboy3742** [comment]
No objection from me at a conceptual level, but the devil is in the details. As long as satisfying the interface doesn't mean implementing functionality we don't want to support, or breaking useful functionality, I don't object to being more ABC compliant.

The only thing I have in mind here is the lookup-by-id vs lookup-by-instance; I don't know what the ABC would enforce in this case.

**Comment by mhsmith** [comment]
We're effectively offering two ABCs here: `Set[Command]` and `Mapping[str, Command]`.

**Comment by freakboy3742** [comment]
Oh sure - I was more just flagging that we need to ensure that supporting an ABC doesn't require adding functionality that we explicitly *don't* want to add to the actual CommandSet interface. I don't have anything particular in mind; I'm just wary that sometimes protocols include edge case APIs that we don't necessarily want to implement.
