### ISSUE TITLE
Table object not updating, and not allowing (data = ('','')) on initialize

### ISSUE THREAD

**Issue by Peder2911** [beeware/toga#278]
Hey!

I am trying to insert data into a table on a buttonpress, but the table isn't being updated. If i print the ._data i see that it contains the data i want it to express, but it is blank in the window.

In addition, i have to use the _data with an underscore, because my Table object apparently doesn't have a .data value?

Here is my code:

import toga

from main import *

class Ornithologist(toga.App):
    def startup(self):
        self.main_window = toga.MainWindow(self.name)
        self.main_window.app = self

        self.main = toga.SplitContainer()
        auxBox = toga.Box()
        self.infoTab = toga.Table(headings = ['Val1','Val2'])

        self.statusField = toga.MultilineTextInput()

        self.scrapeButton = toga.Button('SCRAPE', on_press = self.scrape)

        auxBox.add(self.scrapeButton)
        auxBox.add(self.statusField)

        self.main.content = [auxBox,self.infoTab]

        self.main_window.content = self.main

        self.main_window.show()

    def scrape(self,widget):
        messages = scrapePublic()
        items = list()
        for message in messages:
            self.infoTab.insert(None,message['authorSN'],message['msgID'])
        print(str(self.infoTab._data))

**Comment by freakboy3742** [comment]
Hi @Peder2911 - sorry to hear you're having problems. 

Two questions to help diagnose what is going on:
1. What version of Toga are you using?
2. What platform are you using? (macOS? GTK? Windows?)

As for the `data` attribute -  a Table *should* have a `data` attribute; if it's missing, that's possibly pointing at a bigger problem.

**Comment by Peder2911** [comment]
Hello again.
I am on Toga version 0.2.15, running on OSX 10.11.6 💯 

I agree, finding out that the Table didn't have the data attribute was really puzzling.

**Comment by DariusMontez** [comment]
I stumbled across this as well, but I think I know why -- toga.Table's `data` argument defaults to None, so if no data is provided in the constructor, `DataSource` initialization is completely skipped. If the argument instead defaulted to `[]` (which is essentially the equivalent of "zero rows of data"), then a `DataSource` is created for the table.

**Comment by Peder2911** [comment]
Oh, I perhaps forgot to mention: When I try to instantiate the toga.Table object with the data argument, I get a message saying that the Table object doesn't take the data argument. Really wierd!

**Comment by DariusMontez** [comment]
I believe this can be closed. Table and Tree have undergone much refactoring since v0.2.15 and should be resolved.
