### ISSUE TITLE
OptionContainer - Windows

### ISSUE THREAD

**Issue by iongion** [beeware/toga#28]
```
site-packages\toga_demo\__main__.py", line 31, in main
    left_container = toga.OptionContainer()
AttributeError: 'module' object has no attribute 'OptionContainer'
```

**Comment by Siecje** [comment]
I've just experienced this problem on Windows.

I know Windows support is experimental, but I'm wondering where the ```toga.OptionContainer()``` is supposed to come from.

What would be the steps to fix this?

**Comment by freakboy3742** [comment]
An `OptionContainer` is a widget that hasn't been wrapped up for use under Win32; to fix this bug, you'd need to write a Win32 implementation of this widget.

It's a container widget that allows you to switch between different panels. The usual native implementation would be a Tab view. The implementation would go under `toga_win32/widgets/optioncontainer.py`.

What you'd be looking to write is code similar to `toga_win32/widgets/button.py`, but providing the same interface as OptionContainer on the Cocoa and GTK implementations.

If you're interested in contributing to the Win32 backend, I'd certainly appreciate the help - Win32 is an important platform, but it's not one where I have any expertise (or even access to for development purposes).
