### ISSUE TITLE
Textual apps do not report terminal size correctly

### ISSUE THREAD

**Issue by rmartin16** [beeware/toga#2819]
### Describe the bug

Textual apps do not resolve the size of the terminal window correctly. The most noticeable effect of this is the titlebar is corrupted.

![image](https://github.com/user-attachments/assets/be2b325f-5a14-4caf-845e-b8221a298280)

Once the app is running for a second or two, the size is reported as `Size(width=80, height=24)`. Resizing the terminal window also has no effect.

### Steps to reproduce

Run any app with the textual backend.

### Expected behavior

Terminal window size is reported correctly.

### Environment

- Operating System: pop os 22.04
- Python version: 3.10.14
- Software versions: 
  - Briefcase: `0.3.20.dev192+g32f529a4`
  - Toga: `0.4.7.dev43+g63480d545`

**Comment by freakboy3742** [comment]
Not entirely surprising, as textual features don't get anywhere near as much testing as the desktop and mobile backends. I do wonder if this might be another Texual upgrade issue; when using Textual 0.63.2, the titlebar renders correctly, resizes with the console window, and reports the correct size.

**Comment by rmartin16** [comment]
After a bunch of ultimately useless debugging, I decided to try to run a textual app without `briefcase dev`...and that worked; the app could successfully track the size of the terminal again.

Once I added `console_app = true` to `pyproject.toml`, `briefcase dev` no longer attached a `PIPE` to `stdout` for the app. I guess this is an interesting situation; `console_app` is a binary setting...but the Textual backend for Toga allows an app to be both a Console and a GUI app.... 🤔

**Comment by freakboy3742** [comment]
> After a bunch of ultimately useless debugging, I decided to try to run a textual app without `briefcase dev`...and that worked; the app could successfully track the size of the terminal again.
> 
> Once I added `console_app = true` to `pyproject.toml`, `briefcase dev` no longer attached a `PIPE` to `stdout` for the app. I guess this is an interesting situation; `console_app` is a binary setting...but the Textual backend for Toga allows an app to be both a Console and a GUI app.... 🤔

I don't think that's not entirely true. A Briefcase app with `console_app = false` (either explicitly or implicitly) doesn't provide any guarantee that there is a console. 
* In the Windows context, a GUI app explicitly *doesn't* have a console; `briefcase run` will surface logs for convenience, and attaches a console for that purpose which the app can adapt to.
* In the macOS context, any stdout content on a GUI app is mirrored to the system log; again, `briefcase run` surfaces the system log content to the user, not the console
* iOS, Android and Web don't have any concept of a "console app"; there's only the system log

Linux is the only odd-one-out here; there's no special handling of stdout/error, beyond controlling the level of debug information displayed at app startup in debug/verbose mode. 

`briefcase dev` is also a special case; but it's mostly trying to emulate (as close as possible) the situation with Windows/macOS - a GUI app get streamed stdout logs, with no stdin; a console app gets a direct console connection.

So - the net result here is that from the perspective of Briefcase, Textual really is a "console" app, not a "GUI" app. Which... doesn't seem that inconsistent to me.

**Comment by rmartin16** [comment]
Right...and I think all that makes sense if you're dealing with an app that is either console or GUI. But Toga's textual backend provides the at least theoretical possibility that the same code can be either at different times. For instance, an app that runs a GUI if a display is available and falls back to console otherwise. Or just one that has separate distributables for either use-case. Anyway, mostly thinking out loud...

**Comment by freakboy3742** [comment]
> Right...and I think all that makes sense if you're dealing with an app that is either console or GUI. But Toga's textual backend provides the at least theoretical possibility that the same code can be either at different times. For instance, an app that runs a GUI if a display is available and falls back to console otherwise. Or just one that has separate distributables for either use-case. Anyway, mostly thinking out loud...

I hadn't considered the possibility of an app that ships *both* the textual AND a "True" GUI backend... I'm not sure that's even something we can reasonably accomodate. I think the best we're going to be able to do in that case is to call it a "console" app, and then not capture the logs if it is run in GUI mode.

**Comment by rmartin16** [comment]
Sounds good; we can always revisit something like this later.
