### ISSUE TITLE
iOS MainWindow layouts don't take navigation bar into account.

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2836]
_Originally posted by @jlij in https://github.com/beeware/toga/discussions/2828#discussioncomment-10631652_

iOS apps with a title bar appear to be generating layouts that are too large for the visible display. The layout does not appear to be taking the navigation bar into account.

```
import toga
from toga.style import Pack
from toga import Box, DetailedList, Button
from toga.style.pack import COLUMN, ROW

class TestApp(toga.App):
    def startup(self):
        self.passenger_dl = toga.Box(style=Pack(flex=1))

        self.record_button = [Button(text=i,  style=Pack(flex=1, font_size=18)) for i in  ['A', 'B', 'C', 'D']]
        self.button_box = toga.Box(children=self.record_button, style=Pack(direction=ROW))

        self.page_box = toga.Box(children=[ self.passenger_dl, self.button_box],
                              style=Pack(flex=1, direction=COLUMN))

        self.main_window = toga.MainWindow()
        self.main_window.content =self.page_box
        self.main_window.show()


def main():
    return TestApp()
```
In this example, if the `MainWindow` is turned back to a `Window`, the layout works as expected. 

An iOS 15 Pro has a native height of 852, with 54 pixels dedicated to the status bar frame. This sets a height of 757 for the simple Window case. 

However, using MainWindow, the top offset isn't taken into consideration. This appears to be because the NavigationConatiner doesn't extend RootContainer, so the implementation of `height` doesn't inherit the top_offset calculation.

**Comment by drew0ps** [comment]
@freakboy3742 I have another example for this issue, but instead of buttons I tried to use the OptionContainer. On android it looks fine, on iOS the navigation buttons are not visible, only barely on 15 Pro Max in rotated position.

```
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW, CENTER, LEFT

class mobile_app(toga.App):
    def startup(self):
        self.gui(self)

    def gui(self, widget):
        red_box = toga.Box(style=Pack(background_color="red"))
        blue_box = toga.Box(style=Pack(background_color="blue"))
        
        main_box = toga.OptionContainer(content=[
            toga.OptionItem("red", red_box),
            toga.OptionItem("blue", blue_box)
        ])

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return mobile_app()

```

**Comment by freakboy3742** [comment]
Yeah - this looks like an oversight when we introduced simple app support. The good news is that the fix should be fairly straightforward - we need to move the top_offset handling so it is used consistently.

**Comment by drew0ps** [comment]
To me it seems this is also an issue on macos, when optionContainer is uses and there is a horizontal scroll container within, the scroll element is not visible and can only made visible by manually expanding the window. If it's not in an optioncontainer, the horizontal scroll bar is displayed since the window is correctly sized.

**Comment by freakboy3742** [comment]
> To me it seems this is also an issue on macos, when optionContainer is used and there is a horizontal scroll container within, the scroll element is not visible and can only made visible by manually expanding the window. If it's not in an optioncontainer, the horizontal scroll bar is displayed since the window is correctly sized.

A problem with the layout of ScrollContainers inside OptionContainers on macOS pretty clearly isn't the same issue as a problem with non-scrollable widgets on iOS. There may well be a *separate* issue - but that needs to be logged as a separate bug, with a separate reproduction case.

**Comment by freakboy3742** [comment]
@drew0ps I've opened your earlier comment with a reproduction case as #2845.
