### ISSUE TITLE
OptionContainer obscures bottom scroller on macOS

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2845]
On macOS, a ScrollContainer inside an OptionContainer will obscure the bottom scroll control:

```
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW, CENTER, LEFT

class mobile_app(toga.App):
    def startup(self):
        self.gui(self)

    def gui(self, widget):
        red_box = toga.Box(style=Pack(background_color="red"))
        blue_box = toga.Box(style=Pack(background_color="blue"))
        
        main_box = toga.OptionContainer(content=[
            toga.OptionItem("red", red_box),
            toga.OptionItem("blue", blue_box)
        ])

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return mobile_app()

```

_Originally posted by @drew0ps in https://github.com/beeware/toga/issues/2836#issuecomment-2350656499_

**Comment by freakboy3742** [comment]
Closing on the basis that the reproduction case doesn't reflect the problem that was being described; and adding a ScrollContainer around the content of one of the option item content doesn't reproduce the described behavior either. 

@drew0ps If you're able to provide an updated demonstration case, we can reopen this ticket.

**Comment by drew0ps** [comment]
I tried to reproduce with a simple code but I could not, it seems to be a usage issue in my application.
