### ISSUE TITLE
Programmatic window resize on macOS does not preserve top-left position

### ISSUE THREAD

**Issue by hyuri** [beeware/toga#2855]
### What is the problem or limitation you are having?

(Only tested on macOS)

If I programmatically change the size of a window, macOS nicely animates the window growing or shrinking to the new size.

The issue is:
1) On the vertical, it grows upwards, and shrinks downwards;
2) On the horizontal, it grows rightwards and shrinks leftwards.

So when you increase your window size, your widgets and title bar shift up and right, and the window becomes off-centred on the X axis, and, when you decrease your window size, your widgets and title bar shift down and left, and might remain off-centred as well.

This shifting of basically the whole GUI is jarring, and the off-centring annoying especially if you have a taste for neatness/design.

Is this behavior platform-derived?

### Describe the solution you'd like

When programmatically resizing a window:
1) If increasing the size on the Y axis (vertical), grow it downwards (away from the title bar). If decreasing, shrink it upwards (towards the title bar). This will keep the title bar and any widgets already in the window always on the same position (unless there isn't space to grow the window downwards, in which case mac will grow the window upwards as well).

2) If increasing the size on the X axis (horizontal), make it grow in both directions (to keep the window centred where it originally was), and shrink it towards the centre (to keep it centred where it originally was). This will shift the GUI on the X axis a bit, but much much less so I don't think it will be jarring and it will look neat in the end.

### Describe alternatives you've considered

None

**Comment by freakboy3742** [comment]
Can't disagree that this is the behavior; but I'm also fairly sure it's a platform quirk. We're definitely not doing anything to explicitly opt-into this behavior; and looking at [the docs for NSWindow](https://developer.apple.com/documentation/appkit/nswindow?language=objc), it's not obvious to me that the "resize direction" is something that can be programmatically controlled. 

I'm going to close this ticket on the basis that I'm not sure there's anything we can do about the situation. Happy to re-open if anyone has any specific ideas on an API that would control the animation directions.
