### ISSUE TITLE
Add support for Python 3.13 on Windows

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2889]
### Describe the bug

Toga can't currently be installed on Windows using Python 3.13.

This is due to pythonnet/pythonnet#2454.

### Steps to reproduce

1. Install Python 3.13
2. `pip install toga~=0.4.0`

The installation will fail with an error that it `Could not find a version that satisfies the requirements pythonnet>=3.0.0 (from toga-winforms) (from versions: 2.0.0, ...`

### Expected behavior

Toga should be installable on Windows.

### Environment

- Operating System: Windows
- Python version: 3.13
- Software versions:
  - Briefcase: 0.3.19+
  - Toga: 0.4.6+

### Additional context

There's nothing required on the Toga side of this problem - it's entirely an upstream issue.

**Comment by Jzhenli** [comment]
will support disable GIL?

**Comment by mhsmith** [comment]
No, we'll follow the default setting on all platforms, which means the GIL will still be present in 3.13.
