### ISSUE TITLE
Android event loop is incompatible with Python 3.13

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#2907]
The following traceback is from the Toga main branch, but the code in question has been there for over a year, so it'll also affect the stable version. I'm not familiar enough with this area to suggest an immediate fix.

Testing this will require a new version of Chaquopy, which I'll create a PR for shortly in the briefcase-android-gradle-template repository.

```
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: org.beeware.toga.examples.canvas, PID: 5835
E/AndroidRuntime: com.chaquo.python.PyException: AttributeError: 'AndroidSelector' object has no attribute '_key_from_fd'
E/AndroidRuntime:   at <python>.toga_android.libs.events.handle_fd_wakeup(events.py:347)
E/AndroidRuntime:   at <python>.toga_android.libs.events.onFileDescriptorEvents(events.py:414)
E/AndroidRuntime:   at <python>.chaquopy_java.call(chaquopy_java.pyx:352)
E/AndroidRuntime:   at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:324)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
E/AndroidRuntime:   at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
E/AndroidRuntime:   at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
E/AndroidRuntime:   at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
E/AndroidRuntime:   at $Proxy4.onFileDescriptorEvents(Unknown Source)
E/AndroidRuntime:   at android.os.MessageQueue.dispatchEvents(MessageQueue.java:304)
E/AndroidRuntime:   at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime:   at android.os.MessageQueue.next(MessageQueue.java:346)
E/AndroidRuntime:   at android.os.Looper.loopOnce(Looper.java:189)
E/AndroidRuntime:   at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:8705)
E/AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by freakboy3742** [comment]
Looks like the internal API for getting the event key from the file descriptor has changed - it's gone from [`_key_from_fd()`](https://github.com/python/cpython/blob/3.12/Lib/selectors.py#L335), which is a wrapper around a straightforward dictionary lookup, into an [API that does the lookup directly on the dictionary with a `.get()` call](https://github.com/python/cpython/blob/main/Lib/selectors.py#L320).

As far as I can tell, nothing else has changed, so it should be fairly straightforward to add a wrapper around `_key_from_fd()` usage in AndroidSelector that can accomodate the two implementations (or just wrap the two uses with a `if sys.version...` check).
