### ISSUE TITLE
Two windows opening on startup

### ISSUE THREAD

**Issue by tkshnwesper** [beeware/toga#2946]
### Describe the bug

Opens two windows when the app is launched (see screenshot).

### Steps to reproduce

Run this code:

```python
import toga

class UI(toga.App):
    def startup(self) -> None:
        self.main_window = toga.MainWindow()

        instrument_table = toga.Table(
            headings=['Location', 'Division', 'Line No.', 'Instrument No.'])

        instrument_data_table = toga.Table(headings=['Data'])

        left_container = toga.ScrollContainer(content=instrument_table)
        right_container = toga.ScrollContainer(content=instrument_data_table)

        split_container = toga.SplitContainer(
            content=[(left_container, 2), (right_container, 1)])

        self.main_window.content = split_container

        self.main_window.show()

        return super().startup()

UI('UDP GUI DB', 'com.example.udp_gui_db').main_loop()
```

### Expected behavior

Only one window should open.

### Screenshots

![image](https://github.com/user-attachments/assets/d661cc22-cf49-4389-8908-2ffabde52018)

### Environment

- Operating System: macOS Monterey (12.7.6)
- Python version: 3.12.6
- Software versions:
  - Toga: 0.4.8

**Comment by mhsmith** [comment]
You shouldn't call `super().startup()`, otherwise you'll get both the default starup and your custom startup.

If there's anything in the documentation or examples which suggested you should do this, please let us know so we can fix it.
