### ISSUE TITLE
Audit backends for consistency in "set_attribute()" pattern

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#299]
# The problem
Toga has three layers:

* The public interface;
* The platform implementation; and
* The native widgets.

There is a common pattern in Toga where the public interface exposes an attribute. For example, the Button widget has a `label` attribute. On the public interface, this is exposed as something like:

```
class Button:
    @property
    def label(self):
        return self._label

    @label.setter
    def label(self, value):
        self._label = value
        self._impl.set_label(value)
``` 
Then, the implementation will have code that looks something like:
```
class Button:
    def set_label(self, value):
        self.native.SetLabelOfButton(value)
```
That is - the public interface has a setter for the `label` attribute; that attribute stores a local value on the interface, and passes a value down to the implementation to handle as required (usually this means calling a method on the native widget).

However, the setter is usually not that simple. The setter will usually clean the input:
```
    @label.setter
    def label(self, value):
        self._label = '' if value is None else 
        self._impl.set_label(value)
``` 
So `self.label` is a "clean" value on the interface. But what value is passed down to the implementation? Is it the cleaned value (`self._label`), or the literal argument provided (`value`)?

The interface *should* pass down the literal argument - because the implementation can get access to the cleaned value if it needs it:
```
class Button:
    def set_label(self, value):
        self.native.SetLabelOfButton(self.interface.label)
```
However, the literal value isn't available unless it's passed in. There aren't many occasions when you need the literal value - but when you do, there's no substitute 😄 

# What is needed
Audit each Toga widget, and ensure that:
* Every property that is exposed passes down the literal argument to it's implementation
* Each widget backend uses the value from the interface, not the literal (unless there's a reason to do otherwise)
* Regardless of whether the property is correctly defined or not - make sure there is test to the interface layer that ensures that the implementation gets the right value. (e.g., in this case - write a test that sets the Button label to `None`, and check that the implementation receives `None`, rather than `""`.

**Comment by freakboy3742** [comment]
If you work on this ticket, drop a comment here to let us know which widget you're looking at!

**Comment by starlord1311** [comment]
i would like to take up this issue

**Comment by oguntli** [comment]
Is this still up for grabs? If so I'd like to take up this ticket

**Comment by freakboy3742** [comment]
@oguntli I haven't done a full check recently - there might be a few places left that need to be updated. At the very least, the process of auditing the code and determining that there *aren't* any instances left would be a valuable contribution!

**Comment by oguntli** [comment]
#702 Audited webview and switch

**Comment by freakboy3742** [comment]
Closing this; At this point, I'm fairly sure all the widgets have been updated.
