### ISSUE TITLE
Cannot dynamically remove GUI elements and constraints

### ISSUE THREAD

**Issue by dmlockhart** [beeware/toga#30]
Although I've found its possible to dynamically add GUI elements (e.g. create and display a new view on button press), there doesn't seem to be a way to dynamically delete GUI elements.

For example, I was trying to create a 'show/hide' button for a specific GUI element.  I haven't been able to figure out how implement this in the current version of Toga.

I was expecting that deleting a Toga GUI element using `del my_element` would remove that element and all constraints related to it, but this doesn't seem to be the case.

Is there another way to achieve this functionality?

**Comment by SamSchott** [comment]
@freakboy3742, I was thinking of working on this but wanted to check first what a good API would look like. At the moment, there is only the `Widget.add(*children)` method and I am thinking of adding the following:

* `remove(*children)` removes given children from the widget.
* `insert(index, child)` inserts the given child at the index.

One could additionally or alternatively also provide:

* `insert_before(child, new_child)` inserts `new_child` before `child`.
* `insert_after(child, new_child)` inserts `new_child` before `child`.
* `replace(child, new_child)` replaces `child` with `new_child`.
* `remove(index)` removed child at index.

Personally, I am in favour of keeping it simple and just having the first two methods.

**Comment by freakboy3742** [comment]
@SamSchott I'd say the first of the two suggestions would be my preferred option, as it's closest to the Python List interface (and thus less likely to be surprising). 

Adding an index-based using `__getitem__` might also be useful (e.g., `widget.children[n] = child` or `del widget.children[n]`). However, I'd consider supporting these of secondary importance to the main remove/insert interface.

**Comment by SamSchott** [comment]
Agreed. I'll give it try.

**Comment by obulat** [comment]
This issue has been solved in #814
