### ISSUE TITLE
Selection Example Gives Gtk+ Size Allocation Warning

### ISSUE THREAD

**Issue by danyeaw** [beeware/toga#339]
## Expected Behavior
No size allocation warnings and selection drop downs that don't go off the window.

## Current Behavior
(__main__.py:5108): Gtk-WARNING **: Allocating size to GtkComboBoxText 0x1e92ae0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

![screenshot from 2018-01-25 21-08-45](https://user-images.githubusercontent.com/10014976/35421962-233c4be6-0214-11e8-8eba-6eb7eae2dc8d.png)

## Steps to reproduce

    $ cd examples/selection
    $ python -m selection

## Your Environment

* Python Version (list the specific version number)
3.6.3
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] OSX
  - [ ] Linux
  - [ ] Windows
  - [X] Ubuntu

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [X] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by vishwas78** [comment]
@danyeaw I tried to run the code, it worked fine.
![image](https://user-images.githubusercontent.com/23501858/36092666-26d1ace4-100e-11e8-8c4b-0f16dcf84085.png)

Can you please elaborate the issue?

**Comment by SanketDG** [comment]
How can I go about fixing this?

I see that a widget's size is defined by the `rehint()` method from the `Widget` base class. I have also checked that setting `style.width` to a specific integer works for the current example. but fails if the item length is greater than this specific integer.

**Comment by freakboy3742** [comment]
I've just re-run the selection example; looks like it no longer renders like this.
