### ISSUE TITLE
Button seems to ignore enabled parameter on initalisation

### ISSUE THREAD

**Issue by go8ose** [beeware/toga#400]
## Expected Behavior

When you create a toga.Button, and set the enabled parameter to False, I expect the button to not be enabled when it's first displayed.

## Current Behavior

However it seems the button is enabled. If you later set enabled to false, the button grey's out, as expected.

## Steps to reproduce

1. Save this example code:
`python
import toga

def button_handler1(widget):
    print("hello")

button1 = toga.Button('Hello world', on_press=button_handler1, enabled=False)
button1.style.padding = 50
button1.style.flex = 1

def button_handler2(widget):
    button1.enabled = not button1.enabled
    print("Toggle button1. It is now {}.".format('enabled' if button1.enabled else "disabled"))

def build(app):
    box = toga.Box()

    box.add(button1)

    button2 = toga.Button('Toggle Button', on_press=button_handler2)
    button2.style.padding = 50
    button2.style.flex = 1
    box.add(button2)

    return box

def main():
    return toga.App('First App', 'org.pybee.helloworld', startup=build)

if __name__ == '__main__':
    main().main_loop()

`

2. Run the app, `python3 example`

3. Observe both buttons enabled. Click the "Toggle Button" a few times, and watch no change on the first press (as the button1 is enabled), then on second press the button disables, and behaves as expected from then on.

## Your Environment

* Python Version (list the specific version number)

$ python
Python 3.6.3 (default, Nov 29 2017, 07:34:08) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import toga
>>> toga.__version__
'0.3.0.dev8'

(python provided by pyenv)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [X] macOS - version: 10.13.3 (High Sierra)
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [X] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the report! Looks like we've missed some initial state setup calls.

**Comment by obulat** [comment]
I tried setting enabled=False for button in tutorial 2 in winforms, and it works as expected: all buttons are disabled from the start. So, is the problem in cocoa?

**Comment by freakboy3742** [comment]
I believe this has now been fixed.
