### ISSUE TITLE
MultilineTextInput Example No visual feedback on disabled component

### ISSUE THREAD

**Issue by ibigpapa** [beeware/toga#503]
## Expected Behavior

Visual feedback showing the widget is disabled (greyed out)

## Current Behavior

After toggling enabled there is no visual feedback showing the widget was disabled.  You can no longer type in the input but appears to be enabled.

## Steps to reproduce

1. Launch multilinetextinput example

2. click `toggle enabled` 

## Your Environment

* Python Version (list the specific version number) 3.6.5

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [ X ] Windows - version: Win10 1607
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ X ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by obulat** [comment]
The example app was a bit misleading: although the button said `toggle enabled`, it was toggling `readonly` property. Changing `readonly` property in MultilineTextInput on windows doesn't change its appearance. I updated the example app in PR#525 to reflect both readonly and enabled properties.
After merging #525 this issue may be closed.

**Comment by freakboy3742** [comment]
Closing on the basis it appears to be addressed.
