### ISSUE TITLE
Documentation - Architecture Page not Formatted

### ISSUE THREAD

**Issue by bobm123** [beeware/toga#511]
## Expected Behavior

Toga Documents Architecture Page should load with formatting

## Current Behavior

![toga-docs-arch-not-formatted](https://user-images.githubusercontent.com/3646354/40172482-a36f6f02-599c-11e8-8efc-0ec9235354cb.png)

## Steps to reproduce

1. Navigate to:
https://toga.readthedocs.io/en/latest/background/architecture.html

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by bobm123** [comment]
I spot checked the other Toga documents pages; they all seemed to load fine. Only this one had problems.

There doesn't seem to be anything obviously wrong with the page [source](https://github.com/pybee/toga/blob/master/docs/background/architecture.rst) and the  one I built locally with `make html` was ok. However, the [architecture page](https://toga.readthedocs.io/en/latest/background/architecture.html) seems to be missing the stylesheet link for `sphinx_rtd_theme.css`

**Comment by freakboy3742** [comment]
This is really weird... we've seen this one before; it turned out to be an issue with RTD itself  (rtfd/readthedocs.org#3715). Changing the order of the sphinx plugins will apparently resolve the issue...

**Comment by freakboy3742** [comment]
This has now been addressed.
