### ISSUE TITLE
Add text descriptions to file types for open file/save dialog

### ISSUE THREAD

**Issue by goanpeca** [beeware/toga#516]
See https://github.com/pybee/toga/pull/459/files#diff-88611d29871a76a974f386953705fac9R262

>It is usually possible on some systems to include a text associated to the extensions, for instance
Text Files (*.txt) or Awesome Text files (*.txt)
So file_types could be expanded to include those cases?

>@freakboy3742
>Sounds like a good idea to me. It might be easiest to create a light "datatype" class wrapper to capture these descriptions so we can use either a list or strings or a list of "datatype" objects.

**Comment by saroad2** [comment]
This is already supported. Therefore, closing this issue :)
