### ISSUE TITLE
Enforce/test expected protocols across platforms

### ISSUE THREAD

**Issue by davidroeca** [beeware/toga#520]
## Expected Behavior

When each platform-specific factory `_impl` is implemented, it should conform to the protocol leveraged in the main `toga` package, so that the toga core can call all of the same methods across platforms. 

## Potential Implementations

[Typing/mypy protocols](https://mypy.readthedocs.io/en/latest/class_basics.html#simple-user-defined-protocols) are the pipe dream here, but that will take a lot of work.

Alternatively, toga core could export an abc module like:

```python
from toga.abc import WindowABC
```

And every platform-specific dependency could rely on these ABCs.

Then each platform could have a unit test to ensure the subclass can be instantiated. For subclasses like in the `cocoa` implementation, multiple inheritance or the [register](https://docs.python.org/3.5/library/abc.html#abc.ABCMeta.register) method could be used.

Happy to chat more about this here or on gitter

EDIT:
If type hints are of preferred interest, [monkeytype](https://github.com/Instagram/MonkeyType) could be useful for generating incremental type hints

**Comment by freakboy3742** [comment]
Agreed this could a good improvement. The Dummy backend is effectively providing this interface at present; but it's only enforced as a test condition.

**Comment by freakboy3742** [comment]
On reflection, I'm not convinced this will provide value. Runtime validation of interface compliance provides no additional safety over release-time compliance.
