### ISSUE TITLE
Provide a platform support matrix for widgets

### ISSUE THREAD

**Issue by elbenfreund** [beeware/toga#524]
## Expected Behavior
In order to make informed design decisions it would be useful to have a "at a glance" overview over what widgets are supported on which platforms.

## Current Behavior
A platform support matrix exists only on a *per widget* basis.

If you are interested in a PR, just let me know where in the TOC you would like to see this. My current WIP places the matrix at the bottom of `reference/api/widgets/index.html`

**Comment by danyeaw** [comment]
So I think we use to have this, but it was really hard to keep in sync with the status of each widget. Could we pull the information for the matrix from each individual widget page so that it can't get out of sync.

**Comment by jtrakk** [comment]
> Could we pull the information for the matrix from each individual widget page so that it can't get out of sync.

Where would this information be pulled from exactly, in case someone wants to contribute this feature?

**Comment by freakboy3742** [comment]
This feature now exists.
