### ISSUE TITLE
Provide toggle button

### ISSUE THREAD

**Issue by jpauwels** [beeware/toga#526]
## Expected Behavior

It would be great if there was a toggle button in toga like in macOS, for example:  https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Button/Tasks/SettingButtonType.html

* Toga Target (the type of app you are trying to generate)
 
  - [x] android
  - [x] cocoa
  - [x] django 
  - [ ] gtk
  - [x] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
While cocoa does support this style of button, they actually [recommend against them in the macOS HIG](https://developer.apple.com/design/human-interface-guidelines/macos/buttons/bevel-buttons/). This is because there are better UI elements available now - like switches and checkboxes.
