### ISSUE TITLE
DetailedList - scroll bar and refesh wheel are on the wrong possition - macOX

### ISSUE THREAD

**Issue by Ocupe** [beeware/toga#550]
## Expected Behavior
1. Scrollbar should be on the top, when at the beginning of the detailed list and the other way around.
2. When scrolling to the top of the list and then pull down further, the refresh wheel should appear.

## Current Behavior
1. Scrollbar is on the bottom when at the top of the list. 
![screen shot 2018-06-16 at 22 42 17](https://user-images.githubusercontent.com/11357413/41502256-938770d0-71b6-11e8-833e-ac227958a9a6.png)

2. Refresh wheel appears when scrolling to the bottom and then pull up further.
![screen shot 2018-06-16 at 22 46 38](https://user-images.githubusercontent.com/11357413/41502303-647ad7e0-71b7-11e8-9376-e3ff0a083db8.png)

## Steps to reproduce

1. run toga detailed list example

## Your Environment

* Python Version (3.6.5)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [x] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by stantonxu** [comment]
@Ocupe I don't have problem on my macOS for the position of the scroll bar. Could you share your code?

**Comment by stantonxu** [comment]
Well, I overlooked your description. You meant to run the toga detailed list example.

I tried it on my macOS. Again, no problem for the scroll bar, but the refresh wheel problem does exist.

And I think I find another problem, will create a separate issue, and link here later.

**Comment by stantonxu** [comment]
The new issue created is here https://github.com/pybee/toga/issues/553

**Comment by freakboy3742** [comment]
This appears to be fixed.
