### ISSUE TITLE
Tutorial "You put the box inside another box" Crash on Windows environment

### ISSUE THREAD

**Issue by Cristianasp** [beeware/toga#566]
## Expected Behavior

Tutorial You put the box inside another box does not run correctly on Windows

## Current Behavior

[Winforms] Not implemented: Table.set_on_select()
Exceção Sem Tratamento: Python.Runtime.PythonException: ArgumentException : Parâmetro inválido.
   em System.Drawing.Bitmap..ctor(String filename)
   em Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()

## Steps to reproduce

1. use source from https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html
2. download icons: brutus.icns is not windows format but I have changed the icon to another file
3. python -m toga3.py

## Your Environment

* Python Version (list the specific version number)
Python 3.6.4 :: Anaconda, Inc.
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [ X] Windows - version: 10
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [X ] win32
  - [ ] Other (please specify)

**Comment by obulat** [comment]
I also ran into this issue before I created the `icons` folder inside the folder with the app, as is advised in the tutorial. 

I tried to run the tutorial with `pip install -pre toga` environment, and ran into another issue with icons:
```[Winforms] No valid icon format available for C:\Users\olgab\PycharmProjects\toga\venv\lib\site-packages\toga\resources\tiberius; fall back on Tiberius instead
Unhandled Exception: Python.Runtime.PythonException: FileNotFoundException : Could not find file 'C:\Users\olgab\PycharmProjects\toga\venv\lib\site-packages\toga\resources\tiberius.ico'.```
After I added `tiberius.ico` into `site-packages`, the app ran as it was supposed to.

The `tiberius.ico` file is there in `toga\core\resources` folder on github, but it doesn't exist in `site-packages\toga\resources` installed using `-pre` flag. How can we add it there?
We also need to add a check if the path to icon exists before trying to create an icon, so that if a folder with icons doesn't exist, there is a clear error message.

**Comment by obulat** [comment]
Sorry, I just saw that the issue of tiberius.ico not being available has been dealt with in PR#569 and I guess dev10 release will solve it, right?

So, the main problem here is not checking if the path to icon actually exists. What is the best way of handling non-existing paths? Raise an error or simply print out something like "Icon path <> doesn't exist" and fall-back on Tiberius icon?

**Comment by Aareon** [comment]
There are benefits of having it either way. However, I personally think the correct solution is to except. If I develop an application, I'd like to know explicitly that the app could not find a resource.

**Comment by freakboy3742** [comment]
Closing on the basis that this has since been addressed.
