### ISSUE TITLE
Could not resolve all files for configuration ':debugCompileClasspath'

### ISSUE THREAD

**Issue by silverfox983** [beeware/toga#617]
## Expected Behavior
to build my apk

## Current Behavior

* What went wrong:
Could not resolve all files for configuration ':debugCompileClasspath'.
> Could not find com.android.tools.lint:lint-gradle:26.1.0.
  Searched in the following locations:
      file:/home/seth/.buildozer/android/platform/android-sdk-linux/extras/m2repository/com/android/tools/lint/lint-gradle/26.1.0/lint-gradle-26.1.0.pom
      file:/home/seth/.buildozer/android/platform/android-sdk-linux/extras/m2repository/com/android/tools/lint/lint-gradle/26.1.0/lint-gradle-26.1.0.jar
      file:/home/seth/.buildozer/android/platform/android-sdk-linux/extras/google/m2repository/com/android/tools/lint/lint-gradle/26.1.0/lint-gradle-26.1.0.pom
      file:/home/seth/.buildozer/android/platform/android-sdk-linux/extras/google/m2repository/com/android/tools/lint/lint-gradle/26.1.0/lint-gradle-26.1.0.jar
      file:/home/seth/.buildozer/android/platform/android-sdk-linux/extras/android/m2repository/com/android/tools/lint/lint-gradle/26.1.0/lint-gradle-26.1.0.pom
      file:/home/seth/.buildozer/android/platform/android-sdk-linux/extras/android/m2repository/com/android/tools/lint/lint-gradle/26.1.0/lint-gradle-26.1.0.jar
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 43s
1 actionable task: 1 executed

## Steps to reproduce

1.

2.

3.

## Your Environment
Latest version of Ubuntu
* Python Version (list the specific version number)
3.6.6
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [x] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [x ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

looks like file paths got renamed on the websites its looking for them in

**Comment by freakboy3742** [comment]
The Android backend is currently being rebuilt by a contractor under a grant from the PSF.
