### ISSUE TITLE
It is possible to reinitialize a table widget ?

### ISSUE THREAD

**Issue by TrueMisterJeanP** [beeware/toga#623]
Hello,

I Will know if is it possible to change the headings of a table widget after having initialized it.

First:

self.table1 = toga.Table(
            headings=[],
            data=[],
            style=Pack(flex=1),
            on_select=self.on_select_row_handler
)

That produce a empty table and it is what I want.

Next:
To change the headings and the data i use this code but below it does not work:

        self.table1.headings = ['one', 'two']
        self.table1.data = [('1','2')]

It is possible to reinitialize a table widget ?

Thank you for your help.

## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)
python 3.7.1
* Toga
toga 0.30dev11

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version: Mojave
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [x ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the report. Is changing column headers currently possible? No - the API doesn't provide for changing column headers. Should it be possible? Yes. If you wanted to make an API proposal to make this possible, I'd be in favour.

**Comment by freakboy3742** [comment]
The ability to add columns was added in #820; #2011 modifies this to insert and remove columns.
