### ISSUE TITLE
Toolbar - Add/Remove/Reset/Manipulate it?

### ISSUE THREAD

**Issue by striderr** [beeware/toga#629]
Using 0.3.0dev11 on Windows.

I can add commands to the default toolbar but I'm struggling to remove the the disabled commands provided in the default toolbar.

The default toolbar is great but I have no use for the disabled commands and I don't know how to remove them or start with a clean toolbar so I can build my own.

Can code examples be added into the docs/demo for real world use cases?

Perhaps, how to create a new toolbar from a list of commands?  Or create a toolbar during app startup override?

Maybe have a remove command method?

Thanks.

**Comment by freakboy3742** [comment]
You're right - this is definitely an oversight. Adding `remove`, `clear`, and other set method analogs to `toga.core.command.CommandSet` would make sense.

**Comment by striderr** [comment]
Anyone coming across this, this is what I did to clear the toolbar.

```
cmd1 = toga.Command(self.exit, 'Exit', group=toga.Group("File"))

self.commands = toga.CommandSet(None) #this clears all toolbar commands
self.commands.add(cmd1)

def exit(self, widget):
    toga.app.App.exit(self)
```

**Comment by freakboy3742** [comment]
On reflection - I'm not convinced this is a good idea. The point of a toolbar is to surface a consistent set of commands; modifying that list of commands over the lifespan of the app is an anti pattern.
