### ISSUE TITLE
AttributeError: 'App' object has no attribute 'open_document'

### ISSUE THREAD

**Issue by IanDuncanT** [beeware/toga#643]
## Expected Behavior
No error

## Current Behavior
Receive following error on startup:
`
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rubicon/objc/api.py", line 232, in __call__
    result = self.py_method(py_self, *args)
  File "/Users/Me/Documents/Atom/YAPI/toga/src/cocoa/toga_cocoa/app.py", line 63, in application_openFiles_
    self.impl.open_document(str(fileURL.absoluteString))
AttributeError: 'App' object has no attribute 'open_document'
`

## Steps to reproduce
1. Download toga from source.

2. Run project on MacOS

## Your Environment

* Python Version: 3.7.0

* Operating System and Version:

  - [x] macOS - version: 10.14.3 Beta 18D39a
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target:
 
  - [ ] android
  - [x] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
We need a little more detail here, not just a stack trace - what version of Toga are you using, and what were you trying to run at the time?

**Comment by IanDuncanT** [comment]
Latest Dev version. I pulled it and installed it just before I got this issue. I have had this issue for multiple versions that were from source. The project I am running is: https://github.com/YetAnotherPackageInstaller/rewrite
This is running a gui that gives it on startup and seems to function alright.

**Comment by worship-together** [comment]
Had the same issue with the [your first toga app](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html) ('App' object has no attribute 'open_document').  Solution in our case is to run the app with python -m.  That issue went away.  Before doing that, we had to also do the following:

$ git clone https:///github.com/pybee/toga.git
$ cd toga
$ pip install src/core
$ pip install src/cocoa

**Comment by ikelca** [comment]
I had same issue if I run "toga-demo"
but with "python3 -m " I got following error

/usr/local/opt/python/bin/python3.7: No module named toga-demo 

Environment:

OSX 10.14.3
toga==0.3.0.dev11
toga-cocoa==0.3.0.dev11
toga-core==0.3.0.dev11
toga-demo==0.3.0.dev11

**Comment by d-lord** [comment]
Seeing the same behaviour in [tutorial 0](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html). I notice that it specifies:
>Toga apps must be executed as modules - hence the `-m` flag.

If there's no plan to change that, then I guess this is just how it is. 😄

**Comment by freakboy3742** [comment]
@d-lord The `-m` approach is the preferred way to start a Toga app. I'm not fundamentally opposed to supporting direct script execution as well, provided it can be done in a way that doesn't require overhead for the developer.

**Comment by IanDuncanT** [comment]
I am using this in a package manager where running with no arguments gives the gui. I would like to avoid using `-m` since it would change the command line arguments for those not using the gui. Is there any other way that should work. I may look at seperating the gui code into another file and when running the gui make a shell run it with `-m`.

**Comment by freakboy3742** [comment]
@IanDuncanT Makes sense; thanks for explaining the use case. 

To be clear - I don't have a *fundamental* objection to supporting both the with and without `-m` activation case; it's just a problem of working out how to differentiate between the two cases at runtime (because it changes other properties of the executing Python environment). In an ideal world, we'd support both - the fix just isn't obvious.

**Comment by freakboy3742** [comment]
Toga now supports `python foo.py`, `python  -m foo`, and `briefcase dev` as execution methods.
