### ISSUE TITLE
Documentation should be also CI'd

### ISSUE THREAD

**Issue by fingon** [beeware/toga#647]
## Expected Behavior

All (widget) documentation should have

- example code that works correctly
- screenshots of the widgets given example code (ideally on all platforms but even one would be enough)

Some way of doing automated documentation based on example code would be probably best, but I am not sure how hard that would be in practise.

## Current Behavior

Some of the documentation about widgets is out of date or incorrect ( at least against 0.3.0-dev, not sure if it matches the last release ).

**Comment by freakboy3742** [comment]
Can't disagree with this as a statement of requirements; the question is how to implement it. Just adding documentation *builds* to CI is easy enough - and it's already being done to publish to Read The Docs - but ensuring that documentation is *accurate* is much harder, especially when the framework is developing rapidly.

If you've got suggestions on how to integrate automated checks into the Sphinx pipeline, we're all ears. I know there is *some* ability to run example code as unit tests in Sphinx - but that's not well suited to *GUI* code. Toga has a "dummy" backend that might be useful here, but there's a lot of work to be done before that is truly useful.

**Comment by fingon** [comment]
Probably the nascent web based (‘Django’) might be best bet. Run those tests, include test code and produced html?

Probably considerable amount of work but might be worth it in the long run.

**Comment by freakboy3742** [comment]
Closing on the basis that a documentation build check is now part of CI; beyond that, this is a "moar Docs" request, which is completely valid, but won't be furthered by having an open ticket.
