### ISSUE TITLE
Python-cryptography version incompatible?

### ISSUE THREAD

**Issue by ohspc89** [beeware/toga#650]
Hello,

1. Following the tutorial and tried to run the app through django using the command mentioned in the tutorial page(python setup.py django -s)

2. Below is the message I get. It seems like the version mismatch is the only issue I have. App does not work.
running django
 * Writing application template...
Project template: https://github.com/pybee/Python-Django-template.git
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-django==0.3.0.dev11
  Downloading https://files.pythonhosted.org/packages/d7/e1/6296d7ab1a504c76f2e0ea4a441dff445ed4086304d1affe33f2d1142e38/toga_django-0.3.0.dev11-py3-none-any.whl
Collecting django-environ==0.4.1 (from toga-django==0.3.0.dev11)
  Downloading https://files.pythonhosted.org/packages/f4/06/8dd165534eae19e72ca78bd6e845566cd1e0aacc9c20cc43984675748345/django_environ-0.4.1-py2.py3-none-any.whl
Collecting django==1.10.6 (from toga-django==0.3.0.dev11)
  Downloading https://files.pythonhosted.org/packages/b9/bb/723f78e6f6aea78590331eba4e42b8a09c33ce154204a942525a91101d0b/Django-1.10.6-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 4.9MB/s 
Collecting toga-core==0.3.0.dev11 (from toga-django==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting six (from django-environ==0.4.1->toga-django==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-django==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
pyopenssl 19.0.0 has requirement cryptography>=2.3, but you'll have cryptography 2.1.4 which is incompatible.

## Your Environment

* Python Version 3.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [x] Linux - distro: ubuntu  - version:18.04
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [x] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
The Django backend for Toga needs to be completely rebuilt. The ability to support binary packages will be mostly driven by the mechanism used to get client-side Python working.

On that basis, I'm going to close this ticket, as there's nothing immediately actionable.
