### ISSUE TITLE
Add support for a unified development environment

### ISSUE THREAD

**Issue by Aareon** [beeware/toga#658]
To help keep coding style, documentation, and general conventions consistent throughout the project, I'd like to propose *suggesting* an "optimal" environment to contributors.

This environment would include;
 - [black](https://github.com/ambv/black)
 - [flake8](https://github.com/PyCQA/flake8)
 - [flake8-docstrings](https://github.com/PyCQA/flake8-docstrings)
 - [pipenv](https://github.com/pypa/pipenv)
 - [tox](https://github.com/tox-dev/tox)

This is sort of a start though. A production development environment *should* be consistent such that generally everyone is on the same page. Suggestions, questions, comments, and concerns welcome.

**Comment by Aareon** [comment]
Off-topic, but @freakboy3742 should we add PR labels for the different backends? As in, `core`, `android`, `cocoa`, etc.

**Comment by freakboy3742** [comment]
Agreed that clearly documenting the "standard" development environment is a good idea; however, I'm to my eyes, that's already the case. Our contribution guide describes how to set up a development environment.

Flake8 should already be being enforced by BeeFore checks; if it's not, that's a bug. Adding flake8-docstrings to that makes sense as well if you want to contribute that.

I'm still coming to terms with Black; in principle, I like what it's trying to do, but there are a couple of scenarios where completely automated formatting can lead to *less* readable code. If we *did* adopt it, I'd be looking to have it as an automated trigger so that PRs can't be submitted (or are automatically corrected) if they have formatting errors.

I'm not a fan of pipenv at all, so I'm not racing to add that into our suggested environment.

Tox won't make the testing scenarios that Toga is faced with any easier - the testing matrix is mostly affected by different operating systems, not Python versions.

**Comment by danyeaw** [comment]
I would love to see black added as well, it makes it sooo nice to be able to focus on the content. :+1: Did you mean not use black during a lint check, but actually change the formatting and commit a formatting change using the CI?

**Comment by freakboy3742** [comment]
I'm not 100% sure what best practice is with black these days - essentially, if we embrace black, I want to make sure that it's essentially impossible to submit a pull request that would be rejected for reasons of formatting.

**Comment by danyeaw** [comment]
I think the standard currently is that pre-commit is a dev dependency, add a black pre-commit hook, and then document to setup the development environment run `pre-commit install`. Then on the CI side we add `pre-commit run --all-files` to the lint phase of the CI pipeline. This will return a fail if it changes any files.

I am not sure how you would prevent or reject a pull request. I think GitHub has pre-receive hooks for the Enterprise version only that may be able to do something like this. Maybe we could use GidgetBot or even Beefore to get a bot or automated way to either close Pull Requests that don't pass the Lint stage (sounds maybe slightly harsh possibly) or remind them that they need to run the pre-commit hook.

**Comment by Aareon** [comment]
I entirely agree with
> automated formatting can lead to *less* readable code

but there are avenues one has that allows them the freedom of turning formatting off for as many lines as they need to keep the latter from happening, and it would be a judgement call by the contributor. If the judgment is unfavorable to the rest of the team, a review can be submitted to suggest turning off formatting for a specific chunk of code.

**Comment by Aareon** [comment]
Also, you could just run black over whatever commits and pipe the output through the bot as a review. Black does allow for only checking formatting vs. actually doing the formatting. This would be accomplished same as you're accomplishing flake8 checks

**Comment by Aareon** [comment]
> I'm not a fan of pipenv at all, so I'm not racing to add that into our suggested environment.

I respect this, it can quite an endeavor to truly get it working as you would like. However, I think perhaps we should consider an alternate means of dev environment package management besides `venv` as its not exactly the most future proof solution.

We also have the option of [Poetry](https://github.com/sdispater/poetry) and probably others that I can't remember right now.

For packaging this project, might I also suggest [Flit](https://github.com/takluyver/flit)?

**Comment by freakboy3742** [comment]
So - before we go rushing into adopting new tooling, we need to establish there's 
(a) actually a problem that needs solving, and (b) that the new tool will fix that problem.

Black is an example of something that definitely has (a), and also addresses (b). There are some caveats and side effects to (b) - hence my hesitation to switch immediately.

I'm yet to get a good description of the problem that pipenv and poetry are supposed to solve. There's one subcomponent of both those tools - package version locking - that looks potentially useful, but really only in the context of *deployments* (which means applications, not libraries). The rest of those tools I *actively* dislike - being forced to put 'pipenv run' in front of every command just so you can avoid typing "source venv/bin/activate" once... doesn't seem like an improvement of *anything*.

I have no idea what you're referring to when you describe venv as "not the most future proof solution". It's the virtual enviroment tool baked into Python itself. I fail to see how that could become a problem in the future.

And I'm not sure I see what moving to flit will gain us. "It's new" isn't a compelling reason to change everything. What capability do we *not* have that switching to flit would give us?

As for the suggestions - any suggestion is welcome; it's just difficult to process so many of them all at once, especially when it's not exactly clear what it is you're trying to achieve with the suggestion. Some of that comes from the way the suggestions have been posed - you've nominated tools, but haven't described the problem you're having that the tools will fix. There's a big difference between "We should use black" and "I find the process of getting code style feedback from the build system frustrating; black may be a way to avoid that". The latter is a concrete problem with a proposed solution; it's the starting point of a discussion. The former sounds like you've seen something shiny and are looking for an excuse to play with it :-)

**Comment by Aareon** [comment]
You raise a very valid point, I will try to do better in providing more information for future suggestions. As far as this issue goes, I think it's safe to say we'll probably need to re-attack this in the future whenever myself or someone else finds better reasons for incorporating any of these across the board. I appreciate your candor and your insight in regards to this.
