### ISSUE TITLE
[win32] Widget import regression

### ISSUE THREAD

**Issue by Aareon** [beeware/toga#661]
## Expected Behavior
`import toga` with no exceptions on Windows 10 (`win32` backend)

## Current Behavior
`toga_win32.widgets.box` is imported but not found

## Steps to reproduce
1. Clone master
2. Read `toga_win32/__init__.py`, where `box` is imported but does not exist. 

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [X] win32
  - [ ] Other (please specify)

This is possibly a regression, but I haven't had a chance to check the `git blame`. This regression likely occurred because of the star imports that occur in the `__init__.py` for this backend. This could have also been avoided with more tests against each backend, possibly.

I am only speculating at this time because I haven't had a chance to properly install Toga from source on my machine yet (Win10).

**Comment by Aareon** [comment]
Okay, after looking at the last most relevant commit for the `toga_win32` backend, it appears this is either an issue with a forgotten `git add`, or an oversight.

Source: https://github.com/beeware/toga/commit/e98ab5a900cdf409221438303a7f1006cbefc652

**Comment by Aareon** [comment]
I've got a lot to learn about `win32` before I'm able to add the `Box` widget effectively. Specifically, what the most effective route to implementing this box, as my girst instinct is to implement an adaptive rectangle draw. Like I said, lots to learn lol

**Comment by Aareon** [comment]
I just realized I'm a goof. I realize now that there is no render for `Box`. Still need to implement it for win32 though

**Comment by freakboy3742** [comment]
The win32 backend has been deprecated in favour of winforms.
