### ISSUE TITLE
[win32] Can't install from source/completely unusable

### ISSUE THREAD

**Issue by Aareon** [beeware/toga#662]
## Expected Behavior
Install `core`, `dummy`, and `win32`.

## Current Behavior
```cmd
$ pip install -e .\src\win32\

Obtaining file:///C:/Users/Aareon/Desktop/toga/src/win32
Collecting toga-core==0.2.3.dev1 (from toga-win32==0.2.3.dev1)
  Could not find a version that satisfies the requirement toga-core==0.2.3.dev1 (from toga-win32==0.2.3.dev1) (from versions: 0
.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.3.0.dev1
, 0.3.0.dev2, 0.3.0.dev3, 0.3.0.dev4, 0.3.0.dev5, 0.3.0.dev6, 0.3.0.dev7, 0.3.0.dev8, 0.3.0.dev9, 0.3.0.dev10, 0.3.0.dev11)
No matching distribution found for toga-core==0.2.3.dev1 (from toga-win32==0.2.3.dev1)
```

## Steps to reproduce
 - Clone `master`
 - Execute
    ```cmd
    $ pip install -e .\src\core
    $ pip install -e .\src\dummy
    $ pip install -e .\src\win32
    ```
3. See error

## Your Environment
* Python Version: 3.6.8 (64bit)
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)
  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [X] Windows - version: 10 (10.0.17763)
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [X] win32
  - [ ] Other (please specify)

## Possible issue
The issue *may* be resolved with a version bump in the `win32` backend.

**Comment by Aareon** [comment]
After bumping the version in `win32/__init__.py` to `0.3.0.dev12`, I was able to successfully install the `win32` backend. This raises the question; should a release be made if each backend isn't ready for said release?

**Comment by Aareon** [comment]
The `win32` backend still relies on `toga_cassowary`, which is no longer maintained. This means that the `win32` backend will require a lot more work than I originally thought.

**Comment by Aareon** [comment]
The work I am performing to rectify these issues can be found in https://github.com/Aareon/toga/tree/Aareon-win32-1

**Comment by freakboy3742** [comment]
The win32 backend has been deprecated in favour of winforms.
