### ISSUE TITLE
Select folder dialog method is not implemented, yet not caught with NotImplementedError

### ISSUE THREAD

**Issue by yingw787** [beeware/toga#678]
## Expected Behavior

At the moment, with PR #675, method `select_folder()` in dialogs.py for every native platform is only implemented in `toga_cocoa`, `toga_gtk`, and `toga_winforms` (doing a Ctrl + Shift + F). This implies that `toga_android`, `toga_curses`, `toga_django`, `toga_dummy`, `toga_flask`, `toga_iOS`, `toga_pyramid`, `toga_qt`, `toga_tvOS`, `toga_uwp`, `toga_watchOS`, `toga_web`, and `toga_win32` do not implement this method. These methods may fail with AttributeError saying that a class doesn't have a particular method, instead of a NotImplementedError or a TogaNotImplementedError saying that the method isn't implemented.

Since Python doesn't have the notion of interfaces, and given the amount of code written for `toga` already, one possible way forward may be to create a TogaInterface class at the interface level, implement stub methods raising NotImplementedError, and then subclass off of them for every source and re-implement the methods. That way, forward development will have a unified error model for all sources with unimplemented methods, and source drift can be minimized.

* Toga Target (the type of app you are trying to generate)
 
  - [X] android
  - [ ] cocoa
  - [X] django 
  - [ ] gtk
  - [X] iOS
  - [X] tvOS
  - [X] watchOS
  - [ ] winforms 
  - [X] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Most of the backends listed in this ticket have been moved to a nursery because of their nascent status.
