### ISSUE TITLE
Make toga asyncio compatible.

### ISSUE THREAD

**Issue by futursolo** [beeware/toga#68]
It is important to have operations non-blocking in GUI programming, or the application will become non-responsive during blocking I/O operations.

For traditional desktop languages like C or C++, we can use threads to allow multi tasks run concurrently to avoid the blocking operation block the GUI.

Unfortunately, in Python, we have the global interpreter lock that significantly slows down the multithread operations in some situations. 

In order to solve the drawbacks on multithreading in Python, since Python 3.4, Python introduced a new module called asyncio, which aims to solve the blocking operations in a new approach known as coroutine.

Toga is a new and exciting approach for cross-platform programming using Python. It would be better if Toga can make its event loop asyncio compatible, and make the handlers be able to become a coroutine function.

References:

https://github.com/python/asyncio

https://www.python.org/dev/peps/pep-3156/

https://www.python.org/dev/peps/pep-0492/

**Comment by freakboy3742** [comment]
Completely agreed that this is a desirable goal.

The problem is that there isn't a "Toga event loop" - Toga *itself* doesn't have an event loop; it uses the event loop of the underlying platform. So the question is how to integrate the CoreFoundation event loop and the GTK+ event loop and so on.

This is something that others have looked at; Twisted, for example, has support for both CoreFoundation and GTK+. So it is at least *notionally* possible. The devil lies in the detail.

**Comment by abhishekvermasg** [comment]
@futursolo I would like to work on this issue. Please give me some code pointers.

**Comment by futursolo** [comment]
@abhishekvermasg I think @freakboy3742 has already started working on it.

See:
https://github.com/pybee/rubicon-objc/blob/master/rubicon/objc/async.py
https://github.com/pybee/toga/blob/master/src/gtk/toga_gtk/app.py
https://github.com/pybee/toga/blob/master/src/cocoa/toga_cocoa/app.py

**Comment by freakboy3742** [comment]
I have done some work on this - asyncio now works on iOS, Cocoa and GTK. However, work is still needed on Android, Windows and Web. 

Android has a [Handler API](https://developer.android.com/reference/android/os/Handler.html) for event handling that is pretty much what is required, and is a reasonable analog of what iOS provides. [This blog post](http://www.mopri.de/2010/timertask-bad-do-it-the-android-way-use-a-handler/) might give you a point in the right direction on how to use the Handler API

I haven't done any exploration of what Windows provides, but Twisted's codebase might give you some pointers.

The Web backend needs a lot of work generally, so it probably isn't the best place to start.

The easiest piece to get started with is asyncio.sleep() - if you can get that working, you've got the event loop working; then you just need to work out the networking details.

The Android implementation will really be in VOC, as a support library; which means you may also need to devise a custom event loop for non-Android Java, and possibly one for Swing (in decreasing order of priority; but a "custom" event loop might help you work out some of the details before tackling Android.

**Comment by futursolo** [comment]
Also, I know it may not be the right place to discuss this, but I would like to point out that `async` is actually a keyword in Python 3.5+. To keep backward compatibility, Python didn't prohibit using `async` as a variable/module name; however, it's still confusing.

Python renamed `asyncio.async` to `asyncio.ensure_future` in Python 3.5. IMO, it's much clearer. Would toga consider renaming `rubicon.objc.async` to something like `rubicon.objc.asyncio_support`?

**Comment by freakboy3742** [comment]
@futursolo That's a good point that I hadn't considered. Could you open a separate ticket for this (and maybe even a PR to implement the rename)?

As for the name itself - is there any reason to not use `rubicon.objc.asyncio`? `asyncio_support` is a little cumbersome for my taste.

**Comment by futursolo** [comment]
In addition, for Cocoa & iOS implementation, I think it would be better to ask the user to set the `EventLoopPolicy` explictly and make the user to run the event loop explicitly than handling it implicitly when creating the Application as the other part of the program may call `asyncio.get_event_loop()` before the Application is initialized.

Consider:
```python
from toga_demo.app import main

import asyncio

@asyncio.get_event_loop().call_soon
def _run_after_app_started():
    print("Toga is awesome. It's working!")  # This will not work.


def run():
    main().main_loop()

if __name__ == '__main__':
    run()
```

It would be better if:
```python
from rubicon.objc.async import EventLoopPolicy as CFEventLoopPolicy  # See? The syntax highlight of async is messing with me.
from toga_demo.app import main
import asyncio

asyncio.set_event_loop_policy(CFEventLoopPolicy())

@asyncio.get_event_loop().call_soon
def _run_after_app_started():
    print("Toga is awesome. It's working!")

def run():
    main().register_life_cycle()  # assert isinstance(asyncio.get_event_loop(), rubicon.objc.async.CFEventLoop)
    asyncio.get_event_loop().run_forever()

if __name__ == '__main__':
    run()

```

**Comment by futursolo** [comment]
@freakboy3742 `rubicon.objc.asyncio` is fine, but the other modules under `rubicon.objc.*` namespace will not be able to access `asyncio` module from the stdlib unless you do `from asyncio import *` in `rubicon.objc.asyncio`.

Yea, I know `rubicon.objc.asyncio_support` is very cumbersome, but I couldn't come up with better names at that point of time.

How about `rubicon.objc.cf_loop`?

Also, I can definitely make a Pull Request, but I want to discuss with the project maintainers first to make sure that you guys agree with me.

**Comment by freakboy3742** [comment]
@futursolo Ah, of course - silly me!

Curiosity got the better of me, so I've just [pushed a PR](https://github.com/pybee/rubicon-objc/pull/89) with a rename to `eventloop` - that keeps the name nicely generic but still related to purpose.

The other suggestion about configurable event loop policies - sounds like a great idea. I can see how that would be very helpful for starting a background server accepting connections, or something similar. If you want to experiment with possibly API, please open a new ticket.

**Comment by Devilmoon** [comment]
Hey guys,
Really liking the project so far, but I've bumped into a wall recently - I would need to spawn a coro once a user clicks a button on a Toga window, but this freezes the app (which seems to be the problem described here if I'm not mistaken). Just to clarify, I'm on Windows atm, which is one of the platforms referenced to in here as still needing asyncio support.
Has this been implemented post v0.2.15? Currently using that version (through pip) and it doesn't seem to be working, just wondering if I should switch to master.

tagging @CalogeroMandracchia since he's interested as well

**Comment by freakboy3742** [comment]
@Devilmoon Ah - if you're on Windows, that's a problem at present. The 0.2 branch doesn't have asyncio support on any platform, and 0.3 only supports asyncio on macOS, iOS, and GTK. We're still working on Windows support (and would love any assistance from someone who knows the internals of the .net event loop and/or Windows networking...)

**Comment by Devilmoon** [comment]
Gotcha.

Unfortunately I don't have the knowledge necessary to implement it myself and do a PR!
For now I'm using a workaround by spawning a new thread when the user presses the button and doing my asyncio stuff in there, which seems to work.

Keep up the nice work, I'll do my best to give back to the project, even if only by recommending it to other people

**Comment by freakboy3742** [comment]
This has now been implemented; Toga is now fully integrated with asyncio.

**Comment by chrissimpkins** [comment]
> This has now been implemented; Toga is now fully integrated with asyncio.

Docs? Or at least PR where this was introduced?

**Comment by chrissimpkins** [comment]
> > This has now been implemented; Toga is now fully integrated with asyncio.
> 
> Docs/demos? Or at least PR where this was introduced?

https://github.com/beeware/toga/blob/master/examples/handlers/handlers/app.py for anyone else who comes across this thread.
