### ISSUE TITLE
Local beefore pycodestyle check result different than github

### ISSUE THREAD

**Issue by jess010** [beeware/toga#689]
When trying to do a PR for doc issues (see https://github.com/beeware/toga/pull/687), pycodestyle checks are failing in the github workflow, where they are passing locally by running 'beefore pycodestyle' in the terminal. Additionally, the items that it's failing for are not in the diff, it's a little weird.

I was going to have a go at fixing the issues found on github style check, and try again to see what happens, but the issues appear to relate to import statements, so I think this needs another pair of eyes on this.

See below for the difference:

**In terminal**

```  
* examples/imageview/imageview/app.py
    - file not in diff

  * examples/scrollcontainer/scrollcontainer/app.py
    - file not in diff

pycodestyle: Pre-commit check passed.
```

**[On beekeper log](https://beekeeper.beeware.org/projects/beeware/toga/change/d7b69e91-7a9c-4706-ab6f-e5d1b7ffba50/build/04d1c4fa-7d18-43c9-bfd1-0a1d385e6b32/task/beefore:pycodestyle)**
 
```  
* examples/imageview/imageview/app.py
    - Line 1 not in diff
    - Line 3, col 1: [F403] 'from toga.style.pack import *' used; unable to detect undefined names
    - Line 12, col 36: [F405] 'CENTER' may be undefined, or defined from star imports: toga.style.pack
    - Line 13, col 36: [F405] 'COLUMN' may be undefined, or defined from star imports: toga.style.pack

  * examples/scrollcontainer/scrollcontainer/app.py
    - Line 1 not in diff
    - Line 3 not in diff
    - Line 5, col 1: [E302] expected 2 blank lines, found 1
    - Line 9, col 31: [F405] 'COLUMN' may be undefined, or defined from star imports: toga.style.pack
    - Line 13 not in diff
    - Line 13 not in diff

pycodestyle: Pre-commit check FAILED.
```

Appreciate feedback on how I should address this for the purposes of the PR.

**Comment by danyeaw** [comment]
@jess010 In order to make Brutus happy I think you will need to get rid of the star imports in the modules that you are modifying.

**Comment by ConquerProgramming1** [comment]
Funny, I was noticing that today in the tutorials — I teach Python, and I always do an extended rant about star imports...

I guess I should go ahead and remove them from the tutorials...

 — Ron

**Comment by jess010** [comment]
Thanks @danyeaw. The checks went through on the PR, all good there.

I'm not sure what the root cause of the disconnect between local pycodestyle check and the checks run by brutus when pushed to github though, I'm assuming that this would still be considered an open issue.

**Comment by freakboy3742** [comment]
There have been a couple of fixes for beefore in the last year; I suspect they may have addressed this discrepancy.

That said, I think the real fix is to move away from beefore to a "vanilla" flake8 configuration - or better still, black (once a couple of lingering formatting issues have been addressed.)

**Comment by danyeaw** [comment]
Even with a few issues, moving to Black would be amazing :+1:
