### ISSUE TITLE
Submission testing should include building the docs

### ISSUE THREAD

**Issue by ConquerProgramming1** [beeware/toga#692]
I just submitted a PR due to some invalid Sphinx code causing a doc build failure. Since the docs can fail to build, seems like building the docs should be a part of submission testing (at least if something under /docs has been changed).

I'm willing to do this work when I can get to it, so posting this in part as a reminder for myself.

**Comment by freakboy3742** [comment]
Completely agreed that this is desirable. As a point of reference, both Briefcase and Rubicon-objc do this; the configuration might be useful as a point of comparison.

**Comment by saroad2** [comment]
As for now, this is done via `tox -e docs`, which is running on every PR.
Therefore, closing this issue.
