### ISSUE TITLE
Text in table cell rendering on top of adjacent cell

### ISSUE THREAD

**Issue by arichar6** [beeware/toga#700]
## Expected Behavior

When a table cell has content longer than the cell width, I expect the text to be "hidden" behind the adjacent column. Preferably there would be an ellipsis character (…) appended to the truncated text to indicate that text is hidden.

## Current Behavior

Using the cocoa backend for macOS, the text is rendered on top of the text from the adjacent column.

<img width="752" alt="Screen Shot 2019-05-24 at 4 31 29 PM" src="https://user-images.githubusercontent.com/758066/58355380-2da15580-7e42-11e9-8ec9-2ff2ffb5cb1f.png">

## Steps to reproduce

1. git clone most recent toga
2. cd to the directory for the table_source example
3. python -m table_source

## Your Environment

* Python Version: 3.6.7

* Operating System and Version 

  - [x] macOS - version:  10.14.4
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [x] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the report! Confirmed that this behavior is reproducible; it appears to be a bug in the cell renderer not clipping content to the box border.

**Comment by freakboy3742** [comment]
This has been significantly improved on by #822; however, I think there's room for more improvement.

The new code truncates text at the word boundary, but Cocoa has builtin support for text being truncated at the character level, and auto-inserting an ellipsis (...) when the text has been truncated - it even allows for automated squeezing of the kerning if slightly tighter spacing between characters will let a word fit. These features are part of NSTextField; I *presume* they're adaptable to NSTextFieldCell, but I can't say I can point to an obvious page of docs that says so.
