### ISSUE TITLE
Cannot set size of Window with resizeable=False

### ISSUE THREAD

**Issue by AllenDang** [beeware/toga#706]
## Expected Behavior
I want to create a window with fixed size. So created a window like this
`self.window = toga.Window(size=(400, 400), resizeable=False)`

## Current Behavior
Window shows like this

![屏幕快照 2019-06-12 下午12 47 09](https://user-images.githubusercontent.com/18550/59324138-3766fc00-8d10-11e9-90f4-d049ce99eaab.png)

## Steps to reproduce
1.`self.window = toga.Window(size=(400, 400), resizeable=False)`

## Your Environment
toga 0.3.0.dev11

* Python Version (list the specific version number)
python 3.7

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ x ] macOS - version: Mojave 10.14.5

* Toga Target (the type of app you are trying to generate)
 
  - [ x ] cocoa

**Comment by ignaciocabeza** [comment]
Hi @AllenDang, this issue is now fixed by #816

**Comment by freakboy3742** [comment]
(And you have @ignaciocabeza to thank for the fix!)
