### ISSUE TITLE
"Slightly Less Toy Example" from docs has truncated text on Windows

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#710]
## Expected Behaviour

To have text to the right of the text boxes to be fully visible.

## Current Behaviour

![image](https://user-images.githubusercontent.com/54418/61673901-337eb000-aca6-11e9-9d3b-b46c81e29b6e.png)

## Steps to reproduce

1. Run the example at https://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html on Windows 10.

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: 1903
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Interesting - that's different behavior to what I see. 

I'm wondering if this is a DPI-related issue - do you have any hi-DPI settings (or related font-sizing stuff) in place? Are you running on a 4K monitor? Anything else that might be affecting "default" widget sizing?

**Comment by freakboy3742** [comment]
Also - can you confirm the Toga version you're using? Toga 0.3.0.dev13 added explicit DPI handling, which might be the cause (or solution) to this problem.

**Comment by brettcannon** [comment]
@freakboy3742 it's Toga 0.3.0.dev12 (latest release at https://pypi.org/project/toga/#history). And the screen is probably considered high DPI.

**Comment by voltagex** [comment]
![image](https://user-images.githubusercontent.com/159567/63645910-5855bf80-c74b-11e9-99ca-1cb2cc8038da.png)

Can't reproduce here on a 3200x1800 screen @ 150% scaling

Toga 0.3.0.dev15 / 21dccb8d

**Comment by voltagex** [comment]
Sorry for the spam, I realised that even the "working" Windows example is truncated. Here's the same version of Toga on the same laptop using Ubuntu and GTK3:

![Screenshot from 2019-08-25 15-39-58](https://user-images.githubusercontent.com/159567/63646065-2c3c3d80-c74f-11e9-8ec1-8144a6722527.png)

**Comment by freakboy3742** [comment]
@voltagex Yeah - your Windows screenshot is definitely demonstrating the problem; although, interestingly, at a different scale to @brettcannon. I'm wondering if the size hints being provided to the label widget (and probably all other widgets) need to be adjusted for DPI somehow? (and if so... how...)

**Comment by voltagex** [comment]
Microsoft says you need to opt in for the newer Windows 10 DPI aware stuff.

I've raised https://github.com/pythonnet/pythonnet/issues/947 for this, hopefully I'm not too far off track.

**Comment by freakboy3742** [comment]
Ah - but there's the rub: we *are* opting in. This bug only emerged when we turned on the opt-in behavior. The relevant code is [here](https://github.com/beeware/toga/blob/master/src/winforms/toga_winforms/app.py#L24); the catch is that the return values from the hinting tools also need to change - it's just isn't clear how.

**Comment by voltagex** [comment]
@freakboy3742 Now I'm *really* confused. If you call Form().DeviceDpi inside the app, you get 96 back on a display that should return 144.

**Comment by freakboy3742** [comment]
TFW you discover [you were a little bit prescient in a code comment...]( https://github.com/beeware/toga/blob/master/src/winforms/toga_winforms/window.py#L11)

It appears that `self.dpi = self.native.CreateGraphics().DpiX` gives the right value (in the X axis, anyway...); however, we're not actually doing anything *with* the viewport's DPI. If we can adjust the relevant sizes (especially layout box sizes) by the scale factor, that should address the problem here.

**Comment by obulat** [comment]
I've tried 150% scaling and can reproduce this issue. It seems that only labels are affected. Menu, buttons, toolbars, tables, as well as labels in dialogs are not truncated.

**Comment by obulat** [comment]
At the moment, font units in Winforms backend are set, by default, in Points. What units do we use to set font in Toga? I couldn't find it in the documentation, but assume it's Pixels, so there was a mismatch. When I set the unit to Pixels, I get this at 150% scaling: 
<img width="330" alt="SlightlyLessToyExample" src="https://user-images.githubusercontent.com/15233243/64072373-f559b080-cc95-11e9-84e0-af89ebc86598.png">

**Comment by freakboy3742** [comment]
@obulat AFAIK, the font size *should* be in points - but I wouldn't place any large bets on us handling that size specification consistently.  :-)

Labels should be using the "default system size" unless specifically overridden with a style. Basd on that, the 150% scaling example that you have looks like to me like the label is too small; I would have expected the button text and the label text being the same size - or would that not be what you'd normally expect for Windows?

**Comment by obulat** [comment]
Yes, I do expect button text and label text to be the same size, and you are right that they don't look the same on my screenshot.

I think I found the reason why this happens, although I am not sure about the solution. 

After we create the Winforms implementation of a widget, we call `self.interface.style.reapply`, and the `pack` default style is applied. Which means that `size 12 system` font is set for label instead of Winforms default of 8 pt. I guess `pack` defaults should be the backend default, not just the same for all backends.

I also saw the same font behavior in `TextInput`, and I'm not sure which other widgets are affected.

This is the resulting window with the correct behavior on 150% scaling. 

<img width="256" alt="SlightlyLessToyExample150" src="https://user-images.githubusercontent.com/15233243/64320479-4daaee00-cfc7-11e9-828b-2149890411f8.png">

**Comment by freakboy3742** [comment]
Discovered the cause of this while debugging with @obulat - this is the demo actually working as expected :-)

The layout for the app hard-codes the width of the fahrenheit/celcius labels to 100px - which is plenty for most default layouts, but is a problem when high DPI scaling is applied.

There are two possible fixes here:

1) Include a DPI factor when interpreting pixel sizes. I'm not 100% convinced this is the right thing to do, but it would address the problem we're seeing. We need to work out a consistent story for dealing with DPI changes on a display; scaling sizes *might* be part of that story.

2) Change the layout of the demo itself. The 100px fixed size is being used to emulate a "grid" layout... and that's really pointing to the underlying problem - we need a grid layout mode.

**Comment by elelay** [comment]
Is there need for hidpi awareness in the gtk DetailedList for the icon size? It currently picks `Icon.SIZE[0]` so if this would be increased, it would work.

**Comment by freakboy3742** [comment]
Anyone who has seen this bug in the wild: I’d be interested in hearing your report as to whether the fix in #919 addresses the problem for you.
