### ISSUE TITLE
Win32 still in progress?

### ISSUE THREAD

**Issue by everettraven** [beeware/toga#711]
I’ll start this off by saying I’m new to the whole open source contributing, so I apologize if this isn’t the right place for this.

I would love to contribute to Toga and noticed that the Win32 src folder doesn’t have all the widgets implemented and in its README is says that it is not developed enough to run the demo. But, I noticed that on the Toga read the docs it states that if the  platform is win32 it will use winforms. 

So my question is does the Win32 src folder still need to be developed upon? If so, I would love to contribute to making some new widgets for it. If not, is there any other way I could contribute to the windows platform development?

**Comment by freakboy3742** [comment]
No problems - you've found the right place!

In all honesty, the win32 backend is probably not long for this world. Once upon a time, it was the only backend for Windows support. However, win32 is a very old Microsoft API, and definitely not their preferred API for new apps. Most recent Toga development has been on the winforms backend.

If you want to improve Windows support, the winforms backend will be a much more productive place to contribute. There are still plenty of widgets that need to be implemented (DetailedList is one that I can think of), and there are some features of some widgets that haven't been fully implemented. Winforms also doesn't have a implementation for document-based apps or full screen window support (these last two are requirements for getting [Podium](https://github.com/beeware/podium) working). 

Depending on your skillset, there are also some foundational issues that need to be resolved - for example, the integration of Python's asyncio event loop with the Winforms event loop. Addressing this is something that requires a bit of expertise with the guts of async programming, so it's not for the light hearted. But, if you're feeling adventurous, it would be a huge contribution to the project.

If you have any other questions, feel free to keep asking here; or jump on the [Gitter chat room](https://gitter.im/beeware/general) and we'll do what we can to provide whatever help you need.

**Comment by everettraven** [comment]
Thank you so much for your quick response! I will try and start with doing some of the unfinished winforms widgets and then look into doing the async programming piece as I’m not that well versed with async, although I know it would be great to help me learn it more in depth.

**Comment by everettraven** [comment]
Closing this issue as my question was answered.
