### ISSUE TITLE
Tutorial 3 - action_4 button issue

### ISSUE THREAD

**Issue by maramaraz** [beeware/toga#722]
## Expected Behavior
When pressing ```action_4``` button I expect to change the state of the ```action_3``` button from enabled to disabled or vice-versa.

## Current Behavior
While the state of the ```action_3``` button is changed at the interface layer, it seems like that change is not captured by either implementation or native layers of Toga so pressing the ```action_3``` button always yields the same result - script prints ```Action 3```.
Note: while running the app I was printing ```cmd3.enabled``` and it changes from ```True``` to ```False``` or vice-versa when ```action_4``` button is pressed.  

## Your Environment
I am running Toga on Ubuntu 16.04 with Anaconda Python. Virtual environment is made with ```conda``` instead of ```virtualenv```.

* Python Version - ```3.6.8``` from ```--conda-forge``` channel

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)
  - [ ] Linux - distro:   - version: Ubuntu 16.04

* Toga Target (the type of app you are trying to generate)
   - [ ] gtk

**Comment by freakboy3742** [comment]
Confirming I can reproduce this problem; thanks for letting us know!

This is a good candidate for a first time contributor - it's almost certainly a case where there's an option that is being interpreted incorrectly in the GTK backend.

**Comment by freakboy3742** [comment]
Resolved by #735.
