### ISSUE TITLE
alueError : Procedure probably called with too many arguments (4 bytes in excess) in example

### ISSUE THREAD

**Issue by mcxreeper** [beeware/toga#726]
## Expected Behavior
Run the example [here](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html) properly

## Current Behavior
No window appears and it spits out this:
`(venv) C:\Users\malic\PycharmProjects\VoursaApp>python -m main

Unhandled Exception: Python.Runtime.PythonException: ValueError : Procedure probably called with too many arguments (4 bytes in excess)
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

## Steps to reproduce
1. Make new pycharm project that has its own venv

2. Install beeware onto it using pycharm

3. Copy the code into main.py and try to run it with 'python -m main'

## Your Environment

* Python Version 3.7

* Operating System and Version 

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x ] Windows - version: 10.0.18362.239
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [x] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [x] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms 
  - [ ] win32 for testing
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the report! Some clarifications that will help us work out what is going on here:
* Are you actually using the win32 backend? By default, you *should* be getting the winforms backend; the win32 backend is effectively deprecated.
* Can you confirm the version of Toga that is installed in your virtual environment? You can confirm this detail with `pip freeze`
* Have you actually tried iOS and Android? I can tell you that you won't be able to deploy iOS from Windows - you need an macOS machine to compile iOS binaries. The Android backend is in a known-broken state at the moment; we've just got some grant funding to address this situation.

**Comment by mcxreeper** [comment]
- It's using winforms, I got confused

- `pip freeze` gives this:
`arrow==0.14.5
beeware==0.1.1
binaryornot==0.4.4
biplist==1.0.3
boto3==1.9.213
botocore==1.12.213
briefcase==0.2.9
certifi==2019.6.16
chardet==3.0.4
Click==7.0
cookiecutter==1.6.0
dmgbuild==1.3.2
docutils==0.15.2
ds-store==1.1.2
future==0.17.1
idna==2.8
Jinja2==2.10.1
jinja2-time==0.2.0
jmespath==0.9.4
lxml==4.4.1
mac-alias==2.0.7
MarkupSafe==1.1.1
poyo==0.5.0
python-dateutil==2.8.0
pythonnet==2.4.0
requests==2.22.0
s3transfer==0.2.1
six==1.12.0
toga==0.3.0.dev13
toga-core==0.3.0.dev13
toga-winforms==0.3.0.dev13
travertino==0.1.2
urllib3==1.23
voc==0.1.6
whichcraft==0.6.0`

- I'm planning on testing the mobile platform later after I get familiar with it in windows

**Comment by freakboy3742** [comment]
Ah - I think I know what you're getting - You've been bitten by a subtle change that only exists in the most recent Windows versions.

This was reported (and fixed) about a week ago; #717 contains the fix. 

I obviously need to get a new release of Toga out ASAP to ensure others don't get bitten in the same way that you have been. 

In the meantime, if you wish, you can use the [getting started instructions for contributors](https://toga.readthedocs.io/en/latest/how-to/contribute.html) to install the current development version. That *should* fix this problem.

**Comment by mcxreeper** [comment]
Thanks for the quick reaction

**Comment by freakboy3742** [comment]
FYI: I've just pushed 0.3.0.dev14 which should include the fix for this problem.
