### ISSUE TITLE
FYI, linux: PyGObject 3.32.2 emits tracebacks 

### ISSUE THREAD

**Issue by eliotb** [beeware/toga#729]
This is really an FYI that PyGObject 3.32.2  (current as of 20190825) has a bug in it that is fixed by unreleased 3.33.1.dev0 (as of 20190825). So not a Toga bug.  However, users of Toga may see it and wonder...

## Expected Behavior

No tracebacks in the terminal window.

The tracebacks can be avoided in the mean time by forcing install of .dev version .e.g

`pip install pygobject==3.33.1.dev0`

## Current Behavior

PyGObject 3.32.2 emits this traceback on every slide transition in podium, using Toga.  
```
Exception ignored in: <function Source.__del__ at 0x7f28e08ba9d8>
Traceback (most recent call last):
  File "/home/eliot/.local/share/virtualenvs/beeware/lib/python3.7/site-packages/gi/overrides/GLib.py", line 530, in __del__
    super(Source, self).__del__()
AttributeError: 'super' object has no attribute '__del__'
```

## Steps to reproduce
Run  podium with example slides on linux. Step through the slides. View console.
## Your Environment

* Python Version (list the specific version number)
3.7

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [x ] Linux - debian - 10
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
21dccb8d7e6ad

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [x ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the note. Would it be worth adding a version exclusion to the install requirements for toga-gtk?

**Comment by eliotb** [comment]
I don't know if selecting an earlier version would bring in different bugs that have been fixed in 3.32.2 ...
The tracebacks don't seem to stop e.g. podium from working.

**Comment by freakboy3742** [comment]
Interesting... I've just tried this on my Ubuntu 18.04 box, but don't see this problem. I wonder if it might be Debian 10 specific?

**Comment by eliotb** [comment]
Agh *&^! sorry.
After futzing around with various venvs, and installing multiple versions of pygobject, I can't reproduce the problem either.
Given that it is/was not fatal, we've both probably spent more than enough time on this one :/

**Comment by freakboy3742** [comment]
No worries! I'll close this ticket then; if anyone else works out how to reproduce it, we can reopen (or open a new ticket)
