### ISSUE TITLE
Unable to Build Android

### ISSUE THREAD

**Issue by shivjeetbhullar** [beeware/toga#758]
* Building test...

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by freakboy3742** [comment]
This is a known problem; we have a contractor actively working on Android support right now under a grant from the PSF.
