### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_impl'

### ISSUE THREAD

**Issue by UncleGoogle** [beeware/toga#760]
toga==0.3.0.dev14 on Windows10 gives me error in title.
Repro:

```python
class MinimalApp(toga.App):

    def button_handler(widget):
        print("hello")

    def startup(self):
        box = toga.Box()

        button = toga.Button('Hello world', on_press=self.button_handler)
        button.style.padding = 50
        button.style.flex = 1
        box.add(button)

        return box


if __name__ == "__main__":

    app = MinimalApp('Name', 'com.hb.er')
    app.main_loop()

```

```
         self.interface.main_window._impl.native.Controls.Add(menubar)
AttributeError: 'NoneType' object has no attribute '_impl'
```

**Comment by afmaster** [comment]
I'm facing the same problem here. What I need to do in order to prevent this error. Thank you.

`import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class Pyssword(toga.App):

    def startup(self):



        main_box = toga.Box(style=Pack(direction=COLUMN))


        # USERNAME

        name_label = toga.Label(
            'Username: ',
            style=Pack(padding=(0, 5))
        )
        self.name_input = toga.TextInput(style=Pack(flex=1))

        name_box = toga.Box(style=Pack(direction=ROW, padding=5))
        name_box.add(name_label)
        name_box.add(self.name_input)



        # PASSWORD

        pass_label = toga.Label(
            'Password: ',
            style=Pack(padding=(0, 5))
        )
        self.pass_input = toga.TextInput(style=Pack(flex=1))

        name_box_2 = toga.Box(style=Pack(direction=ROW, padding=5))
        name_box_2.add(pass_label)
        name_box_2.add(self.pass_input)

    def say_hello(self, widget):
        print("Hello", self.name_input.value)


        button = toga.Button(
            'Enviar',
            on_press=self.say_hello,
            style=Pack(padding=5)
        )

        main_box.add(name_box)
        main_box.add(name_box_2)
        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()



def main():
    return Pyssword()`

**Comment by freakboy3742** [comment]
The solution here is much the same as the OP discovered. Startup needs to create a main window; your main window is created in the `say_hello` method, which isn't ever invoked. 

You've also got the button handler for the Enviar button pointing back to the same method where the button is defined, which... is going to lead to some interesting recursive behavior.

On Toga's side, catching the "no main window" case would be a useful (and relatively straightforward) error to catch here.

**Comment by afmaster** [comment]
Thank you @freakboy3742 . I'm sorry for deletion of my post. I've deleted before refreshing the page and seeing your post. Thank you again.

**Comment by mattip** [comment]
Looking at this issue, it seems `startup()` is called in the platform-specific invocation of `self.interface.startup()` which does not expect a return value. One way to solve this would be to add a check that `self.main_window` is valid after the call. As I understand it, this would need to be done on each platform:
```
git grep "self.interface.startup()"
android/src/toga_android/app.py:        self.interface.startup()
cocoa/src/toga_cocoa/app.py:        self.interface.startup()
gtk/src/toga_gtk/app.py:        self.interface.startup()
iOS/src/toga_iOS/app.py:        self.interface.startup()
web/src/toga_web/app.py:        self.interface.startup()
winforms/src/toga_winforms/app.py:        self.interface.startup()
