### ISSUE TITLE
Question about ImageView styling

### ISSUE THREAD

**Issue by SamSchott** [beeware/toga#780]
@freakboy3742, I have been looking at the ImageView widget and wondering about implementing some styling such as alignment, frames, etc. I have seen in the src that you have already stubs of commented-out code for alignment.

This has raised a question for me: when should properties be determined by the given `style` and when should they be given as properties of the widget itself?

**Comment by freakboy3742** [comment]
Alignment and scaling strategy is definitely something we should support in some way - how images scale and shift inside their allocated space is something that is a universal property of image display.

I'm a little less convinced about frames... These are so platform specific, and my experience as a user is that they tend not to be used in modern UI designs anyway. Unless you can find a consistent subset across all platforms that exists everywhere, I'm inclined to ignore frames (outside the bare minimum needed to support "no frame").

As you've noted, these are properties that should be captured by the style language. Don't read too much into the stubbed out methods that are there and commented out; they're more of a thought placeholder than a considered design. The handling of font and text alignment in Label widgets are a better model to follow here.

As a more broad guideline on API design: "if I was building this as a web page, is this something that would be configured with CSS?" If the answer is yes, then it's something that is the domain of the style language; if it's something that would be done in JS, then it should be a programmatic API.

**Comment by SamSchott** [comment]
Ok, this makes sense. If I find some time, I will look into implementing some of this. But it will be difficult for me since I am neither very familiar with the Pack language nor with the frameworks from different platforms.

**Comment by freakboy3742** [comment]
Closing this since it was a question which now appears to have been answered, and there's no other concrete call to action.
