### ISSUE TITLE
Tab Bar Controller feature request

### ISSUE THREAD

**Issue by BrendanSimon** [beeware/toga#786]
On iOS, to have native look and feel, a TabBarController and TabBar needs to be implemented. Common examples are the iOS Music, Photos, Phone, App Store apps.  Third party apps such as FaceBook, FireFox, eBay, etc.

https://developer.apple.com/documentation/uikit/uitabbarcontroller

https://developer.apple.com/documentation/uikit/uitabbar

This needs to be abstracted to a common Toga API. I presume Android has something similar.

Windows and macOS might have toolbars, or ribbons or other widgets.

**Comment by freakboy3742** [comment]
Toga already has an OptionContainer widget; this would seem to be the match for the iOS UITabBar - a top level widget for switching between multiple "tabs" of content.

Closing this ticket on the basis there's already a toga.core API for this feature, and tickets aren't an especially effective way of coordinating efforts around specific platform implementations of widgets.

**Comment by BrendanSimon** [comment]
Ok.  Seems like a reasonable fit.

Do the mobile implementations of a widget limit Toga for other platforms (e.g. Desktop)?

I get the impression that iOS `UITabBar` is probably always at the bottom of the screen.  Is that true, or can it placed elsewhere (e.g. bottom of Toga `Box`)?

If I want a Desktop app had that had to `OptionContainer` widgets in a window (e.g. in each half of a split screen), could I achieve the same thing in a phone or tablet app?

Would `UITabBar` be the right fit, if it had constraints that there could only be one of them at the bottom of the screen?

The implementation variants might be:
* use multiple screens on the phone/tablet app (this could be annoying).
* create higher level custom widgets, that mimic the look-n-feel of the native widget, but are placeable anywhere in a Toga `Box` as an ordinary Toga `widget`.

Sometimes I might want the phone/table app to look and behave similar to the desktop app, and sometimes I might want to adapt to something different that works better on the target.

Neither one is right or wrong, and the best solution would depend on the context of the UIX.

Do you agree?

How would/should Toga implement these variants - as an `OptionContainer` keyword option or a new class?

**Comment by freakboy3742** [comment]
In short, no - I don't agree.

Toga is an abstraction API. As such, it's simply not possible to support all possible appearances on all possible platforms without compromising either the API, or the usability of the final app.

The end goal of Toga is *not* to make it possible to design all possible apps, with all possible user interfaces. *No* abstraction API is going to give you extreme flexibility of that kind. If you want a finely tuned user experience with specific controls, then you should be writing directly to the widget toolkits for the underlying platforms. Altenatively, you can use a "native nowhere" API (e.g., Kivy). That way, you end up with an interface that is *consistent* across all platforms - but the price you pay is that the app doesn't feel native on *any* platform.

To that end, the "make this mobile app behave like a desktop app" use case is a use case I have no interest in supporting. Having tabs at the top of a container widger would feel alien on mobile, and having them at the bottom would feel alien on desktop. 

The underlying use case for an Option Container is "a top level organization widget, providing the ability to switch between multiple tabs of content that consume the entire content area". Each platform has native and natural ways to express that concept. The *location* of the tabs is not a relevant part of that design statement - that's a platform-specific implementation detail.

**Comment by BrendanSimon** [comment]
Ok.  I think I can get most of what I need by using the iOS `UIPageControl`, which effectively gives a view of various parts of a larger form.  This works for phones as usually there is only enough real estate for a limited set of controls (e.g. a  single list, or date picker, etc).

Tablets are interesting as they have more real estate.

One of Toga's goal is single source, multiple target platforms.  I'm wondering how you would specify or architect things so that a tablet app doesn't look like a phone app.  Perhaps that's not a goal or concern of Toga?

Toga could also potentially expose the low level wrapper interface for each target to the programmer.  The programmer could then do special things if required - even write the app with `if target == iOS ... elif target == Android ...`.

The developer is not compelled to use the low level API at all, and for the most use cases is not encouraged to, but it's there for those who want it - e.g. just writing an app for iOS only ... but with Python, or want to throw in the odd special feature/widget here and there (API would have to be compatible with main Toga API - e.g. Box layout engine, etc).

It's just a thought - it may or may not be possible ??

**Comment by freakboy3742** [comment]
This problem is exactly what I was driving at when I was referring to Toga's design philosophy in the discussion about ImageView. There's isn't a way to define a GUI in terms of specific widgets that also behaves appropriately on all platforms. However, it *is* possible to capture high level modes of interaction. 

If you define your GUI in terms of a Tree and a split pane and a specific layout of boxes, then yes, your GUI will need "if target== iOS" (or, at least, if target == mobile) gated logic - but if you can define the high level interactions - (e.g., selecting from a heirarchy to show detail) then the underlying implementation can shift to match the platform.

**Comment by BrendanSimon** [comment]
Sure, but is that what Toga does at the moment?  Doesn't Toga uses boxes to define layouts of widgets?  Are you suggesting Toga apps should ideally not require Box layouts?

Maybe that's still ok, as long as the end widget (Toga level) describes the data and behaviour "hints", and then something maps it to the target widgets.

**Comment by HK416A5** [comment]
Hello! I want to use the `optioinCintainer` widget to add tab views to my app, when I type `briefcase dev`, it works fine on Windows systems, but after I type`briefcase package android`, and install it on my android phone and open it, there is nothing appeare on my screen but a title of the app...How could this happen? Is there something wrong? How can I add tab views to my android app?

**Comment by freakboy3742** [comment]
@HK416A5 OptionContainer hasn't been implemented on Android yet. What you're seeing is the app crashing because the requested widget doesn't exist. There's nothing you can do *right now*, other than "offer to implement OptionContainer".

**Comment by HK416A5** [comment]
@freakboy3742 Thanks for your reply! I am new to Python and Beeware, you help me a lot and the Beeware is amazing!! Thank you very much!
