### ISSUE TITLE
AttributeError: type object 'Icon' has no attribute 'TIBERIUS_ICON'

### ISSUE THREAD

**Issue by devops724** [beeware/toga#794]
## Expected Behavior

start toga demo

## Current Behavior

return this error:
$ toga-demo
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: SplitContainer.set_direction()
Traceback (most recent call last):
  File "/home/hosein/workspace/game_projects/Launcher2/env/lib64/python3.7/site-packages/toga_gtk/app.py", line 91, in gtk_startup
    self.interface.startup()
  File "/home/hosein/workspace/game_projects/Launcher2/env/lib64/python3.7/site-packages/toga_demo/app.py", line 66, in startup
    cmd2 = toga.Command(self.action2, 'Action 2', tooltip='Perform action 2', icon=toga.Icon.TIBERIUS_ICON)
AttributeError: type object 'Icon' has no attribute 'TIBERIUS_ICON'

## Steps to reproduce

1. start toga-demo

2.

3.

## Your Environment

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne

* Python Version (list the specific version number)
Python 3.7.6

$ pip freeze
certifi==2019.11.28
chardet==3.0.4
docutils==0.16
gbulb==0.6.1
idna==2.8
importlib-metadata==1.4.0
Kivy==1.11.1
Kivy-Garden==0.1.4
more-itertools==8.1.0
pycairo==1.18.2
Pygments==2.5.2
PyGObject==3.34.0
requests==2.22.0
toga==0.3.0.dev18
toga-core==0.3.0.dev18
toga-demo==0.3.0.dev18
toga-gtk==0.3.0.dev18
travertino==0.1.2
urllib3==1.25.8
zipp==2.0.1

**Comment by freakboy3742** [comment]
Thanks for the report - this is an oversight that wasn't caught in release testing. I'll submit a fix shortly, which will be rolled into the next release.
