### ISSUE TITLE
Table.data = data is inserting data above old data

### ISSUE THREAD

**Issue by danshorstein** [beeware/toga#798]
## Expected Behavior
I'm trying to replace the data in a Table object to refresh it with live data. 
table = toga.Table(headers['1', '2'], data=[['a', 'b'], ['c', 'd']])

I'd expect the table to only reflect the new data passed in,
table.data = [['e', 'f']]
should be reflected as:
  1  2
  e  f 

## Current Behavior
Currently when I run table.data = [['e', 'f']], it inserts the new data at the top, but does not delete the old data. It makes it look like:
 1 2
 e f
 a b
 c d

## Steps to reproduce
See above

## Your Environment

* Python Version (list the specific version number)
Python 3.7.6
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version:10
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
'0.3.0.dev18'

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [x] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
@danshorstein Thanks for the report! That definitely looks like a bug, and it looks like it's Windows specific. The problem is that the `change_source()` method on the winforms backend (the method that is invoked when the data source for the widget changes) *doesn't* call `clear()`. I'll add a fix.
