### ISSUE TITLE
[feature suggestion] drag-and-drop utilities

### ISSUE THREAD

**Issue by deepio** [beeware/toga#805]
I have been looking for this type of functionality in togas documentation and could not find it, there are two types of drag-and-drop I would like to see. 

* Dragging and dropping a file from the desktop into the main window or a specific area should pass the string representation of the filepath to a `toga.App` class method, for custom handling functions (like opening a file for editing, uploading a file, etc). Thought maybe this is part of the roadmap?
* Clicking and dragging on the screen should write to `toga.Canvas` like using a paintbrush in a Paint app, or custom reordering of table elements like rearranging files and folders in a filebrowser window (Explorer, Finder, etc.) Different functionality for buttons, for example, clicking and holding makes the object movable while double-clicking executes a function.

Even if it's not natively supported, I also looked around to try and implement it if there was any keyboard hooks or mouse position information.
* How do we get keypress context? What about getting mouse position information? 

Would it only be possible if I wrote a webview and javascript event handlers?? Simultaneously deploy a localhost site and view it with the webview? Feels like a very roundabout way but it might work... 

https://toga.readthedocs.io/en/latest/reference/api/widgets/webview.html#toga.widgets.webview.WebView.evaluate_javascript

**Comment by S1SYPHOS** [comment]
I'm just finding this now: has there been any solution to this, @deepio?

**Comment by freakboy3742** [comment]
@S1SYPHOS Unfortunately no - Toga doesn't have any DnD apis at present.

**Comment by S1SYPHOS** [comment]
Alright, thanks for letting me know!

**Comment by freakboy3742** [comment]
@sean078 No - DnD support isn't on our radar at the moment. You can track our roadmap by following [the Beeware blog](https://beeware.org/news/buzz/) - we post quarterly roadmaps where we list what we're planning to work on.
