### ISSUE TITLE
Tutorial 4 does not draw anything except from text

### ISSUE THREAD

**Issue by yconst** [beeware/toga#815]
## Expected Behavior
Tutorial 4 should draw Tiberius along with text and a box around it

## Current Behavior
Tutorial 4 only draws text - no error is output, only the following message:
`[Cocoa] Not implemented: Canvas.on_resize`

## Steps to reproduce

1. Create a new Conda environment using Python 3.7.6

2. Install toga as outlined in https://toga.readthedocs.io/en/latest/how-to/contribute.html

3. Paste the code found in https://toga.readthedocs.io/en/latest/tutorial/tutorial-4.html into tutorial4.py

4. `python tutorial4.py`

## Your Environment

* Python Version 
Python 3.7.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [X] macOS - version: 10.15.2 (19C57)
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version 
b40f067db6af099cf486166bfc74fc8c9e56decf

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [X] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the report!

The "on_resize" message is to be expected; that's not an error, just a warning that resize features aren't fully implemented on Cocoa.

However, it's odd that you're seeing the text, but not the rest of the image. That's not a behavior that I've seen before, and I haven't been able to reproduce it in my own testing. The only notable difference between your system and mine is the version of macOS - I'm still on 10.14 - but I wouldn't have thought that would be the cause...

Is there anything else that might be considered notable about your setup?

**Comment by yconst** [comment]
It's a clean Conda environment with just toga, pyserial and msgpack installed. Nothing else noteworthy really.. Has Toga been tested on the latest MacOS?

**Comment by freakboy3742** [comment]
*I* haven't tested it on 10.15, but I believe others have. 

Any assistance you can provide would be gratefully accepted. Are you able to confirm (dropping print statements into the codebase would be enough) that the Toga canvas drawing commands are actually being executed? Knowing whether the commands are executing, but not doing anything vs failing silently would be a good starting point.

**Comment by yconst** [comment]
Fixed in #817

**Comment by freakboy3742** [comment]
Thanks for the investigation work on this! As noted on the PR, it like we can completely transition to CGContext - it's been available for a while, so we might as well use it.
