### ISSUE TITLE
[winforms] No text in Table Source demo

### ISSUE THREAD

**Issue by yconst** [beeware/toga#824]
## Expected Behavior
Table in Table Source demo is properly rendered with text in Windows 10

## Current Behavior
Table in Table Source demo is rendered but no text appears in the cells. The rows can still be highlighted which means that they exist just the text does not appear.

I suspect this is because `Winforms.ListviewItem` expects strings as parameters.
Changing `winforms/widgets/table.py:28` and `winforms/widgets/table.py:36` to:
` str(getattr(row, attr)) for attr in self.interface._accessors`. 

makes the text show up. The table_source demo data sources convert data to int for filtering and sorting, thus the problem appears. This also makes sense since the regular table demo (no listsource) displays text as it should.

## Steps to reproduce

1. Install latest dev Toga as instructed in website

2. cd to `table_source` example

3. `python -m table_source`

## Your Environment
Windows 10
Anaconda 2019.10 for Windows

* Python Version (list the specific version number)
Python 3.7.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [X] Windows - version: 10 x64 (1903)
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
b8c23416b48f9429d38b403068baafd794ae4021

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [X] winforms
  - [ ] win32
  - [ ] Other (please specify)

.

**Comment by freakboy3742** [comment]
Thanks for the report! Your diagnosis looks also correct. The underlying problem is that the Winforms table implementation doesn't currently support icons in tables.

There are at least two possible fixes here:

1. An immediate workaround: Modify the Winforms backend to strip the "tuple" format back to plain text. 

2. The "complete" fix: work out how to render icons in a Winforms table.

**Comment by yconst** [comment]
2 is definitely the way to go long term; however since this is an important bug that essentially prevents the use of datasources in windows, I'd suggest a workaround as a temp fix.
