### ISSUE TITLE
Cannot use colors on winforms

### ISSUE THREAD

**Issue by Nanush7** [beeware/toga#829]
## Expected Behavior
Using the packer color attribute to change the color of a Label.

## Current Behavior
No color displayed, no errors, widget still gets displayed.

## Your Environment
```python
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW

class AppName(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        self.id_error = toga.Label(
            'Error',
            style=Pack(visibility='hidden', text_align='center')
        )
        error_box = toga.Box(style=Pack(direction=COLUMN, padding=5))
        error_box.add(self.id_error)

        main_box.add(error_box)
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()
```

* Python Version: 3.7.6

* Operating System and Version

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: Windows 10 Pro 1909
  - [ ] Other - name:  - version:

* Toga Version: 0.3.0dev18

* Toga Target

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [x] Other (please specify): Desktop app (Windows) --> I don't know if this is win32 or winforms.

**Comment by freakboy3742** [comment]
Thanks for the report! There's a lot of features on the winforms backend that aren't currently supported - changing colors is one of them. However, this isn't reported in the same way as it is with other missing features, so the confusion is understandable.

(And - for future reference: you're using the winforms backend. We're in the process of deprecating the win32 backend).

**Comment by Nanush7** [comment]
Ok, thank you for the response.

**Comment by saroad2** [comment]
Will be solved on my pull request #844

**Comment by freakboy3742** [comment]
Closing as the feature now exists.

**Comment by MicBoucinha** [comment]
Sorry for commenting on a closed issue but I am currently trying Toga and I am having this exact issue in the latest version (v0.3.0.dev22 on Windows 10 2004). 

Although through Toga's code, both `color` and `background_color` (which the linked #844 PR adds) are implemented, I am unable to change color.

```python
    def startup(self):
        """
        Construct and show the Toga application.

        Usually, you would add your application to a main content box.
        We then create a main window (with a name matching the app), and
        show the main window.
        """
        main_box = toga.Box()
        label = toga.Label("Hello World", style=Pack(color="yellow"))
        main_box.add(label)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()
```

I created this hello world app following briefcase tutorial. 

Can anyone confirm please what I might be doing wrong?

Thanks!

**Comment by MicBoucinha** [comment]
So... I found the issue.

The changes on `src/winforms/toga_winforms/widgets/label.py` that are on the master branch that allow that functionality to work (both `color `and `background_color`), were made after the latest `v0.3.0dev22` release tag which is installed.

Apologies for not noticing it before posting but it might help someone in the same situation as I was.
