### ISSUE TITLE
AttributeError: 'CSS' object has no attribute 'bind'

### ISSUE THREAD

**Issue by Hassan-Mallah** [beeware/toga#831]
Hey
## Expected Behavior

The app is running, but there's no interface, I'm trying "Your First Toga app"
https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html

## Current Behavior

Error: AttributeError: 'CSS' object has no attribute 'bind'
## Steps to reproduce

i followed all the steps many times and the same error

## Your Environment

* Python Version (list the specific version number)
Python 3.6.9

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:  - [+ ] Linux - distro:   Ubuntu - version: 18.04
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
0.2.15
* Toga Target (the type of app you are trying to generate)
I dont know :)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

Cheers

**Comment by freakboy3742** [comment]
Hi! Looks like you've missed passing in the `--pre` flag to pip when installing Toga. The 0.2.15 is the current "stable" version of Toga; however, all active development has been on the 0.3 branch for the last 2 years. The default tutorial reflects the API from the 0.3 branch.

If you run `pip install --upgrade --pre toga` you should have more success.

**Comment by Hassan-Mallah** [comment]
Great, it's working :)
Thank you very much
