### ISSUE TITLE
Add support for iOS darkmode

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#856]
iOS 11 added Dark Mode; however, Toga doesn't honor dark mode defaults when setting up widgets.

Toga should identify when the app is running in dark mode, and use appropriate background/foreground colors instead of defaulting to dark text/light background.

**Comment by isaingard** [comment]
PR submitted for review

**Comment by freakboy3742** [comment]
This looks like it should have been fixed by #959; if anyone finds evidence to the contrary, we can re-open this ticket with details.
