### ISSUE TITLE
Add support for macOS darkmode

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#857]
macOS 10.14 (Mojave) added Dark Mode; however, Toga doesn't honor dark mode defaults when setting up widgets.

Toga should identify when the app is running in dark mode, and use appropriate background/foreground colors instead of defaulting to dark text/light background.

**Comment by SamSchott** [comment]
Could you add examples of widgets that currently have hard-coded colours which do not honour dark mode? Most widgets seem to work just fine.

**Comment by freakboy3742** [comment]
I was going off [this report](https://github.com/beeware/briefcase-macOS-app-template/issues/2) as a starting point, and assumed at least some of the problem would lie with Toga. It's possible that it may be entirely a Briefcase packaging issue, though. 

If that's the case, then we can close this ticket, and move all the activity over to briefcase template ticket.

(Side note - I created this ticket, and a bunch of others, because we're [sprinting this weekend](https://docs.google.com/forms/d/e/1FAIpQLSfHR4VoTzLXzB_owUpQjCs363FaXMu3HI1KI5UWZFzmh5072A/viewform); if you've got spare time, we'd love to see you there!

**Comment by SamSchott** [comment]
I strongly suspect that this is a packaging issue. I've been packaging a toga app with PyInstaller (there was some issue with briefcase and a dependency which I don't quite recall at the moment) and getting dark mode to work required explicitly setting the `NSRequiresAquaSystemAppearance` flag to false in the info.plist for macOS < 10.14. For macOS >= 10.14, dark mode support should come automatically.

For PyInstaller however, I needed to rebuild the bootloader myself with a `MACOSX_DEPLOYMENT_TARGET=10.13` or higher (overriding the PyInstaller default of 10.7) for dark mode to work. That also solved some other appearance issues with the Tree widget in the packaged app.

I assume that briefcase uses some form of precompiled Python interpreter as well and may face similar issues.

Also, thanks for invite to the sprint! But its unlikely that I will find the time this weekend :/

**Comment by kzys** [comment]
Resolved?

According to https://github.com/beeware/briefcase-macOS-app-template/issues/2

> From my testing, this was enabled automatically when we moved to the binary-based bootstrap.

Also my app which is running from `briefcase dev` honors dark mode and can change colors dynamically when I change that from Preferences.

**Comment by samschott** [comment]
Yes, this has been resolved. Thanks for the ping!
