### ISSUE TITLE
Support Canvas in Windows

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#865]
With @freakboy3742 advice, I took a look at [Graphics](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics?view=netframework-4.7.2) and [Canvas](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.canvas?view=netcore-3.1) and tried to use it to develop the `Canvas` widget for Windows. Unfortunately, I haven't succeeded. I've really got lost in all the C# code.

The reason it is hard to develop this widget in Windows is that the Windows approach for painting is **event-based** while the macOS approach is **context-based**. Since *Toga* is mac-driven, it is hard to tweak its API for Windows.

If someone would make the [canvas example](https://github.com/beeware/toga/blob/master/examples/canvas/canvas/app.py) work I will jump in and develop the other APIs of the `Canvas` widget. I just need someone to make the jump start (aka, do the hard part XD).

**Comment by freakboy3742** [comment]
For the record, GTK is also an event-based drawing system. There's only 2 events that matter - "draw" (which redraws the canvas to compensate for parts of a window being uncovered) and "size allocate" (which recomputes the canvas if it changes size). The context-based approach is only intended as a convenient way to explain the geometry relationships; it should map fairly straightforward onto the drawing primitives.

**Comment by freakboy3742** [comment]
There's still a bunch of drawing instructions to implement, but they're all flagged as "not implemented" in the current implementation; they can be handled with followup PRs that fix individual instructions.
