### ISSUE TITLE
Investigate replacing Python.net with other bridging options

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#884]
Python.net has served us well as a bridge into the Windows runtime libraries; however, it seems to be plagued by maintenance problems. Six months after the release of Python 3.8, there isn't an official release supporting Python 3.8.

The good news is that Microsoft has now (as of a year ago) released [WinRT](https://pypi.org/project/winrt/), an officially maintained bridge ("projection" in Windows nomenclature) to the Windows runtime. 

It's only available for Windows 3.7 at present, but it has the advantage of being officially supported by Microsoft.

We should investigate if it is possible to port the Winforms backend to use winrt.

**Comment by saroad2** [comment]
WinRT requires Python 3.7 or higher. That means that Windows users could use Toga only with those Python versions.
Does python.net support Python 3.5-3.6?

**Comment by freakboy3742** [comment]
python.net supports Python 3.5 and 3.6, but doesn't have support for 3.8 yet. It's not clear to me if the Python 3.7 restriction on winrt is technical, or only reflects the version that has been tested and published. 

That said: It appears that winrt may not be as viable as I initially thought; conversations with some folks at Microsoft (backed up by [https://github.com/microsoft/xlang/issues/634](this ticket)) suggest that Microsoft may have lost interest in this effort.

The underlying problem is that I don't (personally) have the time to invest in determining the source of the problems with Python.net for Python 3.8; it [doesn't appear to be a priority for them either](https://github.com/pythonnet/pythonnet/issues/1066), and offers to [pay for developer time haven't been taken up](https://github.com/pythonnet/pythonnet/issues/965).

I also have a small preference for bridging tools that are pure python - Rubicon ObjC has no compiled component, as it is a wrapper over FFI. GTK has native Python bindings through GObject. This simplifies our developer story as we don't need to manage binary wheels, and we're not dependent on upstream package publication. Python.net has a compiled component, which is one of the reasons that Python version updates are problematic. 

We can't use use an FFI approach on Windows because it doesn't expose a raw C API; but there are other approaches for wrapping C++ that might be viable. [This link suggests using pybind11](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019), and also suggests some other options (including [cppyy](https://pypi.org/project/cppyy/)) that might be worth investigating.

With the news about winrt, this issue has become more as a "investigate our options" placeholder. If we can get Python.net to work, that would be great; but if there are other approaches that could work, I'm open to switching.

**Comment by saroad2** [comment]
If Python 3.8 is the main reason you want to replace Python.net with something else, don't hurry. Even Scipy and Numpy do not support Python 3.8 officially in Windows. Windows is really the black sheep when it comes to Python support. That's the reason I still use Python 3.7 in all my Python projects.

As for Python.net, once you get a grip on it, It is quite easy to use. As you know, I recently implemented the entire `Canvas` widget with Python.net and it was absolutely fine (once I figured out how to handle the paint events).

Windows support is quite behind here in *Toga*, but I'm trying to implement what I think is easy to fix and/or I need it to my own project. If you ask me, no need to replace Python.net right now, but it's a good issue to consider in the future. In the meanwhile, I will try to help as much as I can (and have time for) to add windows support where it is missing.

**Comment by tritium21** [comment]
Winapi is the native windows experience, and provides a C interface (and only a C interface).  Using it makes your application look like a line of business app from 1998, which in my view makes it utter perfection, but apparently I'm in the minority.

The question starts _*"Do you want managed or unmanaged?"*_.

 * Managed code requires a complicated binding object to .NET (you cannot use normal FFI), but gives you Winforms and WPF.
 * Unmanaged code lets you create gui's from pretty much anything (from Assembly to MicrScript can just use winapi), but again, it looks like 1998 insurance industry software.

I don't think you can cheese the system by using cppyy or pybind11 to get winforms.  While microsoft has c++ for .NET, its _managed_ c++ for .NET - it runs more like C# than unmanaged c++

**Comment by freakboy3742** [comment]
If by "winapi" you mean `pywin32`, then that's not really an option. I agree that the design of the widgets in the late 90s was a darn sight nicer than the "flat design" monstrosities that have been visited upon us in the meantime - but you can't escape the fact that it makes apps look old and out of place.

As it happens, we *had* a win32 backend for Toga; however, we've moved it to the attic. If you're especially motivated to resurrect it, feel free to contribute updates.

I'm fully aware why FFI isn't an option; the issue is finding a viable binding layer to .Net managed libraries. Python.net works... when it works. This entire ticket is about looking at whether there are viable alternatives.

**Comment by filmor** [comment]
Just some input from the Python.NET side:

We are going to cut a release soon before starting some major refactorings. The last missing item before that release is working 3.8 support. On part of the planned refactorings is using https://github.com/filmor/clr-loader/.

Now depending on whether you want to stick with Python.NET or not, you could either use that project directly, or have a look at how the `netfx_loader` part is implemented. It can serve as a template to building a .NET DLL that provides a C ABI that can then be called via `cffi`. `clr-loader` itself only provides access to functions that have the signature `static int func(IntPtr, long)` for comaptibility reasons, but if you restrict yourself to .NET Framework, it's pretty simple to use any (C compatible) signature to wrap access to WPF.

**Comment by freakboy3742** [comment]
@filmor Thanks for that update - it's good to know there's a release, and a big refactor on the way. `clr-loader` is also an interesting lead; although if there's Python 3.8 support in the pipeline, we're likely to just wait rather than rebuild everything.

**Comment by tritium21** [comment]
> 
> 
> If by "winapi" you mean `pywin32`

No, i mean windows.h

**Comment by freakboy3742** [comment]
@tritium21 Isn't that the same API that pywin32 exposes?

**Comment by tritium21** [comment]
> 
> 
> @tritium21 Isn't that the same API that pywin32 exposes?

Among other APIs, yes, pywin32 exposes the winapi (win32api), but so does ctypes with windll.  pywin32 is a lot more (i would argue far far too much) than just winapi/windows.h.  Could easily do the same with cffi.

**Comment by saroad2** [comment]
Hey guys, it seems like Python.net added a Python 3.8 support in pythonnet/pythonnet#1138.
Starting from version 2.5.0 we expect a full python 3.8 support.

I'l keep tracking this change and whenever this version will be out, I'll give it try.

**Comment by saroad2** [comment]
Hey everyone. Updated my interpreter to python 3.8 and ran a few of the example apps, and everything worked fantastically!

I think we can close this issue.

**Comment by freakboy3742** [comment]
Agreed. With Python 3.8 supported, and some [fairly clear signals from Microsoft](https://github.com/microsoft/xlang/issues/634) that winRT isn't something they're investing in, I agree that this ticket can be closed. If some other bridging option ever emerges, I'd still be interesting in exploring it - but I can't say I have anything that is a viable candidate at this point.
