### ISSUE TITLE
MultiLineTextInput Disable/enable is not working in Cocoa

### ISSUE THREAD

**Issue by ignaciocabeza** [beeware/toga#888]
## Expected Behavior
It should be possible disable/enable `MultiLineTextInput` in Cocoa.

## Current Behavior
Enable/Disable feature in `MultiLineTextInput` is not working. (ref: https://github.com/beeware/toga/blob/master/examples/multilinetextinput/multilinetextinput/app.py#L9) 

## Additional Info
In this widget `self.native` is a `NSScrollView`. `set_enabled` is updating `self.native.enabled` but text widget lives in `self.text`
(https://github.com/beeware/toga/blob/master/src/cocoa/toga_cocoa/widgets/multilinetextinput.py#L20-L30)

Also, `self.text` does not have enabled property. I found only `editable` and `selectable`. Maybe a enabled property should set this two properties?. The only this that I can't reproduce is show a "gray disabled apparence" when enabled == false
Example code:
```
    def set_enabled(self, enabled):
        self.interface.readonly = not enabled
        self.text.selectable = enabled
```

## Steps to reproduce
Run https://github.com/beeware/toga/blob/master/examples/multilinetextinput/multilinetextinput/app.py and press `toggle enabled`

## Your Environment
* Python Version (list the specific version number)
3.7

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version:
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
0.3.0.dev20

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [x] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Fixed by #1938.
