### ISSUE TITLE
A FileSelector widget would be pretty useful

### ISSUE THREAD

**Issue by massenz** [beeware/toga#918]
Definitely not a bug, and maybe I'm missing it (I'm pretty new to Toga) but looking through the Reference docs, there does not appear to be a `FileSelector` (or whatever) widget: the one that pops up when opening or saving "as" a file.

That seems a pretty basic and useful feature (of course, one could do with a text-box and `Load` or `Save` button, but that's positively 1980's): any chance it could be provided? Does it already exist and it is just not mentioned in the docs?

**Comment by freakboy3742** [comment]
I'll agree it's badly documented but the widget *does* exist: it's `open_file_dialog()` on a Window object. E.g.,, from inside the startup method of an app, you could run:
```
    self.main_window.open_file_dialog(title="Which file?", multiselect=False)
```
Documentation of this (and other) features is something that is most definitely on our todo list.

**Comment by massenz** [comment]
Awesome, thanks!
Anything I can help with that?

**Comment by freakboy3742** [comment]
Absolutely - submit a docs PR :-)

But seriously: we already have [autogenerated docstrings for this API](https://toga.readthedocs.io/en/latest/reference/api/window.html#toga.window.Window.open_file_dialog
) - although I notice that the docstring isn't fully fleshed out (there's no description of the arguments). Filling out those extra details would be one possible contribution. 

However, the fact that the docs exist clearly didn't help you find out that this API existed. So - the question becomes "What path/story would have helped you find this answer on your own?" Perhaps a topic guide about dialogs? A HOWTO on file handling? Something else? We're open to suggestions - and contributions. If you've got any questions or need any more details, we're happy to fill in any blanks.

**Comment by massenz** [comment]
Well, to be honest, what tripped me was to assume that a `FileDialog` would be a self-standing widget (and, ahem, having it as a function appended to a `Window` class wouldn't have been my first choice :) ).

And having just now typed the very `toga open file dialog` words in DuckDuckGo, the `MainWindow` ref doc happily shows up as the second result, and the useful information is just there.
(also, now savvy, I found out the `select_folder_dialog()` method which was next on my list - and noticed a quirk: it does return a list, even when `multiselect=False` is set).

So I'm happy to notch this one up to today not really being my day and bedtime fast approaching...

The offer to help still stands, and I'll happily fill out the "extra details."

BTW - even though I barely scratched the surface, Toga is pretty awesome and would appear to be solving a problem for me which I was really dreading (writing up a UI for MacOS, for my python app) so thank you so much!!!

**Comment by massenz** [comment]
Having given your question a bit more thought, it's fair to say that the [How-To](https://toga.readthedocs.io/en/latest/how-to/index.html#how-to) section is on the slim side, so maybe a "guided app" how-to would be nice: essentially, the full app cycle, from the user opening a file, to doing something with it, to saving it would be useful.

As this is exactly what I'll be doing for my [encryption app](https://bitbucket.org/marco/filecrypt) I may be convinced at some point to write up my journey :)

**Comment by fralau** [comment]
Would it not be reasonable to have a widget for a file picker and a directory picker, like e.g. [FileBrowser](https://pysimplegui.readthedocs.io/en/latest/#save-open-buttons) in PySimpleGui?

At first glance, I would consider that kind of a feature as a prerequisite for migrating projects over to Toga.

**Comment by freakboy3742** [comment]
@fralau It's a good thing that [`Window.open_file_dialog()`](https://toga.readthedocs.io/en/latest/reference/api/window.html#toga.window.Window.open_file_dialog), [`Window.save_file_dialog()`](https://toga.readthedocs.io/en/latest/reference/api/window.html#toga.window.Window.save_file_dialog) and [`Window.select_folder_dialog()`](https://toga.readthedocs.io/en/latest/reference/api/window.html#toga.window.Window.select_folder_dialog) exist, isn't it :-)

**Comment by fralau** [comment]
@freakboy3742 Oh good... Interesting that they are connected to the Window object (philosophically this might perhaps be the right decision?). I had remained on the comment of 2020, that it wasn't documented; but this was obviously done in the mean time.

I guess that if one wanted to write a ready-made widget that included a label, a text entry field, and a button that opens a file dialog, what would not be too difficult to do?
