### ISSUE TITLE
Pip uninstalling toga-winforms leaves behind test files

### ISSUE THREAD

**Issue by obulat** [beeware/toga#935]
## Expected Behavior

Running `pip uninstall toga-winforms` should remove all files related to it. 

## Current Behavior

The tests folder is left in `site-packages`:
![SharedScreenshot](https://user-images.githubusercontent.com/15233243/83575099-7f8db880-a537-11ea-877b-a8d2fd7fcd24.jpg)

## Steps to reproduce

1. Run `pip install --pre toga`. See that it installs:
`Installing collected packages: travertino, zipp, importlib-metadata, toga-core, pythonnet, toga-winforms, toga
Successfully installed importlib-metadata-1.6.0 pythonnet-2.4.0 toga-0.3.0.dev19 toga-core-0.3.0.dev19 toga-winforms-0.3.0.dev19 travertino-0.1.3 zipp-3.1.0`

2. Run `pip uninstall toga` to uninstall toga.

3. Run `pip uninstall toga-winforms`. See the messages in the screenshot. The `tests` folder inside site-packages is not removed.

## Your Environment

* Python Version 3.7.5

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: 2004 (OS Build 19041.264)
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
toga-0.3.0.dev19

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by saroad2** [comment]
Is there any reason that we deploy the tests files with the package?
Maybe we should exclude them in the MANIFEST.in file.

**Comment by freakboy3742** [comment]
We can’t remove them from the manifest; otherwise they won’t be included in the source tarball. 

I suspect the cause is a problem in the setup.py that results in the tests directory being identified as part of the app, not extra content.
