### ISSUE TITLE
Option Container/Option Item breaks the widget structure

### ISSUE THREAD

**Issue by Bobw147** [beeware/toga#946]
## Expected Behavior

When iterating through the content of an OptionContainer it would be natural to expect it to return a reference to the widget that was originally added as happens with other containers. 

## Current Behavior

If you add a widget to an OptionContainer and then iterate through its content, the item returned is not a reference to the widget but to an object of type OptionItem which contains the widget as a member. 

Because OptionItem does not support the same public interface as a Widget an error naturally occurs when trying to access any Widget attributes.

When the widget is added as content of an OptionContainer it becomes a member of an auto-created OptionItem when appending the widget to the OptionList which holds the OptionContainer's content. This means that while adding widgets to the OptionContainer the OptionItem object is an invisible implementation detail of the containers OptionList. 

## Steps to reproduce

If, for example, I want to display a formatted list of the whole GUI structure in order to show information about each widget then an obvious way to do this is to perform a recursive decent of the node tree. In most instances this will work fine because the iterating through the children/content of a widget will return another Widget object. Iterating through an OptionContainer content however breaks this rule. The process can currently only be 'corrected' by checking the type of object returned at every stage of the iteration.

## Your Environment

* Python Version (list the specific version number)
3.7.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x ] macOS - version: 10.15.4
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
0.3.0dev20
* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [x] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by Bobw147** [comment]
Having investigated this further the addition of:
`
    def __getattr__(self, name):
        return self._widget.__getattribute__(name)
`
to OptionItem solves the problem of reading attribute values of the widget while addressing the OptionItem instance.

**Comment by freakboy3742** [comment]
I think this feature request may have become deprecated as a result of some more recent changes to OptionContainer.
