### ISSUE TITLE
Iterating through a window widget tree structure is convoluted

### ISSUE THREAD

**Issue by Bobw147** [beeware/toga#947]
## Expected Behavior

Performing a recursive descent through the widget content of a window should follow a relatively straight forward pattern where each widget can be handled in the same way.

## Current Behavior

A recursive descent process on a window's content needs to process different types of widget in different ways and is overly complex as a result. It is best understood by way of example as given below.

## Steps to reproduce

The following code outline shows all of the steps necessary to work down the widget tree

`
    def get_widget_info(self, widget, indent):
        spacing = ' ' * 4 * indent
        output = spacing + 'widget id = ' + widget.id + \n
       ... add other widget data to output as required

        # See if widget is an Option, Split or Scroll container
        if hasattr(widget, '_content'):
            if isinstance(widget, ScrollContainer):
                # ScrollContainer has a single widget content
                next_widget = widget._content
                output += get_widget_info(next_widget, indent + 1) + '\n'
            else:
                # SplitContainer and OptionContainer have a widget list content
                for next_widget in widget.content:
                    # OptionItem has an extra level of indirection
                    if isinstance(next_widget, OptionItem):
                        next_widget = next_widget._widget
                    output += get_widget_info(next_widget, indent + 1) + '\n'
        else:
            # Box has widget list of children rather than content
            for next_widget in widget.children:
                output += get_widget_info(next_widget, indent + 1) + '\n'
       return output
`
This process also falls foul of the problem described in #946 and requires a modification to OptionItem in order for the above to work.

Ideally it should be possible to do this a simply as
`
def get_widget_info(self, widget, indent)
        spacing = ' ' * 4 * indent
        output = spacing + 'widget id = ' + widget.id + \n
       ... add other widget data to output as required

        for next_widget in widget.[iterable list]:
            output += get_widget_info(next_widget, indent + 1) + '\n'
       return output
`

## Your Environment

* Python Version (list the specific version number)
Python 3.7.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
toga 0.30.dev20

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [x ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
I'm not sure I 100% agree. There's definitely value in being *able* to iterate. However, the differences between widgets exist for a reason - the widgets have different needs.

Since there isn't a specific proposal (or at least, there isn't a specific proposal beyond "this thing (that may not be possible) should be possible"), I'm going to close this ticket.
