### ISSUE TITLE
[Enhancement] Submenus

### ISSUE THREAD

**Issue by robinsiebler** [beeware/toga#956]
## Expected Behavior
I would like to have submenus, for example: File > Recent > List of recent files

## Current Behavior
Submenus are not supported

## Your Environment

* Python Version (list the specific version number): 3.7.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version: 10.15.5
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash): 0.2.15

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [x] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Agreed; submenus could be helpful.

I would also note that you've really defined two features here; the *existence* of submenus, and the specific subset of submenus that is a "list of data" (like recent files/documents). A list of menu items backed by a data source is common enough use case that we should expose a simple interface to that.

**Comment by saroad2** [comment]
I'm on it
