### ISSUE TITLE
[Enhancement] Icons for menu Items

### ISSUE THREAD

**Issue by robinsiebler** [beeware/toga#957]
## Expected Behavior
I would like to be able to have icons next to menu (Command) items. This is a common feature in other frameworks

## Current Behavior
This is not currently supported.

## Your Environment

* Python Version (list the specific version number): 3.7.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version: 10.15.5
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash): 0.2.15

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [x] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the suggestion. Icons can already be associated with menu items; the decision to *not* use that icon on the cocoa backend is an explicit choice. 

While menu icons might be a common feature in other frameworks, it's *not* compliant with of the Apple HIG - in fact, they [*explicitly* advise against it](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/#using-icons-in-menus). Toga aims to produce apps that are compliant with local HIG documentation wherever possible.
