### ISSUE TITLE
New Widget Does Not Get Added

### ISSUE THREAD

**Issue by Vipul-Cariappa** [beeware/toga#989]
## Expected Behavior

A new Label Widget needs to get added.

## Current Behavior

New Label Widget does not get added.

## Steps to reproduce

<pre>
from toga import Box, Button, Label, App, MainWindow
from toga.style import Pack
from toga.constants import COLUMN

class BugApp(App):

    def startup(self):
        self.main_window = MainWindow(title=self.name)

        self.label1 = Label('Some Text...')
        self.button1 = Button(label='Add New Label', on_press=self.add_widget)

        self.box = Box(children=[self.label1, self.button1], style=Pack(direction=COLUMN, padding=20))

        self.main_window.content = self.box
        self.main_window.show()

    def add_widget(self, button):
        x = Label("New Label")
        self.box.add(x)
        self.box.refresh()

if __name__ == '__main__':
    app = BugApp('BugApp', 'mybugapp')
    app.main_loop()

</pre>

## Your Environment

* Python Version 3.7

* Operating System and Version 

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - Windows 10
  - [ ] Other - name:  - version:

* Toga Version 
  - [x] 0.3.0.dev23

* Toga Target 

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by Vipul-Cariappa** [comment]
If we replace 
<pre>
self.main_window.content = self.box
</pre>
with
<pre>
self.main_window.content = Box(children=[self.box])
</pre>
it works as expected.

**Comment by Bright-Shard** [comment]
I'm having a similar issue with buttons, but that solution doesn't work for me.

**Comment by freakboy3742** [comment]
I believe these issues have been addressed, and are now formally tested with #1834.
