### ISSUE TITLE
Keyboard shortcut in tutorial 2 is not working

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#991]
**Describe the bug**
I was expecting Ctrl+k on Windows 10 to trigger action 3, but it didn't seem to do anything.

**To Reproduce**
1. Go to https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html
2. Run the code
3. Press `<MOD_1>+k`
4. Notice how the terminal doesn't print anything

**Expected behavior**
Expected `action 3` to br printed.

**Environment:**
 - Operating System: Windows 10
 - Python version: CPython 3.8.3
 - Software versions:
   - Briefcase:
   - Toga: 0.3.0dev22
   - ...

**Comment by freakboy3742** [comment]
Thanks for the report. Not sure what is going on here, but it's definitely a problem.
