### ISSUE TITLE
Table examples not rendering appropriately

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#992]
**Describe the bug**
https://toga.readthedocs.io/en/latest/reference/api/widgets/table.html has examples that are not rendering as code.

**To Reproduce**
1. Go to https://toga.readthedocs.io/en/latest/reference/api/widgets/table.html
2. Go to the "Examples" section
3. Notice how only the first example is getting rendered

**Expected behavior**
All the examples to be rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/54418/88596126-40e91b80-d019-11ea-9616-0b4533eb82eb.png)

**Comment by freakboy3742** [comment]
Looks like this has been fixed.
