### ISSUE TITLE
Setting `Table(missing_value="")` does not silence the warning about a missing value in data

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#993]
**Describe the bug**
Explicitly setting `Table(missing_value="")` (i.e. the empty string and not `None`) does not silence the warning about the missing value:
```
WARNING: Using empty string for missing value in data. Define a 'missing_value' on the table to silence this message
```

**To Reproduce**
1. Go to https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html
2. Run the code
3. Notice the terminal says, `WARNING: Using empty string for missing value in data. Define a 'missing_value' on the table to silence this message`
4. add `missing_value=""` to the `toga.Table()` call
5. Re-launch the app
6. Notice the warning persists

**Expected behavior**
To have no warning when the empty string is specified.

**Environment:**
 - Operating System: Windows 10
 - Python version: CPython 3.8.3
 - Software versions:
   - Briefcase:
   - Toga: 0.3.0dev22
   - ...

**Comment by freakboy3742** [comment]
Thanks for the report. I'm guessing this is classic "is None" vs "False" handling.
