### ISSUE TITLE
Not specifying an `on_select` callback for Table leads to a TypeError

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#994]
**Describe the bug**
If you leave out a `on_select` callable on `Table` and click a row, you get a traceback in the terminal:
```python
Traceback (most recent call last):
  File "C:\\Users\\brcan\\Desktop\\snippets\\.venv\\lib\\site-packages\\toga_winforms\\widgets\\table.py", line 74, in _native_item_selection_changed
    self.interface.on_select(self.interface, row=self.interface.data[e.ItemIndex])
TypeError : 'NoneType' object is not callable
```

**To Reproduce**
1. Go to https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html
2. Run the example
3. Click on any row of the table

**Expected behavior**
No error.

**Environment:**
 - Operating System: Windows 10
 - Python version: CPython 3.8.3
 - Software versions:
   - Briefcase:
   - Toga: 0.3.0dev22
   - ...

**Comment by freakboy3742** [comment]
Thanks for the report! Looks like an oversight on the event handling of the Windows backend.
