### ISSUE TITLE
Have tutorial 3 open up pybee.org by default

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#995]
**Is your feature request related to a problem? Please describe.**
https://toga.readthedocs.io/en/latest/tutorial/tutorial-3.html shows a screenshot of pybee.org being opened, but the code defaults to github.com.

**Describe the solution you'd like**
Have the code direct to pybee.org by default.

**Describe alternatives you've considered**
An updated screenshot of the tutorial to show github.com.

**Comment by freakboy3742** [comment]
Good catch. It would probably be better to converge on `beeware.org` - if only because we won't get the banner about not supporting old browser versions.
