### ISSUE TITLE
Drawing from tutoral 4 does not match the screenshot

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#996]
**Describe the bug**
The drawing doesn't match the picture. 😉 

**To Reproduce**
1. Go to https://toga.readthedocs.io/en/latest/tutorial/tutorial-4.html
2. Run it
3. Look at the picture and see how it looks like a [CSS joke mug](https://www.zazzle.com/rlv/css_is_awesome_coffee_mug-r2b2e63ffaa0a46628fb84f0844e7bf9d_x7jg9_8byvr_512.jpg)

**Expected behavior**
Match the picture.

**Screenshots**
![image](https://user-images.githubusercontent.com/54418/88597836-fcf81580-d01c-11ea-873f-2324f490e502.png)

**Environment:**
 - Operating System: Windows 10
 - Python version:
 - Software versions: Cpython 3.8.3
   - Briefcase:
   - Toga: 0.3.0dev22
   - ...

**Comment by freakboy3742** [comment]
Thanks for the report. I thought we had nailed all the font sizing problems on Windows... evidently not. Confirming one detail that might be impacting here - I remember from the past that you had your desktop at 150% scale. Is that still the case?

**Comment by brettcannon** [comment]
Yep, still 150% (but a different computer). And actually that was reported a year ago when I tried to use Toga during the same Hackathon event. 😄

And the test isn't entirely crisp; should I file a separate issue on that?

**Comment by freakboy3742** [comment]
Hrm... I'm surprised this was reported a year ago - the canvas was only implemented on Winforms earlier this year. Or are you referring to something else being reported a year ago?

The text "crispness" should definitely be a separate issue, though. We *should* be using antialiasing, so unless that's been turned off somehow, I'm intrigued why we'd be seeing chunky text.

**Comment by brettcannon** [comment]
"Reported a year ago" as in the 150% scaling and having issues. (It's Hackathon week at work and as is now tradition, I am going through the Toga tutorial on Windows on my first day 😄 .)

**Comment by freakboy3742** [comment]
Ah - right; so that ticket (#710) was in a slightly different context (layout of Labels, rather than text on a Canvas). We've resolved the problem in labels (which was a fundamental layout problem in 150% scaling); this time, it looks like it's a problem with evaluating the size of text on a canvas. It's not related to scaling this time; I see the same problem at 100%.
