### ISSUE TITLE
Warning in tutorial about Python 3.8 and Windows does not seem to still be true

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#997]
**Describe the bug**
The docs at https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html say that under Windows 10 there is an issue with unsupported packages with Python 3.8. But I just ran all the tutorial examples without issue on Windows 10.
**Environment:**
 - Operating System: Windows 10
 - Python version: CPython 3.8.3
 - Software versions:
   - Briefcase:
   - Toga: 0.3.0dev22
   - ...

**Comment by freakboy3742** [comment]
Ah - thanks. This *was* true up until about a month ago; I removed the message from the BeeWare tutorial, but missed the reference in the Toga tutorial.
